### ISSUE TITLE
How to set user prompts?

### ISSUE THREAD

**Issue by firslov** [karthink/gptel#100]
When using `gptel-send` or other functions, how can I customize my own prompt?

**Comment by karthink** [comment]
`M-x customize-variable` ⏎ `gptel-directives`

**Comment by firslov** [comment]
I found this variable, but how to use the new prompt with `gptel-send`, is there a way to select a prefix-arg when calling `gptel-send`?

**Comment by karthink** [comment]
Yes. Suppose `gptel-send` is bound to `C-c RET` (control + c, return). Then you can add a control+u before: `C-u C-c RET`.  This will bring up a menu where you can set various parameters for the chat.

**Comment by firslov** [comment]
Thanks, I tried it, and the effect is just amazing.

**Comment by nigo81** [comment]
> Yes. Suppose `gptel-send` is bound to `C-c RET` (control + c, return). Then you can add a control+u before: `C-u C-c RET`. This will bring up a menu where you can set various parameters for the chat.
> 
> If it is not bound to a key, you can run `C-u M-x gptel-send` ⏎

I use evil keybinding, when i press c-u ,it scrolls up. How to do it with evil keybindings? 
Thanks

**Comment by ronnac** [comment]
Same question: in evil mode C-u is already taken. Can this be achieved otherwise?

**Comment by karthink** [comment]
> Apparently, in evil-mode SPC-u replaces C-u.

That's not the case unless you've explicitly set it up that way, or if you use Doom Emacs/Spacemacs.

Usually you can type in a number before the command in `evil-mode` to specify the prefix arg.  For example, `1 M-x gptel-send`.

gptel's menu can also be called directly via `M-x gptel-menu`, this is the same as `C-u M-x gptel-send`.
