### ISSUE TITLE
Using more than heading as part of the question in dedicated chat window?

### ISSUE THREAD

**Issue by daedsidog** [karthink/gptel#101]
So far I've been playing my entire question in the heading when its a one-liner, but when I have a question which can't fit in a single line (i.e. a few quoted paragraphs) I just leave the header empty and paste my question below. Sometimes, I give the summary to my question in the heading, my question in the body, and leave a new subheading, labelled as answer, for him to fill in the body of.

I understand that there may be no real standard way of doing these things. To be frank, it worked for me so far, but I'm wondering if this is the best way to go about it, or does it really not matter?

**Comment by karthink** [comment]
> I understand that there may be no real standard way of doing these things. To be frank, it worked for me so far, but I'm wondering if this is the best way to go about it, or does it really not matter?

It doesn't matter at all, the formatting is completely irrelevant to the chat interface.  I don't even use headings, markdown/org-mode or `M-x gptel` most of the time, I just open a scratch buffer or eshell and type away.

**Comment by daedsidog** [comment]
> It doesn't matter at all, the formatting is completely irrelevant to the chat interface. I don't even use headings, markdown/org-mode or `M-x gptel` most of the time, I just open a scratch buffer or eshell and type away.
I see. Thanks.
