### ISSUE TITLE
[Feature request] dedicated chat buffer send by header 

### ISSUE THREAD

**Issue by nehrbash** [karthink/gptel#102]
# Problem
Starting multiple conversations in a dedicated chat buffer requires opening a new conversation buffer or deleting the old conversation.
# Request 
If instead of send by buffer there was an option to send by first level org header you could have multiple conversation in the same buffer and it would feel a little more natural starting a new conversation. 

when I get some time I will attempt to mock up a `gptel-request` to do this. `org-mark-subtree` and `outline-up-heading` should make this fairly easy.

**Comment by karthink** [comment]
M-x gptel-set-topic
(Org-mode only)

**Comment by nehrbash** [comment]
idk how I missed that, thank you!
