### ISSUE TITLE
[FR] To isolate the response from the next and previous text

### ISSUE THREAD

**Issue by Ypot** [karthink/gptel#103]
To avoid the response to be mixed with the original text, I would add an option to "Response to:"

Maybe one of these
Response to:
-b block (-b)
-q quote (-q)

So the response is separated from the previous and next text. Example:

> * Conquest of Egypt

> The Fatimid conquest of Egypt took place in 969, as the troops of the Fatimid Caliphate under the general Jawhar captured Egypt, then ruled by the autonomous Ikhshidid dynasty in the name of the Abbasid Caliphate. The Fatimids had launched repeated unsuccessful invasions of Egypt soon after coming to power in Ifriqiya in 909.
> 
> ```
> #+BEGIN_QUOTE
> I apologize for any confusion, but it seems like there might have been a misunderstanding. The Fatimid conquest of Egypt in 969 is not directly related to the early 20th-century labor strikes 
> (ChatGPT 3.5 Turbo, 2023-08-19)
> 
> #+END_QUOTE
> ```
> 
> By the 960s, the collapse of the Ikhshidid regime, and an economic crisis and factional infighting in Egypt, allowed Fatimid caliph al-Mu'izz (coin pictured) to organize a large expedition to conquer the country, aided by the activity of a network of Fatimid agents there. When the Fatimid invasion came, the Ikhshidid elites negotiated a peaceful surrender, and the brief resistance of the Ikhshidid soldiery was overcome. Jawhar took control of Fustat, the Egyptian capital, on 6 July. Jawhar served as viceroy of Egypt until 973, when al-Mu'izz arrived and took up residence in a new capital, Cairo, which became the seat of the Fatimid Caliphate.

**Comment by Ypot** [comment]
Or maybe using inline tasks.
It is needed to eval first: (require 'org-inlinetask)). 
Then:

The Fatimid conquest of Egypt took place in 969, as the troops of the Fatimid Caliphate under the general Jawhar captured Egypt, then ruled by the autonomous Ikhshidid dynasty in the name of the Abbasid Caliphate. The Fatimids had launched repeated unsuccessful invasions of Egypt soon after coming to power in Ifriqiya in 909.

```
*************** ChatGPT (2023-08-20) /Egypt/
:PROPERTIES:
:GPTEL_MODEL: gpt-3.5-turbo
:GPTEL_TOPIC: Egypt
:GPTEL_SYSTEM: I want you to act as a historian. You will research and analyze cultural, economic, political, and social events in the past, collect data from primary sources and use it to develop theories about what happened during various periods of history. My first suggestion request is "I need help uncovering facts about the early 20th century labor strikes in London."
:END:
I apologize for any confusion, but it seems like there might have been a misunderstanding. The Fatimid conquest of Egypt in 969 is not directly related to the early 20th-century labor strikes 
*************** END
```


By the 960s, the collapse of the Ikhshidid regime, and an economic crisis and factional infighting in Egypt, allowed Fatimid caliph al-Mu'izz (coin pictured) to organize a large expedition to conquer the country, aided by the activity of a network of Fatimid agents there. When the Fatimid invasion came, the Ikhshidid elites negotiated a peaceful surrender, and the brief resistance of the Ikhshidid soldiery was overcome. Jawhar took control of Fustat, the Egyptian capital, on 6 July. Jawhar served as viceroy of Egypt until 973, when al-Mu'izz arrived and took up residence in a new capital, Cairo, which became the seat of the Fatimid Caliphate.

**Comment by Ypot** [comment]
Yes, but with automatic signature.

But I think I like better using inlinetasks. There, PROPERTIES could offer information about chatgpt version and its configuration.

**Comment by Ypot** [comment]
And it could be too:

*** My headline.

My question here

#+begin_quote
ChatGPT's response here.
#+end_quote

**Comment by karthink** [comment]
@Ypot This is now possible via #142, at least when gptel-mode is turned on. See the documentation for the variables `gptel-prompt-prefix-alist` and `gptel-response-prefix-alist`.

**Comment by Ypot** [comment]
Thanks. I don't know how to, but I am closing this issue as I believe it is possible.
Bests!

**Comment by karthink** [comment]
> Thanks. I don't know how to, but I am closing this issue as I believe it is possible.

```
*** My headline.
Text here.
My question here

#+begin_quote
ChatGPT's response here.
-- (ChatGPT 3.5 Turbo, 2023-08-19)
#+end_quote

More text here

My next question here
...
```

To reproduce this set up in org-mode, for example,

```elisp
;; Place ChatGPT response between quotes
(setf (alist-get 'org-mode gptel-prompt-prefix-alist)
      "#+end_quote\n")
(setf (alist-get 'org-mode gptel-response-prefix-alist)
      "#+begin_quote\n")

;; Add LLM model info and date at end of response
(add-hook 'gptel-post-response-hook
          (defun my/gptel-add-model-info ()
            (save-excursion
              (search-forward
               (alist-get 'org-mode gptel-prompt-prefix-alist)
               nil t)
              (previous-line 3)
              (insert
               "\n-- (" (gptel-backend-name gptel-backend)
               ": " gptel-model
               (format-time-string "%Y-%m-%d)")))))
```
