### ISSUE TITLE
Confused with setting up gpt-4 

### ISSUE THREAD

**Issue by Kabouik** [karthink/gptel#106]
I needed `gpt-4` for more context tokens, and realized that I needed [add some credits to my OpenAI balance to get access to it](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4) from the API. I added some, and then immediatelyu after renewing my API key, I did notice indeed that `gptel` would suddenly succeed querying ChatGPT despite me setting the model to `gpt-4`, while it would fail before.

However, the AI replies that it is based on GPT-3 model, and its limit is 4096 tokens. This contradicts what is written [here](https://platform.openai.com/docs/models/continuous-model-upgrades), stating that `gpt-4` has a limit of 8192 tokens. I'm confused. I know this may not be a `gptel` issue, but if entering `gpt-4` when in the `gptel` configuration prompt buffer is not the right way to do it, what am I missing?

I'm sorry if I did somethign wrong, I have no experience with `gptel` yet.

**Comment by karthink** [comment]
How are you setting the model to gpt-4?

**Comment by JT-McLeod** [comment]
I am in the similar position. I have set up an platform.openai.com/account and created an API keys Secret key. This gets to the GPT-3, but not other models such as GPT-3.5-turbo or others listed under "Rate limits" tab. (NB I note that GPT-4 is missing from this list. I did expect to see it there.) Thanks

**Comment by JT-McLeod** [comment]
After setting up a pre-payment of $20, I can now see the gpt-4 option in the "Rate Limits" tab available through the ..openai.com/account. Still not able to chat with the gpt-4 model through gptel.

**Comment by JT-McLeod** [comment]
I now have "gptel-model" set to "gpt-4" and this showing in the *ChatGPT* buffer, but ChatGPT says it is "GPT-3". 
Weird!

**Comment by karthink** [comment]
> I now have "gptel-model" set to "gpt-4"

Just checking: how did you set `gptel-model` to `gpt-4`?

**Comment by JT-McLeod** [comment]
C-u C-c <RET> m and select it from the options.

**Comment by Kabouik** [comment]
> How are you setting the model to gpt-4?

I set it up with `M-x` `gptel-menu` `m` "gpt-4". But if the model was not right, the query would fail, and now it works after I added some credit to my balance; so it must be right, but somehow the model doesn't seem to be GPT-4. Is that possible that `gptel` checks if the API has access to the model before querying it, but mistakenly queries GPT-3.5 when the check passes?

I later set the model to "gpt-3.5-turbo-16k" and here, the token limit was adequately adjusted to 16k.

**Comment by JT-McLeod** [comment]
I tried to use the gpt-4-32k and got the response "ChatGPT error:" the model doesn't exist. Inference it is the API is getting the request I expect.

I then changed gptel m to gpt-4 put another $20 on credit (too ensure it wasn't the limiting factor) and asked ChatGPT "Are you gpt 4?" It's response was:
"No, I am based on OpenAI's GPT-3 model. As of the time of this interaction, GPT-4 has not been released yet. Any updates to the model version will be posted by OpenAI in their official announcements."
Meanwhile I appear to be further billed for gpt-4.
So changing back to gpt-3 for now (to protect my credit), with the intent of in the weekend blundering around in the code and looking at what is actually being sent to the OpenAI API.

**Comment by karthink** [comment]
@Kabouik and @JT-McLeod: If I understand correctly, you've paid for gpt-4 access on openai's website and can access gpt-4 directly (through a browser), but not when using gptel.

According to OpenAI, you should have access to the GPT-4 API [if you're piad more than $1](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4) so far. I haven't yet so I can't access GPT-4 to test this bug. (I can't add credits to my account since I don't see the "prepaid billing" option either; my account is older than Aug 23.)

Could you try the following curl command and let me know what the result is?

```sh
curl  --location  --silent  --compressed  --disable  -XPOST  \
      -w'(abcdefgh . %{size_header})'  -m60  -D-  \
      -d'{"model":"gpt-4","messages":[{"role":"system","content":"You are a large language model living in Emacs and a helpful assistant. Respond concisely."},{"role":"user","content":"What model of gpt are you?"}],"stream":true,"temperature":1.0}' \
      -H'Content-Type: application/json' \
      -H'Authorization: Bearer $YOUR_API_KEY'  \
      https://api.openai.com/v1/chat/completions 
```

**Comment by jmberen** [comment]
I have the same issue and I've tried the curl command you suggested. 
This is the result:
```HTML
HTTP/2 200 
date: Wed, 04 Oct 2023 23:31:53 GMT
content-type: application/json
access-control-allow-origin: *
cache-control: no-cache, must-revalidate
openai-model: gpt-4-0613
openai-organization: user-m4qjlmskyqztfbzavywlw85e
openai-processing-ms: 1328
openai-version: 2020-10-01
strict-transport-security: max-age=15724800; includeSubDomains
x-ratelimit-limit-requests: 200
x-ratelimit-limit-tokens: 10000
x-ratelimit-remaining-requests: 199
x-ratelimit-remaining-tokens: 9953
x-ratelimit-reset-requests: 300ms
x-ratelimit-reset-tokens: 282ms
x-request-id: 9d0a9127222c4f9fd7564b557d29e57a
cf-cache-status: DYNAMIC
server: cloudflare
cf-ray: 8111388aaa6d1946-BCN
content-encoding: gzip
alt-svc: h3=":443"; ma=86400

{
  "id": "chatcmpl-865dIVyGFGHXM717RTAuv3rkwN6zp",
  "object": "chat.completion",
  "created": 1696462312,
  "model": "gpt-4-0613",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "I'm based on GPT-3, OpenAI's latest and most powerful version of the Generative Pretrained Transformer series as of the time of this interaction."
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 38,
    "completion_tokens": 33,
    "total_tokens": 71
  }
}
(abcdefgh . 741)
```

**Comment by karthink** [comment]
@jmberen thanks.

It looks like it's actually gpt-4:

```
  "model": "gpt-4-0613",
```

But the answer it provides is that it's GPT-3:
```
        "content": "I'm based on GPT-3, OpenAI's latest and most powerful version of the Generative Pretrained Transformer series as of the time of this interaction."
```

I'm not sure what to make of it. :confused:

**Comment by jmberen** [comment]
Hi @karthink 
And surprisingly, it charges in on the bill as GPT-4 request...
![image](https://github.com/karthink/gptel/assets/60668335/da80d3a2-2c05-4c7e-aa55-af3db6d27142)

**Comment by Kabouik** [comment]
@JT-McLeod and @jmberen already replied (thanks), so just commenting on this:

> (I can't add credits to my account either since I don't see the "prepaid billing" option; my account is older than Aug 23.)
I had the same issue and had to disable my existing payment option to re-create it, and then the option appeared.

**Comment by PBorocz** [comment]
Based on @Kabouik's comment, I also went through the process of deleting my existing billing plan and setting a new one up (as well as creating a new key)...now my curl test **does** operate (it wouldn't before) but gives me the same odd output @jmberen got. 

Interestingly, when I try to "ask" Chat what model I'm now using (through several various attempts), it answers that it doesn't know about GPT-4 (even though it's set through `gptel-menu`)...leading me to believe its still processing using a GPT-3 version.

Haven't looked through the code but would love to look through (or set?) detailed logging to see what's going back and forth to the openai.

Net net, great tool, thanks for bringing this to fruition @karthink !!!

**Comment by karthink** [comment]
> leading me to believe its still processing using a GPT-3 version.

Based on the curl output, this bug is not related to gptel -- the curl command you tried is the one gptel uses under the hood, and ChatGPT's repsonse identifies the model as `gpt-4-0613`.

I'm leaving this issue open so we (or someone else looking into it) can figure out the inconsistency.

**Comment by jmberen** [comment]
Absolutely agree with @karthink, the bug seems an openAI API issue, not a gptel issue. By the way, my recommendation by the moment is to set the gptel-3.5-turbo model. Otherwise, you'll get GPT-3 responses but it will get billed as GPT-4 responses

**Comment by pondersson** [comment]
It seems like GPT-4 might not be aware of its own existence: https://community.openai.com/t/gpt-4-through-api-says-its-gpt-3/286881/7

**Comment by JT-McLeod** [comment]
To ChatGPT-4:
[image: User]
Hi, which model are you?

I am based on the GPT-4 architecture by OpenAI. How can I assist you
further?

**Comment by pondersson** [comment]
@JT-McLeod Is that the website version of GPT-4? According to this thread it may have some extra background prompts (and maybe training?) that help it with this particular question: https://community.openai.com/t/gpt-4-via-the-api-not-nearly-as-powerful-as-gpt-4-on-the-website/330954

I'm not sure that asking the model for its version is the most reliable test. When I pass the same questions to GPT-3 and GPT-4 through gptel and compare the responses, the ones from GPT-4 tend to be of higher quality. But I could of course be mistaken and just a victim of confirmation bias :shrug:

**Comment by JT-McLeod** [comment]
I do as @jmberen describes, run gptel with gpt-3.5-turbo. My experience is with some code, gptel doesn't have current information. For example code suggested by gptel for the Bokeh rangetool errors as it is using an earlier version. Take the code suggestion and pass it through Chat-gpt with GPT-4 and the modified code runs. Conclusion, gptel is not accessing the newer information. 

I am still impressed with and start with gptel as it better fits my workflow and thinking style :).

I have in mind to see what knowledge base JuypterAI taps and how that compares to gptel. I want to explore if they use the same API as gptel. If not then can gptel be modified to do so.

**Comment by karthink** [comment]
> run gptel with gpt-3.5-turbo.

> Conclusion, gptel is not accessing the newer information.

What happens if you run gptel with gpt-4 instead?

**Comment by leungbk** [comment]
> My initial expectation was I would get an error as I mentioned near the top of this thread. Having just tried it again (ie C-u C-c Enter, m gpt-4) and repeated the coding request I was working on, I now find I get a sensible and more refined response ! Ie it now doesn't error out. Gpt-4 seems to be working in gptel.

This used to work for me in prior checkouts, but does not on the most recent checkout of `gptel` (d7a89d7575e5d0f5148d7498536e470fda628f1e)

**Comment by karthink** [comment]
What error do you get?

**Comment by karthink** [comment]
@leungbk If you are still using gptel + gpt4, could you confirm if it does not work for you?

**Comment by leungbk** [comment]
karthink ***@***.***> writes:

> @leungbk If you are still using gptel + gpt4, could you confirm 
> if it does not work for you?

Sorry for the delay. I haven't been using GPT-4 lately, but I 
remember concluding that my previous report was a false alarm.

However, I think the issue mentioned in this thread involving an 
observed difference between `C-u C-c RET` and `C-c RET` is a real 
one. I can't provide any further testing for this since I'm not on 
GPT-4 right now.

**Comment by karthink** [comment]
> However, I think the issue mentioned in this thread involving an observed difference between `C-u C-c RET` and `C-c RET` is a real one.

Now that I can access gpt-4, I can confirm that setting the model using `C-u gptel-send` works as expected.  The chat still self-identifies as gpt-3, but the model being used is gpt-4 as the billing and the http headers attest. Assuming there's nothing else to be done from gptel's side, I'm closing this issue.
