### ISSUE TITLE
Configuration of default mode not respected

### ISSUE THREAD

**Issue by DanTheDane** [karthink/gptel#124]
I have the following in my configuration (api masked out)

(use-package gptel
   :config
   (setq gptel-api-key "xxxxxxxx")
   (setq gptel-default-mode 'org-mode)
   (setq gptel-model "gpt-4")
   )

However when I run "gptel" it always defaults to gpt-3.5-turbo:
![GPTel](https://github.com/karthink/gptel/assets/6023898/53739a67-5360-4450-b672-86306716c1ab)

The general configuration is working as the api key is picked up, and queries are successful

**Comment by karthink** [comment]
gptel-model is a buffer-local variable, you need to set it's default value.
Use setopt, setq-default or the customize interface instead of setq.

**Comment by danny-psqr** [comment]
Doh! Thank you, didn't think of that.

It works well with setq-default :-)

**Comment by DanTheDane** [comment]
Doh! Thank you, didn't think of that.

It works well with setq-default :-)
