### ISSUE TITLE
Suffix gptel--infix-provider is not defined

### ISSUE THREAD

**Issue by sergeyplis** [karthink/gptel#135]
This is happening after the 11/13/23 update
`transient-setup: Suffix gptel--infix-provider is not defined or autoloaded as a command`

Thanks!

**Comment by karthink** [comment]
Please see #132.

This is an issue with native compilation. Uninstalling the package, then deleting all `gptel-*` files in the eln-cache (`native-comp-eln-load-path`) and reinstalling the package should fix it.

Unfortunately I don't know why native compilation does not like the change in the relevant commit.

**Comment by sergeyplis** [comment]
Thanks for your reply! In my emacs `native-comp-eln-load-path` is not even defined. Yet, I went ahead and reinstalled `gptel` and when it was uninstalled checked that no mention of it is present in `.emacs.d/`. However, I get the same error. Any other things you think I can investigate?

**Comment by karthink** [comment]
Sorry, I'm not sure what else could be causing it. :(

**Comment by mekkamagnus** [comment]
I'm getting the same error. I tried uninstalling and reinstalling but I get it every time I try to "gptel-menu" or try to click to change the gpt version.

**Comment by karthink** [comment]
@sergeyplis if you are still using gptel: Is this still an issue?  There have been several updates since.
