### ISSUE TITLE
Problem due to transient

### ISSUE THREAD

**Issue by minad** [karthink/gptel#14]
Merging transient already wasn't ideal. I use gptel on Emacs 29 and I get the following error:

~~~ elisp
Error: void-function (transient-prefix)
  mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode 0x1421f3accfae8684>))
  debug-early-backtrace()
  debug-early(error (void-function transient-prefix))
  transient-prefix(:command gptel-send-menu)
~~~

Couldn't you avoid relying on the newest features of transient? It would be great if this works out of the box with the transient version from Emacs 29 (or even better Emacs 28 only).

**Comment by tarsius** [comment]
The `builtin` branch in my repository tracks the version that is included in Emacs' `emacs-29` branch.

**Comment by minad** [comment]
> What does "merging transient" mean here?

I meant that @karthink merged the transient branch of gptel, which requires new transient functionality. This broke my Emacs configuration, but it should be alright as soon as you release the next version of Transient.

> I intend for the next transient release to also be included in Emacs 29.

That's good!

**Comment by karthink** [comment]
Did gptel become completely unusable, or is it only giving an error when you try to bring up the menu with a prefix arg?

> Couldn't you avoid relying on the newest features of transient? It would be great if this works out of the box with the transient version from Emacs 29 (or even better Emacs 28 only).

It should work with the Transient version included with Emacs 28 -- before merging into master I removed the section of the code (dynamically generated menu options) that required the newer version of Transient.  I tested it with `emacs -q` as well.

``` text
Error: void-function (transient-prefix)
  mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode 0x1421f3accfae8684>))
  debug-early-backtrace()
  debug-early(error (void-function transient-prefix))
  transient-prefix(:command gptel-send-menu)
```

This error is quite strange!  I can't figure it out.  Just to be sure this isn't related to how I autoload/require things, could you run `load-file` on `gptel-transient.el` in an Emacs session before using gptel?

**Comment by minad** [comment]
That's strange. Why did package-install install transient then as a separate package, despite Emacs 29?

**Comment by karthink** [comment]
The header in `gptel.el` is

```emacs-lisp
;; Package-Requires: ((emacs "27.1") (aio "1.0") (transient "0.3.7"))
```

And in my Emacs 28.2, `/usr/share/emacs/28.2/lisp/transient.el.gz` has in its header

``` emacs-lisp
;; Package-Version: 0.3.7
```

So I'm not sure what's going on either.

**Comment by karthink** [comment]
> Did gptel become completely unusable, or is it only giving an error when you try to bring up the menu with a prefix arg?

@minad can you confirm this?  If gptel is completely unusable because of transient issues, this is a much higher priority problem and I might need to revert HEAD.  If _only_ the transient menu is broken I can wait for a few days for the next version to be released and test after that.  The menu is currently an undocumented feature.

**Comment by minad** [comment]
It completely broke my config for a while, since somehow the package-quickstart.el started to throw errors. I reinstalled without gptel-transient.el. I can try again later.

**Comment by karthink** [comment]
@minad I think I fixed the transient issue in 9da22155 -- the autoload cookie was wrong.  Please test when you can.

**Comment by tarsius** [comment]
Ah, yes, those damn autoload cookies.

**Comment by minad** [comment]
Thanks, it is fixed now!
