### ISSUE TITLE
Release schedule for new versions

### ISSUE THREAD

**Issue by 9s-l-s9** [karthink/gptel#148]
Hello,

I wanted to test the ollama integration with the `emacs-gptel` package. 
I've noticed that the current version published is 0.4.0, where this seems to not be included? (I am using guix to manage my emacs packages and there it is tracking the published versions).
 
Could you please provide some information on when the next version of `emacs-gptel` is expected to be released? :)

Thank you in advance.

**Comment by karthink** [comment]
Interesting timing! I was planning to tag v0.5.0 later today. Please check
in 5-6 hours.

**Comment by karthink** [comment]
Version 0.5.0 is now published.
