### ISSUE TITLE
Add gemini backend support?

### ISSUE THREAD

**Issue by mrdylanyin** [karthink/gptel#149]
Gemini is Google’s AI model and free for personal usage. User can get an API key via their [page on Google AI Studio](https://makersuite.google.com/app/apikey)

**Comment by karthink** [comment]
Sure. Would you be interested in adding it?

**Comment by mrdylanyin** [comment]
I really want to make this feature happen, but truth be told, I'm a newbie when it comes to writing Emacs Lisp. Spent a few hours digging through the source code, and I'm still clueless on where to begin. Apologies for that.

**Comment by karthink** [comment]
@mrdylanyin Almost all of the code is LLM agnostic, so it will not need changing.  You also do not need to understand these parts to add a new backend. Assuming gemini has a http API and replies with JSON, there are only three API-specific functions (technically implementations of generic methods) needed:

- `gptel--parse-buffer`: This scans the buffer where you type and assembles a list of user prompts and LLM responses.
- `gptel--request-data`: This creates the full payload (to be JSON encoded and sent) including all model parameters required by the API.

If streaming responses are supported:
- `gptel-curl--parse-stream`: This extracts the content of the response from the JSON stream returned by the API.
If streaming responses are not supported:
- `gptel--parse-response`: This extracts the content of the response from the full JSON structure returned by the API.

You can look at the implementation of these methods (as `cl-defmethod`) in the files `gptel-openai.el` and `gptel-ollama.el`.  You might be able to get gemini working just by tweaking one of these.
