### ISSUE TITLE
Query can be restarted multiple times

### ISSUE THREAD

**Issue by minad** [karthink/gptel#15]
When pressing C-c RET on a headline multiple times, it seems possible to restart the query. This does not seem desired. It would be better if gptel prints an error message if a query is already running and hasn't completed yet.

**Comment by karthink** [comment]
Yes, this needs to be fixed.  I think multiple queries from one buffer is fine -- for example if you are in a non-dedicated (i.e. regular) buffer and want to ask multiple unrelated queries:

``` text
How many satellites are in orbit around the earth?

What is speedrunning in videogames and when did this practice begin?
```

You can select each line and call `gptel-send`.  However, we want to avoid sending the same request multiple times. I'll create a list of hashes (buffer-local) for currently active queries and check against that.  If you have a better idea please let me know.

**Comment by minad** [comment]
I think it is okay to keep it simple and just allow a single requetat a time, since the API is not fast anyway.

**Comment by karthink** [comment]
My reason for enabling multiple parallel requests per buffer is _because_ the API is not fast.  That said one request per buffer is a simpler solution, I can implement it and see if it feels limiting in usage.

**Comment by minad** [comment]
Sure, but I usually start a query and then refine the prompt. Starting multiple independent queries seems only useful if you run multiple "conversations" in parallel. There is also the danger of hitting some rate limit. Maybe each gptel buffer could run independently.

**Comment by guibor** [comment]
@karthink perhaps it would be possible to configure a `gptel-send-hook` variable, and for anyone interested in avoiding multiple parallel queries it would be possible to add a `gptel-abort` to the hook?
It would be imperfect as it would not be buffer-specific but users could configure that, or even make the hook local to certain types of buffers (e.g if using the gptel conversational buffer it is more likely that this behavior would be desired)

**Comment by karthink** [comment]
@guibor here is a recipe for disallowing multiple requests from one buffer -- only works with Curl though:

``` emacs-lisp
(defun gptel-throttle-request (orig-fn &rest args)
  (if (seq-some (lambda (request)
                  (eq (current-buffer)
                      (plist-get request :buffer)))
                (map-values gptel-curl--process-alist))
      (message "gptel request cancelled: there is an active request in buffer %s"
               (buffer-name (current-buffer)))
    (apply orig-fn args)))

(advice-add 'gptel-request :around #'gptel-throttle-request)
```

I can add it as an option to gptel but it needs more work to support `url-retrieve`.

**Comment by guibor** [comment]
Hi @karthink this is really awesome and seems to work really well.

I have one issue though: if I add the advice before my first query, I get the following error:
`seq-some: Symbol’s value as variable is void: gptel-curl--process-alist`

So I need to remove the advice, use gptel-send at least once, and only then add the advice back.
Does this make sense? Any reason why?

(Thanks again for all your amazing work!)

**Comment by karthink** [comment]
> So I need to remove the advice, use gptel-send at least once, and only then add the advice back.

It's because `gptel-curl.el` is not loaded until required.  Adding a `(require 'gptel-curl)` into the mix should fix it. (Updated above).

**Comment by karthink** [comment]
Closing this issue since, with the benefit of hindsight, there are many uses for gptel where it is desirable to have more than one request active in a buffer.

**Comment by yantar92** [comment]
What if it is made into a defcustom though? Clearly, some people use gptel differently.

**Comment by karthink** [comment]
> What if it is made into a defcustom though? Clearly, some people use gptel differently.

Yes, we can add a defcustom for this.  The default will be the current behavior.

I'm worried about inactive requests registering as active because of bugs in the
request pipeline.  If a request throws an unhandled error somewhere, it will
count as active (indefinitely) and the user will be locked out of calling
`gptel-send` in the buffer.

Another edge case is what happens if the user has canceled tool calls and
gptel's FSM is in the TOOL state.  Such a request can be resumed from
`gptel-menu` right now.  Is this an active request?  Should it block a new call
to `gptel-send`?

Here is a prototype, implemented as advice here but can be implemented inline
eventually.  This requires gptel to be updated to v0.9.9.6:

``` emacs-lisp
(defcustom gptel-single-request nil
  "Only allow one active request at a time in a buffer."
  :type 'boolean
  :group 'gptel)

(define-advice gptel-send (:before-until (&optional arg) single-request)
  "Only allow a single active `gptel-send' request in the buffer.

This requires `gptel-single-request' to be set."
  (when (and gptel-single-request (not arg) (gptel--fsm-live-p))
    (message "Ignoring gptel-send call; a request is active in \"%s\""
             (buffer-name))))
```

This has the above mentioned edge cases.

`gptel--suffix-send` will also need to be similarly advised/edited.
