### ISSUE TITLE
No response/error indicator when executing `gptel`

### ISSUE THREAD

**Issue by randomwangran** [karthink/gptel#16]
Execute `M-x gptel`, it saids Waiting, but no response can received. 
`(setq gptel-api-key "sk-xxxxx")` has been executed. Here's a screenshot:

https://user-images.githubusercontent.com/8197831/224576530-a1888203-46a3-4886-970b-f5e7a1511c59.mp4

**Comment by karthink** [comment]
Hi @randomwangran,

I just added a debug setting to diagnose issues like this. Could you

(i) Pull the latest from this repo and install/load it,
(ii) Run `(setq gptel--debug t)` before running gptel,
(iii) Run gptel and wait for a buffer named `*gptel-error*` response to pop up,
(iv) and paste the contents of the buffer here?

If no such buffer pops up, that's helpful too and you can let me know.

**Comment by jmercouris** [comment]
I ran the code, waited several minutes, and no error buffer popped up.

**Comment by karthink** [comment]
@jmercouris Thank you. Is the value of `gptel-use-curl` non-nil for you? (It might look like `/usr/bin/curl`)

**Comment by jmercouris** [comment]
```
gptel-use-curl is a variable defined in ‘gptel.el’.

Its value is t

Whether gptel should prefer Curl when available.

  You can customize this variable.
```

**Comment by jmercouris** [comment]
Please note:

```
[jmercouris@system:~/.emacs.d/packages]$ which curl
/run/current-system/sw/bin/curl
```

I am running NixOS.

**Comment by karthink** [comment]
Could you set `gptel-use-curl` to `nil` and check if the problem persists?

**Comment by ydche3** [comment]
The same problem. And set `gptel-use-curl` in `gptel.el` to `nil` couldn't solve the problem.

**Comment by karthink** [comment]
@ydche3 Could you try again? I removed the aio dependency and made the code simpler to debug in 040baad9.

**Comment by ydche3** [comment]
> @ydche3 Could you try again (with `gptel--debug` set to `t`)? I removed the aio dependency and made the code simpler to debug in [040baad](https://github.com/karthink/gptel/commit/040baad9101d8bb2bedbedc15b9b8f00cc7d9c05).

Without any difference. But I noticed that whenever run `C-c RET` to send my query, the request wasn't sent behind my proxy.
Here is my emacs proxy setting:
```
(setq url-proxy-services '(("http" . "127.0.0.1:7890")
                           ("https" . "127.0.0.1:7890")))
```
Should I change my proxy setting?

**Comment by karthink** [comment]
You shouldn't have to change your proxy settings. Did you notice this with `gptel-use-curl` set to `nil`, `t` or both?

**Comment by flashjames** [comment]
I have the same problem, it worked first when I tried the mode 4 days ago, but when I tried again today it doesnt return any answers.

I set: "(setq gptel--debug t)"

Where should that info be displayed? (no new buffer with messages with gptel atleast).

When I call the same api end point with javascript and axios, I get answers so it shouldnt be a open ai api problem.

**Comment by karthink** [comment]
> I have the same problem, it worked first when I tried the mode 4 days ago, but when I tried again today it doesnt return any answers.

Just checking, are you on the latest commit? (I just added more error reporting.)

**Comment by flashjames** [comment]
No the readme was clear, it was my bad not re-reading it again.

Thank you for the work on this mod!

**Comment by karthink** [comment]
> Like ChatGPT ready - Hint: Dont forget to do gptel-send

The package already does this, I'm not sure what you mean. Here is what I see:
![2023-03-24-175832_871x365_scrot](https://user-images.githubusercontent.com/8607532/227671091-de79ad9b-1b1b-4434-8b3e-aaa3e35c0bee.png)

**Comment by karthink** [comment]
@jmercouris do you still see this error?

**Comment by jmercouris** [comment]
it works now, i installed via melpa

**Comment by karthink** [comment]
> Like ChatGPT ready - Hint: Dont forget to do gptel-send

@flashjames I'm closing this issue since the original problem has been solved and this hinting is addressed as well. Feel free to reopen if this is not the case.
