### ISSUE TITLE
ChatGPT error (HTTP/1.1 429 Too Many Requests)

### ISSUE THREAD

**Issue by babusri** [karthink/gptel#162]
I tried gptel today and I get the following error:
Querying ChatGPT...
ChatGPT error (HTTP/1.1 429 Too Many Requests): Could not parse HTTP response.

Tried it couple of times.
Then I tried chatgpt in the browser and it works fine.

I had not used chatgpt at all in the last day and so I don't think there is an issue of exceeding the rate of messages.

Windows 11: GNU Emacs 29.1 (build 2, x86_64-w64-mingw32) of 2023-07-31

**Comment by karthink** [comment]
Could you run `(setq gptel--debug t)`, then try using ChatGPT, and paste the contents of the buffer that opens up?

**Important**: This buffer will have your API key near the top, please remove it before pasting it.

**Comment by babusri** [comment]
I have given the error message below.
Note: I have never used the api key before. I just saved it in password manager.
I always used ChatGPT 3.5 from the browser.
This may not be relevant but I signed up for ChatGPT 4.0 a week back.
I have only made a few requests via the browser for ChatGPT 3.5 or 4 and so this error is puzzling.
In any case, this looks like a ChatGPT issue and not related to your nice package.

--------------------------------------
HTTP/1.1 429 Too Many Requests
Date: Sat, 30 Dec 2023 08:03:02 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 337
Connection: keep-alive
vary: Origin
x-request-id: b3b017312c49748de541a62af97c08bb
strict-transport-security: max-age=15724800; includeSubDomains
CF-Cache-Status: DYNAMIC
Set-Cookie:

{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

**Comment by karthink** [comment]
Looks like an OpenAi billing issue.  They changed the system a couple of times -- I think you have to preload your account with credit to access the API now.  This is independent of the ChatGPT plus service, or whatever it's called.

**Comment by babusri** [comment]
Thanks for your prompt response.
https://platform.openai.com/usage
says
$0/$18 limit

So, not sure why I am getting this error.

You can close this as a non-issue.

**Comment by karthink** [comment]
There seems to be [some discussion](https://stackoverflow.com/questions/75898276/openai-chatgpt-gpt-3-5-api-error-429-you-exceeded-your-current-quota-please) about this error -- if you generated your API key before you paid them, it's possible you may need to generate a new one.

I'll close this issue as this is unrelated to gptel, but please update if you find a solution, as it can help others.

**Comment by babusri** [comment]
Karthik,

Looks like the API credits expire in 3 months if not used.
I will purchase some credits.

The https://platform.openai.com/usage shows

[image: image.png]

Because the url says *usage *, I thought that 0% was the amount used.
But as you can see, almost 0% was used (green) but the rest (pink) says
*Expired*.

Babu
