### ISSUE TITLE
other backend

### ISSUE THREAD

**Issue by tvraman** [karthink/gptel#172]
Setting gptel-backend via customize by choosing other backends and specifying gptel-make-gemini throws a validation check

**Comment by karthink** [comment]
@tvraman The description for gptel-backend might be confusing.  As of right now, this works:

```elisp
(setopt gptel-backend (gptel-make-gemini
                              "Gemini"
                              :key (lambda ()
                                     (auth-source-pass-get
                                      'secret "api/ai.google.com"))
                              :stream t))
```

This is using the customize system to set the backend correctly.  Are you looking for a way to create a Gemini backend (among others) interactively from the Customize menu?

**Comment by tvraman** [comment]
Works now, I think I got myself very confused -- mostly as a result of
playing with multiple front-ends and back-ends in the same Emacs
session. That said, adding what you sent by email as part of the docs
for "other" would help.
-- 

--

**Comment by karthink** [comment]
Thanks for the confirmation.  A fully interactive way to specify a backend (in the customize interface) would be nice to have too, but it's a low priority for now.

**Comment by karthink** [comment]
kk
