### ISSUE TITLE
Name gptel buffer to reflect backend

### ISSUE THREAD

**Issue by tvraman** [karthink/gptel#174]
At present the buffer is always called chat-gpt:-)

**Comment by karthink** [comment]
Done, thanks for raising the issue.

**Comment by tvraman** [comment]
Thanks for all the good work and apologies if all this feels like
nitpicking.

I plan to write an emacspeak-gptel module, so I might have more questions.
--

**Comment by karthink** [comment]
> Thanks for all the good work and apologies if all this feels like nitpicking.

No problem, keep them coming!  The interface is lacking polish in many places, pointing them out is helping.
