### ISSUE TITLE
gptel--make-openai with custom endpoint (anyscale) not recognizing model

### ISSUE THREAD

**Issue by LazerJesus** [karthink/gptel#177]
Hey 👋 
ive been playing around with different endpoints and one ive had good results with elsewhere is mixtral. Sadly I dont have the 48gb required to run it locally 🤷 
anyscale offers it as an api and its a drop in replacement for openai's api. in python you can just use the official Python OpenAI library, only replacing the URL and KEY.
ive tried that, any new session now starts with the correct backend but i cant select the model.
what am i doing wrong?

```  
(setq-default
   gptel-backend (gptel--make-openai
                  :name "Anyscale"
                  :host "api.endpoints.anyscale.com"     
                  :endpoint "v1"
                  :key  "xxx"
                  :models '("mistralai/Mixtral-8x7B-Instruct-v0.1")
                  )
   gptel-model "mistralai/Mixtral-8x7B-Instruct-v0.1"
   )
```
<img width="510" alt="Screenshot 2024-01-11 at 13 17 57" src="https://github.com/karthink/gptel/assets/11148454/48d977c6-d7b0-489a-ae18-f1681b2a9431">

**Comment by karthink** [comment]
This may or may not be relevant: it looks like there's a typo in your
configuration, it should be gptel-make-openai, not gptel--make-openai.

**Comment by LazerJesus** [comment]
ok yes that allowed my to chose the provider. funny, i copied that snippet out of some issue.
sadly it didnt work. response cant be parsed.

**Comment by karthink** [comment]
Hang on, I'm pretty sure we can get it to work.  If you are interested: set
the variable gptel--debug to t, then try sending a query. A buffer
containing the response should pop up. You can paste the contents of that
buffer here after removing your API key from it.

**Comment by LazerJesus** [comment]
gptel--debug is t
*Messages
```
Querying Anyscale...
("--location" "--silent" "--compressed" "--disable" "-XPOST" "-w(4267eddb21697a77a895875e606cbe34 . %{size_header})" "-m300" "-D-" "-d{\"model\":\"mistralai/Mixtral-8x7B-Instruct-v0.1\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a large language model living in Emacs and a helpful assistant. Respond concisely.\"},{\"role\":\"user\",\"content\":\"Hello World\"}],\"stream\":false,\"temperature\":1.0}" "-HContent-Type: application/json" "https://api.endpoints.anyscale.comv1")

ChatGPT response error: (((4267eddb21697a77a895875e606cbe34 . 0)) Could not parse HTTP response.) Could not parse HTTP response.
```
*buffer
```
HTTP/2 401 
content-type: application/json
content-length: 37
date: Fri, 12 Jan 2024 19:52:29 GMT
server: uvicorn
x-request-id: 722bc1e9-f158-4905-81dc-6a95ee2cd606
x-cache: Error from cloudfront
via: 1.1 cba85c100a294e3d2360b9852eb535fc.cloudfront.net (CloudFront)
x-amz-cf-pop: WAW51-P4
x-amz-cf-id: _mmN_2idH6t19tE2VGCNJvNsxi7vf0fKm8SLJSujE7hr53T_chI5tQ==

{"err":"Auth token must be provided"}(a7ebb812780a8e7c6c1f78ad4c857c26 . 371)
```

so authtoken is missing.
i am setting :key tho.

**Comment by karthink** [comment]
``` emacs-lisp
(setq-default
   gptel-backend (gptel-make-openai
                  :name "Anyscale"
                  :host "api.endpoints.anyscale.com"     
                  :endpoint "v1"
                  :header (lambda () `(("Authorization" . ,(concat "Bearer " (gptel--get-api-key)))))
                  :key  "xxx"
                  :models '("mistralai/Mixtral-8x7B-Instruct-v0.1"))
   gptel-model "mistralai/Mixtral-8x7B-Instruct-v0.1")
```

**Comment by LazerJesus** [comment]
```
(setq-default
   gptel-backend (gptel-make-openai
	"anyscale"
	:host "api.endpoints.anyscale.com"
	:endpoint "v1"
	:header (lambda () `(("Authorization" . ,(concat "Bearer " (gptel--get-api-key)))))
	:key "x"
	:models '("mistralai/Mixtral-8x7B-Instruct-v0.1"))
   gptel-model "mistralai/Mixtral-8x7B-Instruct-v0.1")
```

1. i have to omit `:word`, otherwise i get this error when evaluating the expression:
`gptel-make-openai: Keyword argument Anyscale not one of (:header :models :stream :key :host :protocol :endpoint)`

2. i still get
```
ChatGPT response error: (((31fc0bff67b7109e9f2b541e2c33c2fe . 0)) Could not parse HTTP response.) Could not parse HTTP response.
```

**Comment by LazerJesus** [comment]
<img width="769" alt="Screenshot 2024-01-19 at 14 48 48" src="https://github.com/karthink/gptel/assets/11148454/55127b14-b7d8-43d1-a977-c3781c5caaa4">
🥳

**Comment by LazerJesus** [comment]
with this gptel becomes even more important to my daily work. i love it!
i got a couple of questions, not sure if here is the best spot, so let me know if i should start a new issue about any of these.

### managing multiple backends
at the moment i toggle models by keybinding custom expressions. like this
```lisp
  (defun set-gpt4-universal ()
    (interactive)
    (setq gptel-model "gpt-4-1106-preview")
    (setq chatgpt-shell-chatgpt-model-version "gpt-4-1106-preview"))

  (defun gptel-with-argument ()
    (interactive)
    (setq current-prefix-arg '(4))
    (call-interactively #'gptel))
```
but with multiple backends that is becoming tedious. is there a better way?


### whats the fastest way to provide one-off directives
i often highlight text regions and want to write just one sentence. 
using the gpt-system buffer (reached via `h h` from the gptel minibuffer) is about 8 key hits for me. 
`open minibuffer, h h, closing minibuffer, clearing text, c-c c-c.`
is there a faster way?


### managing directives / directives per model?
different models have different strengths and weaknesses, therefore i use them for different reasons.
for example, i use gpt4 for coding and mixtral for summarizing large bodies of text.
that requires different directives. is it possible to have directives per model?
how would i do that?
