### ISSUE TITLE
latest gptel throws error on curl completion

### ISSUE THREAD

**Issue by tvraman** [karthink/gptel#178]
Debugger entered--Lisp error: (wrong-type-argument markerp nil)
  (marker-position nil)
  (gptel-curl--stream-cleanup #<process gptel-curl> finishedn)

**Comment by karthink** [comment]
I'm not able to reproduce this.  Does it happen every time?

**Comment by tvraman** [comment]
seems sporadic.

Also seeing some strange behavior around gptel-post-response-function --
likely due to defalias wierdness?

Symptoms: doing add-hook appeared to bomb but setting via custom works.

Thanks for that hook by the way I used it to make emacspeak speak the
response automatically
--

**Comment by karthink** [comment]
`gptel-post-response-hook` is obsolete, I changed it to `gptel-post-response-functions` which has different behavior -- functions in this hook receive the beginning and end positions of the response as arguments.  If you were using `gptel-post-response-hook`, please update and modify your hook functions appropriately.

**Comment by tvraman** [comment]
done. Actually I had done it but there was a version that was
bytecompiled  somewhere in my env and it required a lot of chasing. 
--

**Comment by tvraman** [comment]
appears to  not happen any more
