### ISSUE TITLE
Restoring Ollama state correctly

### ISSUE THREAD

**Issue by karthink** [karthink/gptel#181]
The state of Ollama chats cannot be restored accurately since we are not (presently) storing the chat embedding vector the API returns.  Storing this is simple, but this vector tends to be large, and will cause two issues with Emacs:

1. The buffer size will increase by a factor of 2 when saved to disk.
2. It will be stored as a string on a single logical line, and will trigger Emacs' long lines issues.

The option of storing it separately in a data file (ASCII or binary) is off the table: one gptel's objectives is to produce self-contained, single file chats that are portable and reproducible modulo pinning the Emacs+gptel version.  (And we try very hard to stay backward compatible so the pinning isn't necessary.)

**Comment by luyangliuable** [comment]
Is this why we get the `Ollama error (nil): Malformed JSON in response.` error whenever we receive a response from ollama?

**Comment by karthink** [comment]
> Is this why we get the `Ollama error (nil): Malformed JSON in response.` error whenever we receive a response from ollama?

No, there's no connection between this and the error.

The error sounds like a bug.  Is Ollama not working for you at all, or does it not work when you restore a chat from a file on disk?

**Comment by luyangliuable** [comment]
I get the the error when I run `gptel-send` with the following configurations. It also takes 10 minutes before the response arrives.

```
(setq-default gptel-model "mistral:latest" ;Pick your default model
                   gptel-backend (gptel-make-ollama "Ollama"
                                   :host "localhost:11434"
                                   :stream t
                                   :models '("mistral")))
```

* gptel-curl:
```

```

* gptel-log:
```
{
  "gptel": "request body",
  "timestamp": "2024-02-11 11:13:45"
}
  {
  "model": "mistral",
  "system": "You are a large language model living in Emacs and a helpful assistant. Respond concisely.",
  "prompt": "Test",
  "stream": true
}

```

ollama server is also active and `ollama run mistral` works normally.
<img width="1147" alt="image" src="https://github.com/karthink/gptel/assets/23611033/5f992ddb-29ae-49f9-8178-197fabdc67f7">

**Comment by karthink** [comment]
This was fixed recently, please update gptel.
