### ISSUE TITLE
Send from transient window fails on Doom Emacs with org-mode

### ISSUE THREAD

**Issue by edmundmiller** [karthink/gptel#182]
I'm getting

```console
Unbound suffix: ‘<return>’ (Use ‘C-g’ to abort, ‘?’ for help) [+org/dwim-at-point]
```

Whenever using `gptel-menu` and hitting "enter".

It seems to work from other modes such as markdown and elisp. I think it's this line https://github.com/karthink/gptel/blob/b432b2f3e7ec072f0df6655adda627696abffa7a/gptel-transient.el and these https://github.com/doomemacs/doomemacs/blob/03d692f129633e3bf0bd100d91b3ebf3f77db6d1/modules/lang/org/config.el#L1258-L1259 clashing.

I wish I knew how to set it to either or in the transient suffix map.

**Comment by karthink** [comment]
Two solutions:

1. Press `C-m` instead of `RET` (see #75)
2. Replace the send key with a key of your choice:
```elisp
(transient-suffix-put 'gptel-menu (kbd "RET") :key "<f8>")
```

**Comment by edmundmiller** [comment]
Awesome, I couldn't find the first issue, sorry for any duplication!

The second solution also works great, thank you so much!
