### ISSUE TITLE
gptel-send in org-mode - wrong number of arguments

### ISSUE THREAD

**Issue by lalon** [karthink/gptel#183]
I am experiencing an issue with gptel-send in org-mode. Whenever I try to use gptel-send, I encounter the following error message: "let: Wrong number of arguments: setq, 1". This issue occurs consistently and prevents me from utilizing gptel-send in org-mode.

Please let me know if any additional information is required to investigate and resolve this issue. Thank you.

**Comment by karthink** [comment]
1. Does `gptel-send` work fine in non Org mode buffers?
2. Please run `M-x toggle-debug-on-error` and paste the stacktrace here.
3. Paste your gptel configuration here.

**Comment by karthink** [comment]
Hmm, this is strange.  The backtrace does not correspond to the actual code!  I wonder if Emacs 27 expands `letrec` differently.

I pushed a tentative fix, please update.

**Comment by lalon** [comment]
Yep that fixed it, thank you!
