### ISSUE TITLE
request : define output buffer

### ISSUE THREAD

**Issue by rileyrg** [karthink/gptel#192]
Is there a way, or could there be, to define where the output of gptel-send is sent? Ideally If I have a *Chat GPT* buffer open then if I select and gptel-send from, say, my code buffer then the reply doesnt get inserted in my code, rather into *Chat GPT*.

**Comment by karthink** [comment]
`C-u M-x gptel-send`, or `C-u C-c RET`:

![image](https://github.com/karthink/gptel/assets/8607532/86ac4d3f-5d75-4ead-9390-ea706cf88cb6)

Is this what you're looking for?

**Comment by rileyrg** [comment]
That only works once from what I can see.

Ideally i set it to use "existing session" and then all queries for into
that session. Unless I'm doing something wrong, I need to C-u gptel-send
"e" every time.

-- 
https://github.com/rileyrg?tab=repositories

**Comment by karthink** [comment]
> That only works once from what I can see.

You can press `C-x C-s` in the transient menu to save the options. All subsequent queries from the transient menu will respect this option.

If you don't want to open the transient menu each time, you can use a keyboard macro (see #189) or define a custom send command (see #94).

**Comment by rileyrg** [comment]
Many thanks!

**Comment by karthink** [comment]
Also added a note on this question to the [FAQ](https://github.com/karthink/gptel#i-want-the-transient-menu-options-to-be-saved-so-i-only-need-to-set-them-once).
