### ISSUE TITLE
formatting issue in org blocks (Mixtral models)

### ISSUE THREAD

**Issue by akhil3417** [karthink/gptel#200]
renamed the org file to .md since github doesn't support it  [potential_bug.md](https://github.com/karthink/gptel/files/14112780/bug.md)
`#+begin\_src assembly`

related to 10f5760

**Comment by karthink** [comment]
> renamed the org file to .md since github doesn't support it  [bug.md](https://github.com/karthink/gptel/files/14112780/bug.md)
> `#+begin\_src assembly`

Is this with or without streaming responses?

**Comment by akhil3417** [comment]
> Is this with or without streaming responses?
with streaming responses , also the first source block is always correct.

**Comment by akhil3417** [comment]
+ another day of LLMs trying to do things other than what is asked (see ss below)
+ also thanks for the awesome package , gptel works seamlessly in eMacs-android as well.

+ Screenshot:
![Screenshot_20240201-084346_Emacs](https://github.com/karthink/gptel/assets/92385307/7ee37214-a8bb-451c-b949-b8aa25ea146f)
