### ISSUE TITLE
error in process sentinel: Symbol’s value as variable is void: gptel--debug

### ISSUE THREAD

**Issue by trekta** [karthink/gptel#205]
Hey, I am using the latest release and did not change my configuration.
Using gptel-send I get this error and no response:
`error in process sentinel: Symbol’s value as variable is void: gptel--debug`
with `debug-on-error t` I get this backtrace:
```
Debugger entered--Lisp error: (void-variable gptel--debug)
  gptel-curl--sentinel(#<process gptel-curl> "finished\n")
```
funny enough, after I eval `gptel--debug t` everything works as expected and the gtpel-error buffer shows ordinary looking curl response.

Thanks for all the hard work you put into this package and sorry if this turns out to some stupid error on my side

**Comment by karthink** [comment]
Some left over stuff from a recent refactoring. Should be fixed, sorry for the trouble.
