### ISSUE TITLE
Wrong type argument: markerp, nil

### ISSUE THREAD

**Issue by fpGHwd** [karthink/gptel#208]
When I use gptel and mark some contents to ask GPT, it produces error message: 

> Querying ChatGPT...
error in process sentinel: setq: Wrong type argument: markerp, nil
error in process sentinel: Wrong type argument: markerp, nil
Querying ChatGPT...
error in process sentinel: setq: Wrong type argument: markerp, nil
error in process sentinel: Wrong type argument: markerp, nil

 
And then I toggle debug on error,  the error stack shows:
```Debugger entered--Lisp error: (wrong-type-argument markerp nil)
  marker-position(nil)
  (setq response-end (marker-position tracking-marker))
  (progn (setq response-beg (+ start-marker 2)) (setq response-end (marker-position tracking-marker)))
  (save-current-buffer (set-buffer (marker-buffer start-marker)) (progn (setq response-beg (+ start-marker 2)) (setq response-end (marker-position tracking-marker))) (pulse-momentary-highlight-region response-beg tracking-marker) (if gptel-mode (progn (save-excursion (goto-char tracking-marker) (insert "\n\n" (gptel-prompt-prefix-string))))))
  (progn (save-current-buffer (set-buffer (marker-buffer start-marker)) (progn (setq response-beg (+ start-marker 2)) (setq response-end (marker-position tracking-marker))) (pulse-momentary-highlight-region response-beg tracking-marker) (if gptel-mode (progn (save-excursion (goto-char tracking-marker) (insert "\n\n" (gptel-prompt-prefix-string)))))) (save-current-buffer (set-buffer gptel-buffer) (if gptel-mode (progn (gptel--update-status " Ready" 'success)))))
  (if (equal http-status "200") (progn (save-current-buffer (set-buffer (marker-buffer start-marker)) (progn (setq response-beg (+ start-marker 2)) (setq response-end (marker-position tracking-marker))) (pulse-momentary-highlight-region response-beg tracking-marker) (if gptel-mode (progn (save-excursion (goto-char tracking-marker) (insert "\n\n" (gptel-prompt-prefix-string)))))) (save-current-buffer (set-buffer gptel-buffer) (if gptel-mode (progn (gptel--update-status " Ready" 'success))))) (save-current-buffer (set-buffer proc-buf) (goto-char (point-max)) (search-backward (plist-get info :token)) (backward-char) (let* ((val (read (current-buffer)))) (progn (ignore (consp val)) (let* ((x914 (cdr-safe val))) (let ((header-size x914)) (let* (... ... ...) (cond ... ... ...))))))) (save-current-buffer (set-buffer gptel-buffer) (if gptel-mode (progn (gptel--update-status (format " Response Error: %s" http-msg) 'error)))))
  (let* ((info (alist-get process gptel-curl--process-alist)) (gptel-buffer (plist-get info :buffer)) (backend-name (let ((cl-x (buffer-local-value 'gptel-backend gptel-buffer))) (progn (or (progn (and ... t)) (signal 'wrong-type-argument (list ... cl-x))) (aref cl-x 1)))) (tracking-marker (plist-get info :tracking-marker)) (start-marker (plist-get info :position)) (http-status (plist-get info :http-status)) (http-msg (plist-get info :status)) response-beg response-end) (if gptel-log-level (progn (gptel-curl--log-response proc-buf info))) (if (equal http-status "200") (progn (save-current-buffer (set-buffer (marker-buffer start-marker)) (progn (setq response-beg (+ start-marker 2)) (setq response-end (marker-position tracking-marker))) (pulse-momentary-highlight-region response-beg tracking-marker) (if gptel-mode (progn (save-excursion (goto-char tracking-marker) (insert "\n\n" ...))))) (save-current-buffer (set-buffer gptel-buffer) (if gptel-mode (progn (gptel--update-status " Ready" 'success))))) (save-current-buffer (set-buffer proc-buf) (goto-char (point-max)) (search-backward (plist-get info :token)) (backward-char) (let* ((val (read (current-buffer)))) (progn (ignore (consp val)) (let* ((x914 ...)) (let (...) (let* ... ...)))))) (save-current-buffer (set-buffer gptel-buffer) (if gptel-mode (progn (gptel--update-status (format " Response Error: %s" http-msg) 'error))))) (save-current-buffer (set-buffer gptel-buffer) (run-hook-with-args 'gptel-post-response-functions response-beg response-end)))
  (let ((proc-buf (process-buffer process))) (let* ((info (alist-get process gptel-curl--process-alist)) (gptel-buffer (plist-get info :buffer)) (backend-name (let ((cl-x (buffer-local-value ... gptel-buffer))) (progn (or (progn ...) (signal ... ...)) (aref cl-x 1)))) (tracking-marker (plist-get info :tracking-marker)) (start-marker (plist-get info :position)) (http-status (plist-get info :http-status)) (http-msg (plist-get info :status)) response-beg response-end) (if gptel-log-level (progn (gptel-curl--log-response proc-buf info))) (if (equal http-status "200") (progn (save-current-buffer (set-buffer (marker-buffer start-marker)) (progn (setq response-beg (+ start-marker 2)) (setq response-end (marker-position tracking-marker))) (pulse-momentary-highlight-region response-beg tracking-marker) (if gptel-mode (progn (save-excursion ... ...)))) (save-current-buffer (set-buffer gptel-buffer) (if gptel-mode (progn (gptel--update-status " Ready" ...))))) (save-current-buffer (set-buffer proc-buf) (goto-char (point-max)) (search-backward (plist-get info :token)) (backward-char) (let* ((val (read ...))) (progn (ignore (consp val)) (let* (...) (let ... ...))))) (save-current-buffer (set-buffer gptel-buffer) (if gptel-mode (progn (gptel--update-status (format " Response Error: %s" http-msg) 'error))))) (save-current-buffer (set-buffer gptel-buffer) (run-hook-with-args 'gptel-post-response-functions response-beg response-end))) (let* ((p (if (and nil (not (eq nil ...))) (assoc process gptel-curl--process-alist nil) (assq process gptel-curl--process-alist)))) (progn (if p (setq gptel-curl--process-alist (delq p gptel-curl--process-alist))) nil)) (kill-buffer proc-buf))
  gptel-curl--stream-cleanup(#<process gptel-curl> "exited abnormally with code 35\n")
```

**Comment by fpGHwd** [comment]
![Screenshot-2](https://github.com/karthink/gptel/assets/11605000/a3dd1526-4e18-4ea4-a233-16c53f8600f0)

**Comment by karthink** [comment]
Thanks for the report. It looks like the curl process is failing with an SSL error.

1. Does this happen every time?
2. Does this happen only when you select a region?
3. What curl version is this? `curl --version` in the shell.
4. What Emacs version is this?
5. Could you produce a log? Here's how to do it:

- Turn on logging with `(setq gptel-log-level 'debug)`
- Try to use gptel, produce the above error
- Open the `*gptel-log*` buffer and remove your API key (if any) from its contents
- Paste the contents of the buffer here.

**Comment by cashpw** [comment]
I'm also seeing this error after running `gptel-send` for Gemini (`gemini-pro`).

## Steps to reproduce:

1. My config

    ```elisp
    (use-package! gptel
      :config
      (setq
       gptel-default-mode 'org-mode)
      (setq-default
       gptel-model "gemini-pro"
       gptel-backend (gptel-make-gemini "Gemini"
                       :key (cashpw/get-secret "personal-gemini")
                       :models '("gemini-pro")
                       :stream t)))
2. Open a scratch buffer (`SPC x`) and type "What's 2+2?"
3. `M-x gptel-send`
4. See `(wrong-type-argument markerp nil)` in minibuffer

## Debug info

<details>
<summary>Debugger output</summary>

```elisp

Debugger entered--Lisp error: (wrong-type-argument markerp nil)
  marker-position(nil)
  (setq response-end (marker-position tracking-marker))
  (progn (setq response-beg (+ start-marker 2)) (setq response-end (marker-position tracking-marker)))
  (save-current-buffer (set-buffer (marker-buffer start-marker)) (progn (setq response-beg (+ start-marker 2)) (setq response-end (marker-position tracking-marker))) (pulse-momentary-highlight-region response-beg tracking-marker) (if gptel-mode (progn (save-excursion (goto-char tracking-marker) (insert "\n\n" (gptel-prompt-prefix-string))))))
  (progn (save-current-buffer (set-buffer (marker-buffer start-marker)) (progn (setq response-beg (+ start-marker 2)) (setq response-end (marker-position tracking-marker))) (pulse-momentary-highlight-region response-beg tracking-marker) (if gptel-mode (progn (save-excursion (goto-char tracking-marker) (insert "\n\n" (gptel-prompt-prefix-string)))))) (save-current-buffer (set-buffer gptel-buffer) (if gptel-mode (progn (gptel--update-status " Ready" 'success)))))
  (if (equal http-status "200") (progn (save-current-buffer (set-buffer (marker-buffer start-marker)) (progn (setq response-beg (+ start-marker 2)) (setq response-end (marker-position tracking-marker))) (pulse-momentary-highlight-region response-beg tracking-marker) (if gptel-mode (progn (save-excursion (goto-char tracking-marker) (insert "\n\n" (gptel-prompt-prefix-string)))))) (save-current-buffer (set-buffer gptel-buffer) (if gptel-mode (progn (gptel--update-status " Ready" 'success))))) (save-current-buffer (set-buffer proc-buf) (goto-char (point-max)) (search-backward (plist-get info :token)) (backward-char) (let* ((val (read (current-buffer)))) (progn (ignore (consp val)) (let* ((x421 (cdr-safe val))) (let ((header-size x421)) (let* (... ... ...) (cond ... ... ...))))))) (save-current-buffer (set-buffer gptel-buffer) (if gptel-mode (progn (gptel--update-status (format " Response Error: %s" http-msg) 'error)))))
  (let* ((info (alist-get process gptel-curl--process-alist)) (gptel-buffer (plist-get info :buffer)) (backend-name (let ((cl-x (buffer-local-value 'gptel-backend gptel-buffer))) (progn (or (progn (and ... t)) (signal 'wrong-type-argument (list ... cl-x))) (aref cl-x 1)))) (tracking-marker (plist-get info :tracking-marker)) (start-marker (plist-get info :position)) (http-status (plist-get info :http-status)) (http-msg (plist-get info :status)) response-beg response-end) (if gptel-log-level (progn (gptel-curl--log-response proc-buf info))) (if (equal http-status "200") (progn (save-current-buffer (set-buffer (marker-buffer start-marker)) (progn (setq response-beg (+ start-marker 2)) (setq response-end (marker-position tracking-marker))) (pulse-momentary-highlight-region response-beg tracking-marker) (if gptel-mode (progn (save-excursion (goto-char tracking-marker) (insert "\n\n" ...))))) (save-current-buffer (set-buffer gptel-buffer) (if gptel-mode (progn (gptel--update-status " Ready" 'success))))) (save-current-buffer (set-buffer proc-buf) (goto-char (point-max)) (search-backward (plist-get info :token)) (backward-char) (let* ((val (read (current-buffer)))) (progn (ignore (consp val)) (let* ((x421 ...)) (let (...) (let* ... ...)))))) (save-current-buffer (set-buffer gptel-buffer) (if gptel-mode (progn (gptel--update-status (format " Response Error: %s" http-msg) 'error))))) (save-current-buffer (set-buffer gptel-buffer) (run-hook-with-args 'gptel-post-response-functions response-beg response-end)))
  (let ((proc-buf (process-buffer process))) (let* ((info (alist-get process gptel-curl--process-alist)) (gptel-buffer (plist-get info :buffer)) (backend-name (let ((cl-x (buffer-local-value ... gptel-buffer))) (progn (or (progn ...) (signal ... ...)) (aref cl-x 1)))) (tracking-marker (plist-get info :tracking-marker)) (start-marker (plist-get info :position)) (http-status (plist-get info :http-status)) (http-msg (plist-get info :status)) response-beg response-end) (if gptel-log-level (progn (gptel-curl--log-response proc-buf info))) (if (equal http-status "200") (progn (save-current-buffer (set-buffer (marker-buffer start-marker)) (progn (setq response-beg (+ start-marker 2)) (setq response-end (marker-position tracking-marker))) (pulse-momentary-highlight-region response-beg tracking-marker) (if gptel-mode (progn (save-excursion ... ...)))) (save-current-buffer (set-buffer gptel-buffer) (if gptel-mode (progn (gptel--update-status " Ready" ...))))) (save-current-buffer (set-buffer proc-buf) (goto-char (point-max)) (search-backward (plist-get info :token)) (backward-char) (let* ((val (read ...))) (progn (ignore (consp val)) (let* (...) (let ... ...))))) (save-current-buffer (set-buffer gptel-buffer) (if gptel-mode (progn (gptel--update-status (format " Response Error: %s" http-msg) 'error))))) (save-current-buffer (set-buffer gptel-buffer) (run-hook-with-args 'gptel-post-response-functions response-beg response-end))) (let* ((p (if (and nil (not (eq nil ...))) (assoc process gptel-curl--process-alist nil) (assq process gptel-curl--process-alist)))) (progn (if p (setq gptel-curl--process-alist (delq p gptel-curl--process-alist))) nil)) (kill-buffer proc-buf))
  gptel-curl--stream-cleanup(#<process gptel-curl> "finished\n")

```
</details>

<details>
<summary><code>*gptel-log*</code></summary>

```
{
  "gptel": "request headers",
  "timestamp": "2024-02-07 16:57:02"
}
{
  "Content-Type": "application/json"
}
{
  "gptel": "request body",
  "timestamp": "2024-02-07 16:57:02"
}
{
  "contents": [
    {
      "role": "user",
      "parts": {
        "text": "You are a large language model living in Emacs and a helpful assistant. Respond concisely.\n\nWhat's 2+2?"
      }
    }
  ],
  "generationConfig": {
    "temperature": 1.0
  }
}
{
  "gptel": "request Curl command",
  "timestamp": "2024-02-07 16:57:02"
}
[
  "curl",
  "--disable",
  "--location",
  "--silent",
  "--compressed",
  "-XPOST",
  "-y300",
  "-Y1",
  "-D-",
  "-w(86f2883e17467c81f3ee5c1e90f6aa94 . %{size_header})",
  "-d{\"contents\":[{\"role\":\"user\",\"parts\":{\"text\":\"You are a large language model living in Emacs and a helpful assistant. Respond concisely.\\n\\nWhat's 2+2?\"}}],\"generationConfig\":{\"temperature\":1.0}}",
  "-HContent-Type: application/json",
  "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:streamGenerateContent?key=<omitted>"
]
{
  "gptel": "response headers",
  "timestamp": "2024-02-07 16:57:03"
}
"HTTP/2 200 \r\ncontent-type: application/json; charset=UTF-8\r\nvary: Origin\r\nvary: X-Origin\r\nvary: Referer\r\ncontent-encoding: gzip\r\ndate: Thu, 08 Feb 2024 00:57:03 GMT\r\nserver: scaffolding on HTTPServer2\r\ncache-control: private\r\nx-xss-protection: 0\r\nx-frame-options: SAMEORIGIN\r\nx-content-type-options: nosniff\r\nserver-timing: gfet4t7; dur=772\r\nalt-svc: h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000\r\n\r"
{
  "gptel": "response body",
  "timestamp": "2024-02-07 16:57:03"
}
[
  {
    "candidates": [
      {
        "finishReason": "SAFETY",
        "index": 0,
        "safetyRatings": [
          {
            "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
            "probability": "NEGLIGIBLE"
          },
          {
            "category": "HARM_CATEGORY_HATE_SPEECH",
            "probability": "LOW"
          },
          {
            "category": "HARM_CATEGORY_HARASSMENT",
            "probability": "MEDIUM"
          },
          {
            "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
            "probability": "NEGLIGIBLE"
          }
        ]
      }
    ],
    "promptFeedback": {
      "safetyRatings": [
        {
          "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_HATE_SPEECH",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_HARASSMENT",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
          "probability": "NEGLIGIBLE"
        }
      ]
    }
  }
]
```
</details>

I also tested a few prompts with curl directly; example:

```sh
curl \
  -H 'Content-Type: application/json' \
  -d '{"contents":[{"parts":[{"text":"What is 2+2?"}]}]}' \
  -X POST https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=YOUR_API_KEY
```

## Root cause

**The log indicates the output stopped due to `SAFETY`**  (a response with content has a `finishReason: STOP`).

~The issue is the directive~ I _thought_ the issue was the directive. However, omitting it (i.e. `What is 2+2?` rather than `You are a large language model living in Emacs and a helpful assistant. Respond concisely.\n\nWhat is 2+2?`) **also**  gets a `"finishReason": "SAFETY"`. Omitting the "2+2" (e.g. `What is a cat?`) gets a good response.

I am baffled that `What is 2+2?` is considered unsafe?

## Suggestion(s)

We should check the curl response for the presence of the top-level `"content"` key and fail gracefully by checking the `"finishReason"` if it's missing.

**Comment by karthink** [comment]
@cashpw Thank you for the detailed analysis, this is very helpful.  I've pushed a commit that makes the API less likely to block harmless questions ("What's 2+2" should work now), but I'll keep in mind the need to check the `finishReason` explicitly so it can fail gracefully -- will work on it soon.

In any case, @fpGHwd's issue is unrelated to this, they are having issues because Curl is failing to negotiate the SSL handshake.

**Comment by fpGHwd** [comment]
> 5\. Could you produce a log? Here's how to do it:

Thanks for replying. 
-----
> 1. Does this happen every time?
2. Does this happen only when you select a region?
3. What curl version is this? curl --version in the shell.
4. What Emacs version is this?
5. Could you produce a log? Here's how to do it:
-----
1. Yes everytime I mark content and `M-x gpgel-send`;
2. this error happens not only when I select a region, but also use `M-x gptel` and input what I want to ask, then press `C-c RET`;
3. current curl version what I use:  

> wd@ubuntu2204:~$ curl --version
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

4. emacs version(built from source code):

> wd@ubuntu2204:~$ emacs --version
GNU Emacs 29.2.50
Development version b91f0ee2fcc5 on emacs-29 branch; build date 2024-02-04.
Copyright (C) 2024 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

5. `(setq gptel-log-level 'debug)` and logging when use gptel and get buffer `*gptel-log*` content, as following:

> {
  "gptel": "request headers",
  "timestamp": "2024-02-08 13:34:08"
}
{
  "Content-Type": "application/json",
  "Authorization": "Bearer sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
{
  "gptel": "request body",
  "timestamp": "2024-02-08 13:34:08"
}
{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "system",
      "content": "You are a large language model living in Emacs and a helpful assistant. Respond concisely."
    },
    {
      "role": "user",
      "content": "radmoon use bridge NIC to debug with program with symbols"
    }
  ],
  "stream": true,
  "temperature": 1.0
}
{
  "gptel": "request Curl command",
  "timestamp": "2024-02-08 13:34:08"
}
[
  "curl",
  "--disable",
  "--location",
  "--silent",
  "--compressed",
  "-XPOST",
  "-y300",
  "-Y1",
  "-D-",
  "-w(2d370ad358517c6b7542b01dc2832089 . %{size_header})",
  "-d{\"model\":\"gpt-3.5-turbo\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a large language model living in Emacs and a helpful assistant. Respond concisely.\"},{\"role\":\"user\",\"content\":\"radmoon use bridge NIC to debug with program with symbols\"}],\"stream\":true,\"temperature\":1.0}",
  "--proxy",
  "localhost:7890",
  "--proxy-negotiate",
  "--proxy-user",
  ":",
  "-HContent-Type: application/json",
  "-HAuthorization: Bearer sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "https://api.openai.com/v1/chat/completions"
]
{
  "gptel": "response headers",
  "timestamp": "2024-02-08 13:34:09"
}
"HTTP/1.1 200 Connection established\r\n\r"
{
  "gptel": "response body",
  "timestamp": "2024-02-08 13:34:09"
}

{
  "gptel": "request headers",
  "timestamp": "2024-02-08 13:35:23"
}
{
  "Content-Type": "application/json",
  "Authorization": "Bearer sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
{
  "gptel": "request body",
  "timestamp": "2024-02-08 13:35:23"
}
{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "system",
      "content": "You are a large language model living in Emacs and a helpful assistant. Respond concisely."
    },
    {
      "role": "user",
      "content": "PC vm ubuntu cannot ping 192.168.10.99"
    }
  ],
  "stream": true,
  "temperature": 1.0
}
{
  "gptel": "request Curl command",
  "timestamp": "2024-02-08 13:35:23"
}
[
  "curl",
  "--disable",
  "--location",
  "--silent",
  "--compressed",
  "-XPOST",
  "-y300",
  "-Y1",
  "-D-",
  "-w(0f13aa6fbbb9b820f326d74a55b8037a . %{size_header})",
  "-d{\"model\":\"gpt-3.5-turbo\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a large language model living in Emacs and a helpful assistant. Respond concisely.\"},{\"role\":\"user\",\"content\":\"PC vm ubuntu cannot ping 192.168.10.99\"}],\"stream\":true,\"temperature\":1.0}",
  "--proxy",
  "localhost:7890",
  "--proxy-negotiate",
  "--proxy-user",
  ":",
  "-HContent-Type: application/json",
  "-HAuthorization: Bearer sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "https://api.openai.com/v1/chat/completions"
]
{
  "gptel": "response headers",
  "timestamp": "2024-02-08 13:35:24"
}
"HTTP/1.1 200 Connection established\r\n\r"
{
  "gptel": "response body",
  "timestamp": "2024-02-08 13:35:24"
}

{
  "gptel": "request headers",
  "timestamp": "2024-02-08 13:35:31"
}
{
  "Content-Type": "application/json",
  "Authorization": "Bearer sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
{
  "gptel": "request body",
  "timestamp": "2024-02-08 13:35:31"
}
{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "system",
      "content": "You are a large language model living in Emacs and a helpful assistant. Respond concisely."
    },
    {
      "role": "user",
      "content": "\\346\\263\\250\\346\\204\\217 adb shell \\347\\246\\201\\346\\255\\242\\345\\257\\206\\347\\240\\201\\347\\232\\204\\346\\226\\271\\346\\241\\210"
    }
  ],
  "stream": true,
  "temperature": 1.0
}
{
  "gptel": "request Curl command",
  "timestamp": "2024-02-08 13:35:31"
}
[
  "curl",
  "--disable",
  "--location",
  "--silent",
  "--compressed",
  "-XPOST",
  "-y300",
  "-Y1",
  "-D-",
  "-w(bca81047a72b9d944a97351dd19029f7 . %{size_header})",
  "-d{\"model\":\"gpt-3.5-turbo\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a large language model living in Emacs and a helpful assistant. Respond concisely.\"},{\"role\":\"user\",\"content\":\"\\346\\263\\250\\346\\204\\217 adb shell \\347\\246\\201\\346\\255\\242\\345\\257\\206\\347\\240\\201\\347\\232\\204\\346\\226\\271\\346\\241\\210\"}],\"stream\":true,\"temperature\":1.0}",
  "--proxy",
  "localhost:7890",
  "--proxy-negotiate",
  "--proxy-user",
  ":",
  "-HContent-Type: application/json",
  "-HAuthorization: Bearer sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "https://api.openai.com/v1/chat/completions"
]
{
  "gptel": "response headers",
  "timestamp": "2024-02-08 13:35:31"
}
"HTTP/1.1 200 Connection established\r\n\r"
{
  "gptel": "response body",
  "timestamp": "2024-02-08 13:35:31"
}

{
  "gptel": "request headers",
  "timestamp": "2024-02-08 13:36:05"
}
{
  "Content-Type": "application/json",
  "Authorization": "Bearer sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
{
  "gptel": "request body",
  "timestamp": "2024-02-08 13:36:05"
}
{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "system",
      "content": "You are a large language model living in Emacs and a helpful assistant. Respond concisely."
    },
    {
      "role": "user",
      "content": "what is the parameter of the earth?"
    },
    {
      "role": "assistant",
      "content": "The parameter of the Earth refers to its circumference, which is approximately 40,075 kilometers (24,901 miles)."
    },
    {
      "role": "user",
      "content": "what's the best time of learning knowledge?"
    },
    {
      "role": "assistant",
      "content": "The best time for learning knowledge can vary depending on individual preferences and circumstances. However, many people find it helpful to allocate dedicated time when they are well-rested, focused, and free from distractions. Experimenting with different times throughout the day can help identify the most effective learning time for you. Ultimately, consistency and a genuine interest in the subject matter are key factors in successful learning."
    },
    {
      "role": "user",
      "content": "what'a a thought experiment?"
    }
  ],
  "stream": true,
  "temperature": 1.0
}
{
  "gptel": "request Curl command",
  "timestamp": "2024-02-08 13:36:05"
}
[
  "curl",
  "--disable",
  "--location",
  "--silent",
  "--compressed",
  "-XPOST",
  "-y300",
  "-Y1",
  "-D-",
  "-w(16981708ac3b30262eee8c7bda151743 . %{size_header})",
  "-d{\"model\":\"gpt-3.5-turbo\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a large language model living in Emacs and a helpful assistant. Respond concisely.\"},{\"role\":\"user\",\"content\":\"what is the parameter of the earth?\"},{\"role\":\"assistant\",\"content\":\"The parameter of the Earth refers to its circumference, which is approximately 40,075 kilometers (24,901 miles).\"},{\"role\":\"user\",\"content\":\"what's the best time of learning knowledge?\"},{\"role\":\"assistant\",\"content\":\"The best time for learning knowledge can vary depending on individual preferences and circumstances. However, many people find it helpful to allocate dedicated time when they are well-rested, focused, and free from distractions. Experimenting with different times throughout the day can help identify the most effective learning time for you. Ultimately, consistency and a genuine interest in the subject matter are key factors in successful learning.\"},{\"role\":\"user\",\"content\":\"what'a a thought experiment?\"}],\"stream\":true,\"temperature\":1.0}",
  "--proxy",
  "localhost:7890",
  "--proxy-negotiate",
  "--proxy-user",
  ":",
  "-HContent-Type: application/json",
  "-HAuthorization: Bearer sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "https://api.openai.com/v1/chat/completions"
]
{
  "gptel": "response headers",
  "timestamp": "2024-02-08 13:36:06"
}
"HTTP/1.1 200 Connection established\r\n\r"
{
  "gptel": "response body",
  "timestamp": "2024-02-08 13:36:06"
}

**Comment by karthink** [comment]
There's no response from ChatGPT.  I'm guessing this has something to do with your proxy configuration:

```json
[
  "curl",
  "--disable",
  "--location",
  "--silent",
  "--compressed",
  "-XPOST",
  "-y300",
  "-Y1",
  "-D-",
  "-w(2d370ad358517c6b7542b01dc2832089 . %{size_header})",
  "-d{\"model\":\"gpt-3.5-turbo\",\"messages\":[{\"role\":\"system\",\"content\":\"You are a large language model living in Emacs and a helpful assistant. Respond concisely.\"},{\"role\":\"user\",\"content\":\"radmoon use bridge NIC to debug with program with symbols\"}],\"stream\":true,\"temperature\":1.0}",
  "--proxy",
  "localhost:7890",
  "--proxy-negotiate",
  "--proxy-user",
  ":",
  "-HContent-Type: application/json",
  "-HAuthorization: Bearer sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "https://api.openai.com/v1/chat/completions"
]
```

What is your proxy setup, and what configuration are you using in gptel to use a proxy?

**Comment by fpGHwd** [comment]
@karthink  Yeah, I try to restart my proxy program clash, then it works. 

It should be an issue with my proxy. I use Clash as my proxy, and it's configured with a proxy group that automatically switches between nodes. Sometimes it switches to nodes that cannot access the ChatGPT API, which causes most of the issues when accessing the OpenAI API. I will check my proxy configuration.

Thank you!

**Comment by fpGHwd** [comment]
OK, thanks.
