### ISSUE TITLE
gptel-prompt-string should be "* " if gptel uses org-mode

### ISSUE THREAD

**Issue by wo** [karthink/gptel#21]
I've set `(setq gptel-default-mode 'org-mode)`. Prompts are in org-mode, but they still begin with '### ', which indicates a markdown heading. It would be better if they began with '* ' or '** ' etc., so that I can collapse and navigate the prompts with the standard org-mode commands.

(Admittedly, this is easy to fix manually with  `(setq gptel-prompt-string "* ")`.)

**Comment by karthink** [comment]
Thanks, I'll fix it soon.

By the way, the prompt prefix is currently just for the user to distinguish between prompts and responses -- it's not required for the package to work.

**Comment by karthink** [comment]
Fixed in 5ebaf361.  You can remove the manual fix from your configuration.  (Also check out `M-x customize-variable gptel-prompt-prefix-alist`.)
