### ISSUE TITLE
Custom backend without setting global default

### ISSUE THREAD

**Issue by vlad-isan** [karthink/gptel#214]
Hi there and many thanks for this amazing package!

Is there a way to set bindings to open gptel with different specific backends / models selected, without setting the backend as a global default?

It works when I set the backend / model with `setq-default`, but I couldn't make it work per invocation.

Is there a way?

**Comment by karthink** [comment]
Have you tried using the transient menu to set the backend/model? (`C-u M-x gptel-send`)

**Comment by vlad-isan** [comment]
It works if I use the transient menu, was just wondering if it was possible to preset the backend and model on a keybinding, and open gptel with a specific backend & model, without using the transient menu.

This would server as a shortcut to have predefined keybindings for different backends / models, one fot gpt4-turbo, one for ppx online, without message history for example.

**Comment by karthink** [comment]
> It works if I use the transient menu, was just wondering if it was possible to preset the backend and model on a keybinding, and open gptel with a specific backend & model, without using the transient menu.

When you set the model/backend in the transient menu, it's persistent in that buffer.  Do you often need to switch backends within a single buffer?

> This would serve as a shortcut to have predefined keybindings for different backends / models, one for gpt4-turbo, one for ppx online, without past messages / context for example.

Yes, with some elisp. See #189.

**Comment by vlad-isan** [comment]
That was helpful, thank you.
Thanks for the quick replies
