### ISSUE TITLE
Default model not respected

### ISSUE THREAD

**Issue by md-zengo** [karthink/gptel#215]
Hi,
I added 
`(setq-default gptel-model "gpt-4-0125-preview")` to my configuration, but default still reverts to GPT 3.5 - what am I doing wrong?

**Comment by karthink** [comment]
The models supported with the default OpenAI backend are:

```elisp
("gpt-3.5-turbo" "gpt-3.5-turbo-16k" "gpt-4" "gpt-4-turbo-preview" "gpt-4-32k" "gpt-4-1106-preview")
```

You have two options (see #197 for details):
1. `gpt-4-turbo-preview` is the same as `gpt-4-0125-preview`, so you can use that instead. 
2. [Add](https://github.com/karthink/gptel/issues/197#issuecomment-1918380973) `gpt-4-0125-preview` to the list of valid models.

**Comment by karthink** [comment]
Update: I added `gpt-4-0125-preview` explicitly to the list of available models, so you don't have to use `gpt-4-turbo-preview` instead.
