### ISSUE TITLE
how to open gptel in the current buffer?

### ISSUE THREAD

**Issue by gruns** [karthink/gptel#216]
when one runs `M-x gptel`, it picks another buffer, seemingly at random, and loads gptel therein

how can i force `M-x gptel` to open gptel in the current buffer?

thanks! 🙌 once determined, i can add this to the readme if helpful

**Comment by karthink** [comment]
I added a user option (`gptel-display-buffer-action`) that you can customize for this.

**Comment by gruns** [comment]
@karthink youre a hero 👏 

will wait for the next release which includes this 🙌

**Comment by karthink** [comment]
Cheers @gruns

**Comment by gruns** [comment]
@LazerJesus that is how does one use `gptel-display-buffer-action`?

**Comment by LazerJesus** [comment]
yes. i have the same irritation with the default behavior as you.

**Comment by karthink** [comment]
Try

```emacs-lisp
(setq gptel-display-buffer-action '(pop-to-buffer-same-window))
```
