### ISSUE TITLE
Kagi query produces no output

### ISSUE THREAD

**Issue by ezaquarii** [karthink/gptel#218]
I tried to query Kagi summarizer and fastgpt models. When sending a request, it says "Querying kagi..." and inserts an empty reply below the cursor.

I'm not sure how to debug it. I called `(setq gptel--debug t)` but I didn't get any error message.

**Comment by ezaquarii** [comment]
It was a service payment problem.

**Comment by karthink** [comment]
> I'm not sure how to debug it. I called `(setq gptel--debug t)` but I didn't get any error message.

For future reference, logging is handled by the variable gptel-log-level.  To generate a log of all requests, you can use

(setq gptel-log-level 'debug)   ;or 'info

Requests and responses are logged to the *gptel-log* buffer.
