### ISSUE TITLE
org-mode output is not properly formatted 

### ISSUE THREAD

**Issue by dasoju** [karthink/gptel#238]
Hi 
I am using gptel with gemini and i see that the formatting of org-mode is not looking right 
for example, in middle of my conversation,  i asked a question "can you recommend a package", it gave an answer with some options, but the alignment of the subheadings is off, as you can see in the snapshot below 

![image](https://github.com/karthink/gptel/assets/54728201/d7835e1e-a1f3-4f83-bd6e-36427c46e272)

**Comment by karthink** [comment]
I updated the Org formatting in b634f05f.  Please test (with the same or similar input to Gemini).

**Comment by dasoju** [comment]
also tables are getting garbled, for example, please see below 
![image](https://github.com/karthink/gptel/assets/54728201/b3a7efcd-946a-4141-b304-9a73022f4e42)

of course, once i go into the table and TAB, i get a better output, wondering if this can be fixed
![image](https://github.com/karthink/gptel/assets/54728201/625575d4-daed-4ff8-ae3d-f681d7dc7968)

**Comment by karthink** [comment]
> of course, once i go into the table and TAB, i get a better output, wondering if this can be fixed

The tables are inserted as they are received from the LLM, there is no text processing going on.

**Comment by dasoju** [comment]
Thanks for the fix, the formatting looks good now, basically as below 
![image](https://github.com/karthink/gptel/assets/54728201/58ca47ef-f843-4b22-bc17-4f1f313c30d7)

**Comment by karthink** [comment]
Very well, I'll close this issue now.

Auto-aligning tables is not planned for gptel, but you can do it via `gptel-post-response-functions` or `gptel-post-stream-hook`.  If you are interested in writing this hook function and need help please create a new issue.
