### ISSUE TITLE
Recursive require on emacs 29

### ISSUE THREAD

**Issue by avishefi** [karthink/gptel#239]
Getting `eval-buffer: Recursive load:` between gptel.elc and gptel-gemini.el

When byte compiling gptel-gemini.el:

```
Compiling file <REDACTED>/.emacs.d/elpa/gptel-20240308.224/gptel-gemini.el at Fri Mar  8 13:47:58 2024
Entering directory ‘<REDACTED>/.emacs.d/elpa/gptel-20240308.224/’
gptel-gemini.el:25:2: Error: Recursive ‘require’ for feature ‘gptel’
````

Performed a clean reinstall by deleting the gptel directory and reinstalling the package. While gptel functions correctly immediately after installation, a recursive require error is encountered upon restarting Emacs. This error renders gptel unusable after the initial session.

**Comment by karthink** [comment]
Not sure what could be causing this.

Can you share your config for gptel?

**Comment by avishefi** [comment]
I had this:

```elisp
(use-package gptel
  :defer t
  :commands (gptel gptel-menu gptel-send gptel-request)
  :bind (:map gptel-mode-map
              ("C-c C-<return>" . gptel-send))
  :custom
  (gptel-backend (gptel-make-gemini "Gemini"
                   :key #'gptel-api-key
                   :stream t))
  (gptel-model "gemini-pro")
  (gptel-log-level "debug"))
```

Commenting out `(gptel-backend ...` resolves the issue, so I moved it from `use-package`'s `:custom` to `:config` and now the error is gone.

This is how it works now:

```elisp

(use-package gptel
  :defer t
  :commands (gptel gptel-menu gptel-send gptel-request)
  :bind (:map gptel-mode-map
              ("C-c C-<return>" . gptel-send))
  :custom
  (gptel-model "gemini-pro")
  (gptel-log-level "debug") ;; nil, info, debug
  :config
  (setq gptel-backend (gptel-make-gemini "Gemini"
                        :key #'gptel-api-key
                        :stream t)))
```
