### ISSUE TITLE
Adding hook to `gptel-post-response-functions` results in error in process sentinel

### ISSUE THREAD

**Issue by daedsidog** [karthink/gptel#248]
`(add-hook 'gptel-post-response-functions (lambda () (message "hello")))`

Then send a message in `gptel`, this results in:

```
Send your query with C-c RET!
Querying ChatGPT...
error in process sentinel: run-hook-with-args: Wrong number of arguments: ((t) nil (message "hello")), 2
```

I'm on the latest commit. This also happens if I use `gptel-post-response-hook`.

**Comment by karthink** [comment]
Please see the docstring for `gptel-post-response-functions`.  It's an abnormal hook where each function is passed the bounds of the response.

**Comment by daedsidog** [comment]
Thanks, that was my fault.

**Comment by karthink** [comment]
> Thanks, that was my fault.

No worries, the API changed at some point because it was much more useful to be able to access the response bounds for further processing.

**Comment by daedsidog** [comment]
Yep, I did it manually so far. Great change.
