### ISSUE TITLE
(OpenAI) (Curl only) Response in log but but not in buffer

### ISSUE THREAD

**Issue by karthink** [karthink/gptel#254]
I have the same issue.

With streaming I can see the streamed response in the log but I still get the "Emtpy Response" message.

dot not work:
```
(setq gptel-use-curl t
         gptel-stream nil)
````

works:
```
(setq gptel-use-curl nil)
````

_Originally posted by @stfl in https://github.com/karthink/gptel/issues/251#issuecomment-1999446760_

**Comment by karthink** [comment]
@freddez is it resolved with the latest commit?

**Comment by freddez** [comment]
Absolutely !

**Comment by karthink** [comment]
@stfl Please update and test, it looks like it should be resolved.

**Comment by stfl** [comment]
It works for me now with 
```
         gptel-use-curl t
         gptel-stream t)
```

**Comment by stfl** [comment]
Thank you for getting this fixed so quickly.
