### ISSUE TITLE
Display sometimes fails to update with the latest `gptel` output

### ISSUE THREAD

**Issue by benthamite** [karthink/gptel#264]
I am experiencing an issue whereby the output of `gptel` is sometimes not displayed until I press a key or invoke `redraw-display`. The issue only happens sometimes, and it isn’t clear to me why it happens when it does happen.

I am not sure this is a problem with `gptel` itself: it may also be due to some peculiarity of my Emacs config. Unfortunately, after trying a bunch of things, including bisecting my `init.el` file, I am still unable to figure out what’s going on.

**Comment by karthink** [comment]
I'm completely clueless about this one, sorry.  I don't use `inhibit-redisplay`anywhere in gptel.

In any case, let's get some more information:

1. Emacs version
2. Terminal/GUI emacs, are you using a terminal multiplexer (tmux etc) if terminal
3. OS
4. gptel commit, or date installed if installed with package.el
5. streaming or oneshot responses with gptel
6. Any gptel-specific customizations (post-response-hook, pre-response-hook etc)
7. Are you using a special mode-line (Doom modeline etc) or header-line

**Comment by benthamite** [comment]
Thanks for replying. Since opening the issue, I noticed that the problem is affecting non-`gptel` buffers. So it’s clearly unrelated to this package specifically.
