### ISSUE TITLE
Error invoking gptel-menu

### ISSUE THREAD

**Issue by wrn** [karthink/gptel#265]
Emacs 29.1
Will have this error:
transient-setup: Wrong type argument: (or eieio-object cl-structure-object oclosure), "Model Parameters"

Fix:
[fix.patch](https://github.com/karthink/gptel/files/14667970/fix.patch)

**Comment by VitoVan** [comment]
The patch worked, thank you @wrn

**Comment by karthink** [comment]
Applied, thank you @wrn!
