### ISSUE TITLE
GPTel-menu on hitting enter makes a gptel-request but doesn't notify the user.

### ISSUE THREAD

**Issue by tusharhero** [karthink/gptel#293]
# Steps to reproduce
1. `M-x gptel RET`
2. `M-x gptel-menu RET`
3. `RET`

# Observation
A gptel-request is made but is not reflected on top bar (topleft).

# Expected result
A gptel-request is made and is reflected on top bar (topleft).

**Comment by gregoryg** [comment]
I can confirm - the "Ready" status is not changed when the request is sent from the transient menu.  When sending from the gptel-mode buffer using just `C-c RET`, the status is changed to 'Waiting' as expected.

**Comment by karthink** [comment]
Should be fixed, please test.

**Comment by karthink** [comment]
@gregoryg Thank you for confirming.
