### ISSUE TITLE
Add an option to not insert the response below but the message buffer.

### ISSUE THREAD

**Issue by nasyxx** [karthink/gptel#30]
Add an option to not insert the response below but the message buffer.  Or maybe in a sidewindow buffer?

I tried to find and edit where you insert the response but failed.

**Comment by karthink** [comment]
If I understand correctly, you want

- the prompt to be a selected region or the current line in a buffer, and
- the response to show up as a message or in a side-window.

Is this correct?

**Comment by nasyxx** [comment]
Yes!

**Comment by karthink** [comment]
Option added to the transient menu:

![2023-04-09-042930_918x376_scrot](https://user-images.githubusercontent.com/8607532/230770018-9ce87644-6c17-44af-bd39-8c899303dce1.png)

You can access it by calling `gptel-send` (`C-c RET`) with a prefix argument, or directly via `gptel-menu`

**Comment by nasyxx** [comment]
Great!

**Comment by karthink** [comment]
Also see the wiki for more options.
