### ISSUE TITLE
Auto Fill mode should be respected

### ISSUE THREAD

**Issue by sacredirritant** [karthink/gptel#302]
It would be nice if the response insertion behaved the same as ordinary interactive insertion so that inserting a space at a column beyond current-fill-column automatically breaks the line at a previous space when Auto Fill mode is enabled.  Long lines in the response are currently inserted as-is.

**Comment by karthink** [comment]
I don't think this is possible, auto-fill only works when running `self-insert` with space.  So it doesn't work in gptel for the same reason that it doesn't work when you yank text.

You can fill text in gptel's post-response hook:

```emacs-lisp
(add-hook 'gptel-post-response-functions 'fill-region)
```

Or, conditioned on `auto-fill-mode`,

```emacs-lisp
(add-hook 'gptel-post-response-functions
          (lambda (beg end)
            (when auto-fill-function
              (fill-region beg end))))
```

**Comment by sacredirritant** [comment]
I see, thank you for the work around.

**Comment by karthink** [comment]
Due to the way text properties are handled by gptel, you _may_ get errors with some LLMs when continuing a conversation after filling text.  If you get errors as a result of filling text please reopen this issue.

**Comment by willbush** [comment]
Thought this was working pretty well at first, but then noticed it messes up source block formatting.

```emacs-lisp
(add-hook 'gptel-post-response-functions
          (lambda (beg end)
            (when auto-fill-function
              (fill-region beg end))))
```

I ended up just going with soft-wrapping `(add-hook 'gptel-mode-hook #'visual-line-mode)`

**Comment by chrischambers** [comment]
I'm using a similar workaround now: visual-line-mode in combination with the visual-fill-column package, but would much prefer auto-fill. I humbly submit that this issue be revisited, as these are essentially workarounds.
