### ISSUE TITLE
How to disable the highlight after its done generating

### ISSUE THREAD

**Issue by Celibistrial** [karthink/gptel#308]
After generation of text the text is briefly highlighted in "yellow", how to disable this?

**Comment by karthink** [comment]
It's not possible to disable this right now.

**Comment by Celibistrial** [comment]
It looks kinda ugly 
![2024-05-09_20-41](https://github.com/karthink/gptel/assets/82810795/838a06a9-2b9c-4693-89f1-3c52821d1ae1)

**Comment by karthink** [comment]
Is the highlight persistent, or does it go away after a few milliseconds?

**Comment by Celibistrial** [comment]
Its not persistent , it doesn't go away on its own however (i have to press a button or move my mouse to make it go away)
I am using emacs in the GUI(DOOM emacs)

**Comment by karthink** [comment]
Try `(setq pulse-flag t)`.

**Comment by Celibistrial** [comment]
Oh thats much better, is there anyway to change the colour?

**Comment by karthink** [comment]
Yes, you can customize `pulse-highlight-start-face.`

**Comment by Celibistrial** [comment]
Oh okay thanks! This solves my issue.
Just a thought: adding an option to disable highlights might be helpful.

**Comment by karthink** [comment]
> Just a thought: adding an option to disable highlights might be helpful.

It's on the docket, will get to it at some point.

**Comment by Celibistrial** [comment]
Oh okay thanks! This solves my issue.
Just a thought: adding an option to disable highlights might be helpful.

**Comment by ryukinix** [comment]
> Yes, you can customize pulse-highlight-start-face.

Oh thank you, that was starting to disturbing me. A cleaner and more neutral option:

```emacs-lisp
(custom-set-faces
 '(pulse-highlight-start-face ((t (:background "gray10")))))
```

<img width="1115" height="376" alt="Image" src="https://github.com/user-attachments/assets/1a90854c-e61b-49de-9ef4-6f5bd5b406f2" />
