### ISSUE TITLE
error in process sentinel

### ISSUE THREAD

**Issue by ghowoo** [karthink/gptel#31]
I set up gptel by (straight-use-package 'gptel), and tried to run gptel in Emacs. It seems like I have successfully submitted the API key, but it gives me an error:

Send your query with C-c RET!
Querying ChatGPT...
error in process sentinel: gptel-curl--parse-response: Search failed: "some abc123 thing"
error in process sentinel: Search failed: "some abc123 thing"

I am able to run GPT 4 openai online and also be able to use openai api in R.

Any direction to solve the problem will be very helpful. 
Thanks.

**Comment by ghowoo** [comment]
Thanks karthink. I hope I get the value right:

(describe-variable gptel-use-curl)
#("t’s value is t

Not documented as a variable.

  Probably introduced at or before Emacs version 1.1.

" 96 99 (help-args ("c:/Program Files/Emacs/emacs-28.2/share/emacs/28.2/etc/NEWS.1-17" 95921) category help-news-button button (t)))

**Comment by karthink** [comment]
1. Did you use a dedicated gptel buffer (`M-x gptel`) or select some text in a regular buffer?

2. Could you please run `(setq gptel-use-curl nil)` and retry?

**Comment by ghowoo** [comment]
Thanks for help.
1, I use M-x gptel
2, I work on Windows 11
curl --version
curl 7.88.1 (Windows) libcurl/7.88.1 Schannel WinIDN
Release-Date: 2023-02-22
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets
3, After run (setq gptel-use-curl nil), gptel works.

I am not sure if it has solved the problem, but it works right now. thx.

**Comment by karthink** [comment]
It looks like you'll need curl v8.0 or higher to use it with gptel.

Of course, you can fall back to url-retrieve (as you did), but this doesn't support all the features -- specifically the live-streaming replies that will be added soon.

**Comment by jamauldrew** [comment]
(setq gptel-use-curl nil), works for me.
