### ISSUE TITLE
gptel waits for ever in org capture templates

### ISSUE THREAD

**Issue by JonatanSahar** [karthink/gptel#33]
To reproduce:

1. call `org-capture`, select a template
2. paste some text, select it
3. call `gptel-send`

**Comment by karthink** [comment]
I couldn't reproduce this. Could you try this after running `M-x toggle-debug-on-error`?

**Comment by karthink** [comment]
@JonatanSahar Are you still experiencing this issue?

**Comment by karthink** [comment]
Please reopen if this is still an issue.
