### ISSUE TITLE
How to pass additional options? Eg., num_ctx for Ollama

### ISSUE THREAD

**Issue by krvpal** [karthink/gptel#330]
Hi, thank you for this excellent package!

I'm using Ollama and to be able to set the context length, ollama [provides this option](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-specify-the-context-window-size):

```
"options": {
    "num_ctx": 4096
  }
```

I'm struggling to use this in Gptel. I understand there is a `curl-args` keyword, but any variation like the below I'm trying does not seem to be working. I've set `gptel-log-level` to `debug` and checking the logs, but the option does not show up.
```
  (defvar gptel--ollama
    (gptel-make-ollama
        "ollama"                             
      :host "localhost:12345"             
      :protocol "http"
      :models '("llama3")           
      :stream t
      :curl-args '("num_ctx:4096")
      ))                             
```

Please help!

**Comment by karthink** [comment]
gptel uses Ollama's `/api/chat` endpoint, not `/api/generate`.  I'm not sure if `num_ctx` is meaningful for Chat-style requests.

In any case, `num_ctx` is not explicitly supported by gptel.  If you want to limit the context size, you can run the relevant `/set parameter ...` command in Ollama itself, or use the `-n` option in gptel's transient menu to limit the request to the last `n` responses:

![Screenshot_20240618_145812](https://github.com/karthink/gptel/assets/8607532/94cd77ac-cd0c-49a4-91ef-5702bf5caa78)

---
Only a subset of options common to most LLM APIs is exposed by gptel right now.  I plan to eventually cover backend-specific parameters, such as `num_ctx`, but this won't be any time soon.

**Comment by krvpal** [comment]
Thanks for your response. 

I'm looking to increase the default context length. Without passing the `num_ctx` to Ollama, the context length is always set to 2048. This is a problem when I'm using Gptel to summarize text, which is longer and the response I receive only considers the last paragraph. 

I would like to increase context length to 4096 or higher, as there are fine tuned llama3 models that are capable of 8x the usual context length. 

This is a powerful use case to summarize long texts in org, markdown or any text file if one could set `num_ctx`. I'm using the `-n` parameter already as suggested. 

Is using `curl-args` out of the question? 

Thanks!

**Comment by karthink** [comment]
> I'm looking to increase the default context length. Without passing the `num_ctx` to Ollama, the context length is always set to 2048. This is a problem when I'm using Gptel to summarize text, which is longer and the response I receive only considers the last paragraph.
> 
> I would like to increase context length to 4096 or higher, as there are fine tuned llama3 models that are capable of 8x the usual context length.

I understand.

> This is a powerful use case to summarize long texts in org, markdown or any text file if one could set `num_ctx`. I'm using the `-n` parameter already as suggested.

The `-n` parameter will help limit the context size further, but not increase the default.  So you're right about it being not useful for your use case.

> I'm not sure how `/set parameter ...` would work, because I typically start the Ollama server and Gptel handles the rest. I do not use `ollama run` which is the command that accepts this option. I will explore configuring Ollama server itself in the meantime.

As stated above, there is currently no way to set this using gptel.  Since you're running Ollama somewhere that you control (I'm assuming), you can set this parameter from the Ollama CLI instead.  I'm not sure exactly how to do this either, [this looks promising](https://github.com/ollama/ollama/blob/main/README.md#customize-a-prompt).  It also seems like you should be able to type `/set parameter ...` into the CLI when using `ollama run`.

> Is using `curl-args` out of the question?
> 
> Thanks!

`:curl-args` is for supplying command line arguments to Curl, such as for additional authentication, web proxy etc.  It does not affect the contents of the JSON packet to be sent to Ollama.

**Comment by krvpal** [comment]
Got it! Thanks again. 

I do control the Ollama server as it is running locally. I believe I should be able to create my own "modelfile" with the required parameters and use it as a custom model. 

`ollama run` creates a fresh instance every time, I do not think it will help in this case.

**Comment by Frozenlock** [comment]
@krvpal have you had any success? I'm also wondering how to increase the context length.

**Comment by karthink** [comment]
Until I can add official support for num_ctx to gptel, I can address this problem by picking a high (but not too high) default value sent with all requests to Ollama.  What token count do you suggest? 2048? 4096? Higher?

**Comment by karthink** [comment]
I've added support for `num_ctx` via `gptel-max-tokens`.  You can set this using the `-c` option in gptel's menu, or just set the variable directly.  Please update, test and let me know.

**Comment by karthink** [comment]
> I've added support for `num_ctx` via `gptel-max-tokens`.  You can set this using the `-c` option in gptel's menu, or just set the variable directly.  Please update, test and let me know.

I've had to revert this change since there's no way to control the response token limit without `gptel-max-tokens`.  For now we'll have to settle for adding a high enough default `num_ctx` parameter to requests.

**Comment by krvpal** [comment]
> @krvpal have you had any success? I'm also wondering how to increase the context length.

Hi @Frozenlock , I used 'modelfile' to configure `num_ctx` and run that model with a different name in Ollama. Here's a [nice article](https://www.gpu-mart.com/blog/custom-llm-models-with-ollama-modelfile) you may find useful, and the official [reference](https://github.com/ollama/ollama/blob/main/docs/modelfile.md#format).




> > I've added support for `num_ctx` via `gptel-max-tokens`.  You can set this using the `-c` option in gptel's menu, or just set the variable directly.  Please update, test and let me know.
> 
> I've had to revert this change since there's no way to control the response token limit without `gptel-max-tokens`. For now we'll have to settle for adding a high enough default `num_ctx` parameter to requests.


Hi @karthink, current llama3 model supports up to 8192 tokens. I'd recommend to set this max value itself as the default for Ollama, and if for any reason one needs to reduce the context tokens, they can always use the `-n` option in gptel's menu.

**Comment by karthink** [comment]
> Hi @karthink, current llama3 model supports up to 8192 tokens. I'd recommend to set this max value itself as the default for Ollama, and if for any reason one needs to reduce the context tokens, they can always use the `-n` option in gptel's menu.

Done, thank you for the suggestion.

I will close this issue now.  I have a TODO item to make this customizable in the future, after gptel gets the ability to handle per-backend and per-model capabilities.

**Comment by ProjectMoon** [comment]
One thing to be aware of is that increasing context size with ollama will cause it to allocate more memory on the server. Just in case you get any reports of people having issues with memory errors after this change...

**Comment by wangwb98** [comment]
Hi @karthink , @krvpal ,
it seems using :header field to set up num_ctx can work fine (of course you have to remove the 8192 force setting in gptel--request-data)

For example, my setup is like this:
```
(setq-default gptel-model "qwen2.5"
              gptel-default-mode 'org-mode
              gptel-backend    (gptel-make-ollama "GPU-Ollama"
                                 :host "10.1.0.101:11434" 
                                 :stream nil
                                 :header '(("num_ctx" . "32768") ("num_predict". "-1"))
                                 :models '("qwen2.5")))

```

**Comment by sivaramn** [comment]
> Hi @karthink , @krvpal , it seems using :header field to set up num_ctx can work fine (of course you have to remove the 8192 force setting in gptel--request-data)
> 
> For example, my setup is like this:
> 
> ```
> (setq-default gptel-model "qwen2.5"
>               gptel-default-mode 'org-mode
>               gptel-backend    (gptel-make-ollama "GPU-Ollama"
>                                  :host "10.1.0.101:11434" 
>                                  :stream nil
>                                  :header '(("num_ctx" . "32768") ("num_predict". "-1"))
>                                  :models '("qwen2.5")))
> ```

what other parameters do you use in the header option? if there is a way to dynamically modify it before `gptel-send` or any other command, it would be super useful.

**Comment by ProjectMoon** [comment]
> Hi @karthink , @krvpal , it seems using :header field to set up num_ctx can work fine (of course you have to remove the 8192 force setting in gptel--request-data)
> 
> For example, my setup is like this:
> 
> ```
> (setq-default gptel-model "qwen2.5"
>               gptel-default-mode 'org-mode
>               gptel-backend    (gptel-make-ollama "GPU-Ollama"
>                                  :host "10.1.0.101:11434" 
>                                  :stream nil
>                                  :header '(("num_ctx" . "32768") ("num_predict". "-1"))
>                                  :models '("qwen2.5")))
> ```

How does one move the `num_ctx` from `gptel--request-data`? Are you just patching the package manually, or do you have some `advice` that wraps the function?

**Comment by wangwb98** [comment]
@sivaramn @ProjectMoon my appology, I found my local hack in the gptel code to force setting the :header value to :options in API request to ollama. Thus my previous post wasn't complete, sorry for the confusion.

And @sivaramn  is right, it's better to use a more dynamic way to set this. Let me see if I can come up with a patch soon.

**Comment by wangwb98** [comment]
I'm now using the advice to achieve this goal, you guys may want to have a try.

~~~elisp
(defvar my-ollama-num-ctx nil
  "Custom num_ctx value for gptel--request-data when backend is gptel-ollama, if it's non-nil.")

(defun my-gptel--request-data-advice (orig-fn _backend &rest args)
  "Advice to replace :num_ctx in options-plist with `my-ollama-num-ctx` only for gptel-ollama backend."
  (if (and (cl-typep _backend 'gptel-ollama)
           my-ollama-num-ctx)
      (let ((prompts-plist (apply orig-fn _backend args)))
        ;; replace value of :num_ctx to `my-ollama-num-ctx`
        (let ((options (plist-get prompts-plist :options)))
          (when (plist-member options :num_ctx)
            (plist-put options :num_ctx my-ollama-num-ctx))
          (plist-put prompts-plist :options options))
        prompts-plist)
    (apply orig-fn _backend args)))

(advice-add 'gptel--request-data :around #'my-gptel--request-data-advice)
~~~

**Comment by karthink** [comment]
**Breaking change**:  The ad hoc setting of 8192 for `num_ctx` has now been removed.  Please read this to see how to configure it:

----

I've added support for arbitrary request parameters/options to be included with requests.  You can set these parameters at the backend level or at the model level, as follows:

As a backend property:
```elisp
(gptel-make-ollama "ollama"                             
  :host "localhost:12345"             
  :protocol "http"
  :models '(llama3)           
  :stream t
  :request-params
  '(:options (:num_ctx 4096
              :top_p 0.9
              :low_vram :json-false
              :num_thread 8
              :stop ["\n"])))
```

These are converted to JSON and included with the query payload as-is, so this is a direct translation of Ollama's supported options, [as described here](https://github.com/ollama/ollama/blob/main/docs/api.md#request-7).

As a model property:
```elisp
(gptel-make-ollama "ollama"                             
  :host "localhost:12345"             
  :protocol "http"
  :models
  '(openhermes-latest
    (llama3 :request-params '(:options
                              (:num_ctx 4096
                               :top_p 0.9
                               :low_vram :json-false
                               :num_thread 8
                               :stop ["\n"]))))           
  :stream t)
```

Model-level parameters override backend-level parameters, which override gptel's user options (when they exist, such as with `gptel-max-tokens`).

So you can set these parameters per-model in your configuration.
