### ISSUE TITLE
Plans to add DeepSeek API support?

### ISSUE THREAD

**Issue by jamorphy** [karthink/gptel#333]
Or is OpenRouter the only possible way for now?

**Comment by karthink** [comment]
I hadn't heard of DeepSeek.  From a cursory glance, it looks like it supports the OpenAI API, so you should already be able to use it with gptel.

Can you link me to the DeepSeek API reference page?  When I try it asks me to create an account.

**Comment by jamorphy** [comment]
I've been using it via openrouter but I'll try with the OpenAI format. The API docs are here: https://platform.deepseek.com/api-docs/

Thanks for your work on the package, it's great

**Comment by karthink** [comment]
Looks like it's as simple as
```elisp
(gptel-make-openai "DeepSeek"
  :stream t
  :key "your-deepseek-api-key-or-function"
  :host "api.deepseek.com"
  :endpoint "/chat/completions"
  :models '("deepseek-chat" "deepseek-coder"))
```

Could you test this?  If it works I can add it to the README.

**Comment by jamorphy** [comment]
Tested it, works as expected.

**Comment by karthink** [comment]
Thank you. Added instructions to the README.

**Comment by karthink** [comment]
There is now a `gptel-make-deepseek` that's simpler to use and also supports including the "reasoning" part of the response.

``` emacs-lisp
(gptel-make-deepseek "DeepSeek"       ;Any name you want
  :stream t                           ;for streaming responses
  :key "your-api-key")               ;can be a function that returns the key
```
