### ISSUE TITLE
An Emacs mode declaration at top of file causes duplicate org-mod properties

### ISSUE THREAD

**Issue by ProjectMoon** [karthink/gptel#337]
If you follow [this](https://www.gnu.org/software/emacs/manual/html_node/emacs/Choosing-Modes.html), to declare an org-mode buffer with gptel auto-enabled:  `; ; -*- mode: org-mode; eval: (gptel-mode 1); -*-` You will wind up with multiple property blocks in the file. Putting the mode declaration at the file causes gptel to write a new property block in the org file with its own settings, rather than using the org property block right below it.

Is there a workaround to have certain org-mode files automatically load gptel, while others do not? Without having to muck around with the auto mode alist, preferably.

**Comment by karthink** [comment]
Couldn't reproduce this.  I tried:

1. In a chat buffer, call `M-x add-file-local-variable-prop-line`
2. Choose `eval`, type in `(gptel-mode 1)` or what's in the screenshot below.
3. Save the file.  Only one properties block is created, or when there's one below the header line already, it's reused.

![image](https://github.com/karthink/gptel/assets/8607532/7314615a-1d6a-457d-b6e9-d20462edba4d)

**Comment by karthink** [comment]
> Is there a workaround to have certain org-mode files automatically load gptel, while others do not? Without having to muck around with the auto mode alist, preferably.

Adding that file-local var -- or dir-local if you store your chats in one place -- is the only way right now.  What do you mean by "certain org-mode files"?

**Comment by ProjectMoon** [comment]
OK I think the reason this happened was because I actually started my prop line with `;` instead of `#` for org-mode.

**Comment by karthink** [comment]
> OK I think the reason this happened was because I actually started my prop line with `;` instead of `#` for org-mode.

I avoid writing these by hand since they're easy to mess up, hence add-file-local-variable-prop-line.
