### ISSUE TITLE
The suggested default key binding confliction with auctex.

### ISSUE THREAD

**Issue by hongyi-zhao** [karthink/gptel#34]
I'm using auctex, which has bound the following short key, conflicted with [the suggested one used by this package](https://github.com/karthink/gptel#in-a-dedicated-chat-buffer):
```emacs
C-c RET (translated from C-c <return>) runs the command
TeX-insert-macro (found in LaTeX-mode-map), which is an interactive
byte-compiled Lisp function in ‘tex.el’.

It is bound to C-c RET.

(TeX-insert-macro SYMBOL)

Insert TeX macro SYMBOL with completion.

AUCTeX knows of some macros and may query for extra arguments, depending on
the value of ‘TeX-insert-macro-default-style’ and whether ‘TeX-insert-macro’
is called with C-u.

[back]
```
Considering that auctex is a very popular tool with a long history, I don't want to change its default key binding convention. So, I ask you for an alternative key binding convention in your package.

Regards,
Zhao

**Comment by karthink** [comment]
I don't see where the conflict is. `gptel-send` is not bound to any key unless you're in a special buffer you create with `M-x gptel` -- in which case you're not in `latex-mode`.

**Comment by hongyi-zhao** [comment]
Say, I'm in [AUCTeX](https://www.gnu.org/s/auctex/) buffer, `C-c RET` will not trigger `gptel-send`.

**Comment by karthink** [comment]
> Say, I'm in [AUCTeX](https://www.gnu.org/s/auctex/) buffer, `C-c RET` will not trigger `gptel-send`, and as an alternative, now I rebound it to `F2`.

Sorry, I don't follow. `gptel-send` is not bound to _any_ key, so you're free to bind it as you please, or just call `M-x gptel-send`. So where is the conflict?

**Comment by hongyi-zhao** [comment]
If so, why do you give [the following description](https://github.com/karthink/gptel#in-a-dedicated-chat-buffer):
![image](https://user-images.githubusercontent.com/11155854/230240758-4e28e80b-f733-4965-9e21-f7022812617a.png)

**Comment by karthink** [comment]
It's bound to `C-c RET` in dedicated gptel buffers, i.e. one created using `M-x gptel`. But this is a markdown or org buffer (depending on the value of `gptel-default-mode`), not an AuCTeX buffer.

Of the two ways of using gptel (in a dedicated chat buffer vs queries in any buffer), may I ask how you use or would like to use gptel?

**Comment by hongyi-zhao** [comment]
> Of the two ways of using gptel (in a dedicated chat buffer vs queries in any buffer), may I ask how you use or would like to use gptel?

Both. They have their own advantages and disadvantages. Therefore, I am seeking a unified shortcut key convention.

**Comment by karthink** [comment]
I see. Do you have a suggestion for a keybinding that works in both contexts?

**Comment by hongyi-zhao** [comment]
I use the following:
```emacs
(use-package gptel
  :bind
  (
   ("<f2>" . gptel-send)
   )

  :config
  (setq gptel-api-key "sk-xxx")
  )
```

![image](https://user-images.githubusercontent.com/11155854/230256516-f8412b30-ffc1-48ba-81dc-f35e4c5d151a.png)
