### ISSUE TITLE
Feature Request: Always save `gptel--system-message` in file-local variables

### ISSUE THREAD

**Issue by TxGVNN** [karthink/gptel#340]
The first, thanks for a great package. I'm using it every day.

Currently, the system message is only saved in file-local variables if it deviates from the default. This could lead to reproducibility issues, especially if we (or even myself in the future) change the default system message. 

For instance, let's say I have a file using the default system message. Later, I change the default message changes. Now, if I try to use the old file, I might get unexpected results because the saved system message (which wasn't stored as it was the default) is different from the new default.

To address this, I propose always saving the `gptel--system-message` to file-local variables.  
```diff
-             (unless (string= (default-value 'gptel--system-message)
-                              gptel--system-message)
-               (add-file-local-variable 'gptel--system-message gptel--system-message))
+             (add-file-local-variable 'gptel--system-message gptel--system-message)
```

P/S: This issue is created by me with gptel tool.

Best regards!

**Comment by karthink** [comment]
This was done intentionally to limit how much metadata is written, but perhaps I should err on the side of reproducibility as you suggest.  Please note that the entire local variables block cannot be more than 3000 characters in size, this is an Emacs limitation.  So if your system message is long (as they often tend to be), it can break things.

**Comment by TxGVNN** [comment]
Thank you for your feedback. Oh, I was unaware of the character limit for local variable declarations.  We should proactively choose saving instead of defaulting. Thank you
