### ISSUE TITLE
Typo in defining the gtpel minor mode

### ISSUE THREAD

**Issue by thomassdk** [karthink/gptel#35]
Just a minor typo which doesn't have any effect as the default for `:global` is the same as setting it to `nil` but spotted during a curiosity dive. Didn't seem significant enough to warrant a PR

https://github.com/karthink/gptel/blob/e2afe5000e507c4e8f06732cf788da09c76869b9/gptel.el#L235

**Comment by karthink** [comment]
@thomassdk thanks. Since you mentioned "curiosity dive": If you're in an exploratory mood, could you check out the `streaming` branch of the repo, set `gptel-playback` to `t` and try using the package? I've got real-time streaming working but I'm wondering if it works for anyone else yet.

**Comment by karthink** [comment]
Thanks, I pushed it to master.

I'll fix the `:global nil` line soon. At some point `gptel-mode` was set to be `:global t` and I didn't clean things up after the design changed.

**Comment by karthink** [comment]
Fixed.
