### ISSUE TITLE
Internal--without-restriction function error when adding current buffer as context to GPTEL

### ISSUE THREAD

**Issue by vick08** [karthink/gptel#350]
When attempting to add the current buffer as a context for GPTEL, using the gptel-add command, I am getting the "internal--without-restriction" error.
here is the output from a debugger:
Debugger entered--Lisp error: (void-function internal--without-restriction)
  internal--without-restriction(#f(compiled-function () #<bytecode 0x126b529e4d9109c9>))
  gptel-context--insert-buffer-string(#<buffer *LLM response*> (#<overlay from 1 to 1953 in *LLM response*>))
  gptel-context--string(((#<buffer *LLM response*> #<overlay from 1 to 1953 in *LLM response*>)))
  gptel-context--wrap-default("You are a large language model living in Emacs and a helpful assistant. Respond concisely." ((#<buffer *LLM response*> #<overlay from 1 to 1953 in *LLM response*>)))
  gptel-context--wrap("You are a large language model living in Emacs and a helpful assistant. Respond concisely.")
  gptel-request(nil :stream t)
  #f(compiled-function (&optional arg) "Submit this prompt to the current LLM backend.\n\nBy default, the contents of the buffer up to the cursor position\nare sent.  If the region is active, its contents are sent\ninstead.\n\nThe response from the LLM is inserted below the cursor position\nat the time of sending.  To change this behavior or model\nparameters, use prefix arg ARG activate a transient menu with\nmore options instead.\n\nThis command is asynchronous, you can continue to use Emacs while\nwaiting for the response." (interactive "P") #<bytecode -0x55582ff17135115>)(nil)
  apply(#f(compiled-function (&optional arg) "Submit this prompt to the current LLM backend.\n\nBy default, the contents of the buffer up to the cursor position\nare sent.  If the region is active, its contents are sent\ninstead.\n\nThe response from the LLM is inserted below the cursor position\nat the time of sending.  To change this behavior or model\nparameters, use prefix arg ARG activate a transient menu with\nmore options instead.\n\nThis command is asynchronous, you can continue to use Emacs while\nwaiting for the response." (interactive "P") #<bytecode -0x55582ff17135115>) nil)
  gptel-org--send-with-props(#f(compiled-function (&optional arg) "Submit this prompt to the current LLM backend.\n\nBy default, the contents of the buffer up to the cursor position\nare sent.  If the region is active, its contents are sent\ninstead.\n\nThe response from the LLM is inserted below the cursor position\nat the time of sending.  To change this behavior or model\nparameters, use prefix arg ARG activate a transient menu with\nmore options instead.\n\nThis command is asynchronous, you can continue to use Emacs while\nwaiting for the response." (interactive "P") #<bytecode -0x55582ff17135115>) nil)
  apply(gptel-org--send-with-props #f(compiled-function (&optional arg) "Submit this prompt to the current LLM backend.\n\nBy default, the contents of the buffer up to the cursor position\nare sent.  If the region is active, its contents are sent\ninstead.\n\nThe response from the LLM is inserted below the cursor position\nat the time of sending.  To change this behavior or model\nparameters, use prefix arg ARG activate a transient menu with\nmore options instead.\n\nThis command is asynchronous, you can continue to use Emacs while\nwaiting for the response." (interactive "P") #<bytecode -0x55582ff17135115>) nil)
  gptel-send(nil)
  #<subr funcall-interactively>(gptel-send nil)
  apply(#<subr funcall-interactively> gptel-send nil)
  ad-Advice-funcall-interactively(#<subr funcall-interactively> gptel-send nil)
  apply(ad-Advice-funcall-interactively #<subr funcall-interactively> (gptel-send nil))
  funcall-interactively(gptel-send nil)
  call-interactively(gptel-send nil nil)
  command-execute(gptel-send)

**Comment by karthink** [comment]
What's your Emacs version and how did you install gptel?

**Comment by vick08** [comment]
Ah so sorry, I should have known you would ask. :)
I am on Emacs 30.
I installed GPTEL via the built-in package manager, c-h p, the version from melpa-stable.

**Comment by karthink** [comment]
Hmm, I'm not sure what the problem is then.  Can you check if `internal--without-restriction` is defined in `subr.el` in Emacs 30?

**Comment by vick08** [comment]
I am far from being an Emacs expert, but in looking at subr.el in the "lisp" folder, I do not find the "internal--without-restriction" function. The only thing that gets close to it is the 

(defmacro without-restriction (&rest rest)
  "Execute BODY without restrictions.

The current restrictions, if any, are restored upon return.

When the optional LABEL argument is present, the restrictions set
by `with-restriction' with the same LABEL argument are lifted.

\(fn [:label LABEL] BODY)"
  (declare (indent 0) (debug t))
  (if (eq (car rest) :label)
      `(save-restriction (internal--labeled-widen ,(cadr rest)) ,@(cddr rest))
    `(save-restriction (widen) ,@rest)))


Hope this helps somewhat?

**Comment by karthink** [comment]
Where is this macro defined?

**Comment by karthink** [comment]
It looks like `internal--without-restriction` changed to `internal--labeled-widen` in Emacs 30.  Macro expansions in gptel should be updated to match.  Did you have gptel installed already when you upgraded to Emacs 30? Rebuilding/reinstalling gptel should solve the issue then.

**Comment by vick08** [comment]
I thought I reinstalled GPTEL after installing Emacs 30, but apparently, I did not. Uninstalled / reinstalled it again, and things seem to be working fine. Thank you!
