### ISSUE TITLE
Anthropic request error

### ISSUE THREAD

**Issue by pirminj** [karthink/gptel#354]
When setting up the Anthropic backend with 

```
(gptel-make-anthropic "Claude"
    :stream t
    :key (getenv "ANTHROPIC_API_KEY"))
```

the requests fail with `Claude error: (HTTP/2 401) x-api-key header is required`

**Comment by karthink** [comment]
Does `(getenv "ANTHROPIC_API_KEY")` return the right API key in your Emacs session?
