### ISSUE TITLE
url issue for awesome prompts?

### ISSUE THREAD

**Issue by jamadri** [karthink/gptel#360]
https://github.com/karthink/gptel/blob/175e8d2efe0e6b8757f06b863096e514fd731f50/gptel-transient.el#L107
In case that helps,
I had to replace the gptel--crowdsourced-prompts-url variable with
"https://raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv"

I am using emacs>27 on windows (no wsl)

**Comment by karthink** [comment]
Both the current URL and the one you propose work for me.  I'll change it to the one you suggest assuming that the current URL doesn't work for some people.

In any case, I plan to replace these crowdsourced prompts with the ones provided by the Fabric project.
