### ISSUE TITLE
Incorrect added buffer content in gptel-context-add

### ISSUE THREAD

**Issue by jonmoore** [karthink/gptel#368]
In `gptel-context-add` the code below prompts for a buffer name and adds its contents to the context:
https://github.com/karthink/gptel/blob/17f39f6a8144496252eacc012ef7f1d6a2ac883a/gptel-context.el#L114-L117

The intent is to add the complete buffer contents but `(point-min)` and `(point-max)` are evaluated in the then-current buffer rather than the target buffer, often resulting in incomplete content. I think this can be fixed as follows:
```elisp
    (let* ((buffer-name (read-buffer "Choose buffer to add as context: " nil t))
           (buffer-to-add (get-buffer buffer-name)))
      (gptel-context--add-region
       buffer-to-add
       (with-current-buffer buffer-to-add (point-min))
       (with-current-buffer buffer-to-add (point-max))
       t)
      (message "Buffer '%s' added as context." buffer-name)))
```

**Comment by karthink** [comment]
This was reported a while ago, thanks for the reminder. Fixed just now by PR #358.
