### ISSUE TITLE
magit COMMIT_EDITMSG buffer interpreted as Prose editor context

### ISSUE THREAD

**Issue by nfedyashev** [karthink/gptel#370]
I've tried calling gptel in the context of magit while writing commit message

```
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
```

`(print major-mode)` in such buffer outputs `text-mode`

`You are a prose editor. Rewrite the following text to be more professional`
I suspect that's not the prefilled context that a typical user might want(no disrespect to all Prose editors Emacs users).

LLM as git commit message (re)write tool seems to be pretty popular topic accordingly to Google search results. Perhaps it is worth improving this workflow for end users.

My suggestion - instead of just checking major-mode name, prior to that check whether `buffer-file-name` contains `COMMIT_EDITMSG` string and in this case, set a special context instead of the default one for text-mode(Prose editor).

Perhaps something like "You are git expert. What you write will be passed to git commit -m \"[message]\". Rewrite the following message."

**Comment by karthink** [comment]
The refactoring interface needs a fair bit of work instead of micro-fixes, unfortunately.  Let's leave this issue open for now while I figure out how the redesigned interface should work.

**Comment by karthink** [comment]
The refactoring interface has been redesigned from scratch (the workflow change should be apparent when you use it).  

> My suggestion - instead of just checking major-mode name, prior to that check whether buffer-file-name contains COMMIT_EDITMSG string and in this case, set a special context instead of the default one for text-mode(Prose editor).

For the issue of specialized refactor messages like this one, I've added a user option (`gptel-rewrite-directives-hook`) to which you can add functions.  Each function in the hook is called until one returns a (non-nil) string, the default refactoring instruction.  The function can use any logic to prepare the instruction.  In this case, you could do something like:

```elisp
(defun gptel-rewrite-commit-message ()
  (when (and (string-match-p "COMMIT_EDITMSG" (buffer-name))
             (derived-mode-p 'text-mode))
    "You are a git expert.  What you write will be passed to git commit -m \"[message].  Rewrite the following message."))

(add-hook 'gptel-rewrite-directives-hook #'gptel-rewrite-commit-message)
```

I can think about including messages for some common special cases (like this one) to the default value of this hook in gptel, but it'll help to get some feedback on how this system works first.

**Comment by nfedyashev** [comment]
This one sounds like perhaps it can be closed :+1: 
Thank you

**Comment by karthink** [comment]
Closing, but if you have feedback on some default cases to include in this hook please let me know.
