### ISSUE TITLE
"LLM refactor outputready.  M-x gptel-menu to continue ✓"

### ISSUE THREAD

**Issue by nfedyashev** [karthink/gptel#376]
@karthink I was testing the new rewrite approach and noticed this message which seems a bit weird without a space between "output" and "ready" words.

Not sure yet where this is coming from

**Comment by karthink** [comment]
Is the problem just the typo or the message itself?

**Comment by nfedyashev** [comment]
just the typo I think(missing space between words)

**Comment by karthink** [comment]
Okay, I'm assuming the message itself is not confusing then.  I'll fix the typo, but do you think the message needs to be improved in some way, to give you more context about what just happened?

**Comment by nfedyashev** [comment]
I think the message was pretty clear

**Comment by karthink** [comment]
Should be fixed.

**Comment by nfedyashev** [comment]
can confirm it is fixed, thank you
