### ISSUE TITLE
[Bug] `gptel--convert-markdown->org` accidentally change `#` in source blocks to `*`

### ISSUE THREAD

**Issue by rennsax** [karthink/gptel#380]
If the server responses with something like:

<pre>
``` bash
# This is a comment
make all
```
</pre>

Then `gptel--convert-markdown->org` will convert `#` to `*`, which is not the desired behavior.

**Comment by karthink** [comment]
Note that
`````
``` bash
`````
is not [valid markdown for a fenced code block](https://spec.commonmark.org/0.31.2/#fenced-code-blocks).  It should be
`````
```bash
`````
Are you sure that the server is responding with that extra space between the ticks and `bash`?  You can turn on logging with `(setq gptel-log-level 'info)` and check the `*gptel-log*` buffer.

**Comment by rennsax** [comment]
Oh, dear, I couldn't reproduce this bug with my LLM backend 🥲. I'll close my issue until I figure out whether it's due to the irregular responses from the backend. Thanks for your reply very much!
