### ISSUE TITLE
GPTel entering text after the cursor

### ISSUE THREAD

**Issue by motaatmo** [karthink/gptel#391]
Hi,

when I'm using GPTel in the dedicated buffer (i.e. as a chat interface), the model response ends up after the cursor, so I have to move to the end of the file to continue.

The behavior is (I just entered "Test" and pressed C-c ret):
```

### Test█

Test received! How can I assist you today?

### 
```

What I want is this:

```

### Test

Test received! How can I assist you today?

### █
```

Greetings!

**Comment by karthink** [comment]
Please see the FAQ in the Readme.

**Comment by motaatmo** [comment]
Ah, sorry! I tried to find something like this in the Readme, but
somehow I failed... probably because I used the wrong search terms.
