### ISSUE TITLE
formatting in-buffer refactored code function made as a configuration option 

### ISSUE THREAD

**Issue by sivaramn** [karthink/gptel#402]
https://github.com/karthink/gptel/wiki/Tweaking-LLM-responses#formatting-in-buffer-refactored-code

The above is very useful when using it as a copilot development style workflow.  Can this be made as a configurable option in gptel instead of a tip in the repo? I believe this is the most common use case for a developer, code insertion without the markdown mode

**Comment by karthink** [comment]
Have you tried the full-fledged rewriting interface that's available in gptel?

![image](https://github.com/user-attachments/assets/ce103455-c873-4242-9cc5-c70d749465fa)

**Comment by sivaramn** [comment]
> Have you tried the full-fledged rewriting interface that's available in gptel?
> 

Tried it now.  Works well.  With llama 3.2 in ollama, on an empty file with comment strings on what I want each function to do, it sorts of fills it out. Not under each comment but at the bottom with fresh code.  Must be an LLM issue

**Comment by sivaramn** [comment]
This issue can be closed

**Comment by karthink** [comment]
It only fills in the region that's selected, so it can't make make multiple edits in different places in the buffer at once.  If I understand correctly, you want something like [Evedel](https://github.com/daedsidog/evedel) for a more code-intensive AI assistant workflow.  Evedel builds on gptel and reuses its configuration so you shouldn't have any issues setting it up.

**Comment by karthink** [comment]
There is also [Elysium](https://github.com/lanceberge/elysium) for a different workflow, which is also using `gptel`.

I'm not a programmer -- my coding needs are minimal.  So gptel only includes some basic refactoring/codegen features.  Thankfully there are a few alternative workflows for this task created by professional programmers, some of which are built on top of gptel -- hopefully one of them will work for you.

**Comment by sivaramn** [comment]
> It only fills in the region that's selected, so it can't make make multiple edits in different places in the buffer at once. If I understand correctly, you want something like [Evedel](https://github.com/daedsidog/evedel) for a more code-intensive AI assistant workflow. Evedel builds on gptel and reuses its configuration so you shouldn't have any issues setting it up.

Well I do highlight all the commented lines;

# create add_nbr for only int

#create sub_nbrs for float

I select all the above lines and hit 'r', I was expecting it to fill in code under the respective comments.  But it currently does it all below the selected region

**Comment by karthink** [comment]
> Well I do highlight all the commented lines;
>
> # create add_nbr for only int
>
> #create sub_nbrs for float
>
> I select all the above lines and hit 'r', I was expecting it to fill in code under the respective comments.
>
> But it currently does it all below the selected region

Below the region?  It should fill out the region itself.  It looks like you need to update gptel, you're a few months behind.

(NOTE: It's still not going to add code under the respective comments.)
