### ISSUE TITLE
Does not work with Chinese words.

### ISSUE THREAD

**Issue by Standinocw** [karthink/gptel#404]
This tool does not support Chinese. If the org file contains Chinese, it will send garbled code to the backend's large model.

**Comment by karthink** [comment]
What is the value of `buffer-file-coding-system` in this Org buffer?

**Comment by Standinocw** [comment]
> What is the value of `buffer-file-coding-system` in this Org buffer?

Its value is ‘utf-8-dos’
Local in buffer linux.org; global value is utf-8

**Comment by karthink** [comment]
What is

- the value of the variable `gptel-use-curl`
- the OS you are using (Windows/Mac/Linux)
- the version of Emacs
- the commit of gptel you're running (if you don't know you can describe when/how you installed it)

**Comment by karthink** [comment]
What is the value of `default-process-coding-system` in your Emacs?

**Comment by Standinocw** [comment]
it works now. Thanks.
