### ISSUE TITLE
Warning after upgrading to a new gptel version

### ISSUE THREAD

**Issue by wlauppe** [karthink/gptel#423]
After upgrading to the newest version of gptel i got the following warning: 

```
Warning (native-compiler): gptel-org.el:338:26: Warning: the function ‘gptel--to-number’ is not known to be defined.
```

its only shown the first time emacs starts after an upgrade, if i close emacs after the initial run and run it again there are now warnings

**Comment by karthink** [comment]
Tried to fix it, please update.

**Comment by wlauppe** [comment]
that, was fast, 
seems to be fixed now, thanks 👍
