### ISSUE TITLE
ChatGPT error: (HTTP/2 404) The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by jkozak** [karthink/gptel#44]
Get this when `gpt-4` selected as model using version `20230413.602` - the two 3.5 versions seem fine.

**Comment by karthink** [comment]
This suggests your account doesn't have access to GPT-4 yet (see the end of #43). There's a waitlist for GPT-4 API access right now.

If you can access GPT-4 using a different client or on the web, it's a bug with gptel.

**Comment by spenczar** [comment]
I'm able to access GPT-4 through the ChatGPT web interface (https://chat.openai.com/), but not through gptel. When I curl the OpenAI APIs to list models, I don't see gpt-4. API access is probably independent of the web access.

**Comment by karthink** [comment]
> API access is probably independent of the web access.

Looks like it. There's a waitlist for GPT-4 API access: https://openai.com/waitlist/gpt-4-api

**Comment by jkozak** [comment]
Yes, that's it.  Apologies for taking your time.
