### ISSUE TITLE
gptel-send when called on region in prog-mode buffers should output response to other buffer

### ISSUE THREAD

**Issue by nordlow** [karthink/gptel#446]
`M-x gptel-send` when mark is active in a code buffer should adhere to the Emacs DWIM principle, meaning it should output the response into another buffer instead of the current behavior that outputs typically non-working code or English text the resulting in a syntactically incorrect code modification.

The solution could branch on the whether the current major-mode inherits from `prog-mode` and output the result in another buffer or directly in the minibuffer.

**Comment by karthink** [comment]
> the current behavior that outputs typically non-working code or English text the resulting in a syntactically incorrect code modification.

Perhaps this is the problem.  You can ask it to output code and only code in the system message, and it will generally do so.  One of the default `gptel-directives` includes this, and you can set it for the buffer.  That said, you'll probably want to write a system message with more instructions.

> Emacs DWIM principle, meaning it should output the response into another buffer

I'm not seeing what's DWIM about this behavior.  "What I Mean" can be anything here -- In a `prog-mode` buffer, I might want
- the LLM to generate only code, OR 
- to generate text but wrap it in a code comment, OR
- to rewrite/refactor the code in the active region, OR
- to generate text but reply in another buffer.

All of these (and more) seem like equally valid "DWIM" behaviors to me.

You can do the first and last using gptel's transient menu.  To wrap text in a code comment in the `prog-mode` buffer you can use the hook `gptel-post-response-functions`.  To rewrite/refactor the code you can use the "in-place output" option in the transient menu, or use the refactor interface (also in the transient menu).

**Comment by nordlow** [comment]
I guess it all comes down to what instructions you feed it.

I guess it would be very useful to have gtpel insert code in the same language as that major-mode represents as real code and anything else as comments.

**Comment by karthink** [comment]
> I guess it would be very useful to have gtpel insert code in the same language as that major-mode represents as real code and anything else as comments.

It's rarely enough to specify that the response has to be code in language FOO.  Typically you are looking to provide many more task-specific instructions.  You can craft a system message with the requisite details and save it as an element of `gptel-directives`.  When using gptel you can switch the system message to this preset and send your request.

The "add directive" `d` option in the transient menu can be used to add a one-time instruction on top of the more general system message.
