### ISSUE TITLE
Improve functionality of context handling

### ISSUE THREAD

**Issue by osheari1** [karthink/gptel#453]
There seems to be a few areas of improvement with context handling
* [Enhancement] There isn't any functionality to remove full context sets (files, buffers, regions, ect). It would be useful to add and remove different contexts.
![image](https://github.com/user-attachments/assets/15bb3bca-ead8-4416-ad65-af78558a5038)
* [Enhancement] Contexts also seem to persist across different buffers / chat sessions. For example, when I have 2 chats open, the contexts will be shared across both even if they are totally unrelated. I have to restart emacs to clear it.
![image](https://github.com/user-attachments/assets/ab1d1b1b-eb91-49a2-a921-4bfb9298891e)
![image](https://github.com/user-attachments/assets/e964dc71-7ca7-4188-84f7-9dab9fd950a6)
* [Enhancement] Context keybindings don't work when evil is enabled (ofc this can be manally fixed). 

Potential solutions:
* Add functions to remove particular context sets (from Inspect buffer?) and clear the whole context set (from transient menu). 
* If we have the functionality to clear / update contexts, this isn't as big of an issue, as the contexts can be cleaned up across projects / buffers.
* Update the keybindings to handle evil mode.

**Comment by karthink** [comment]
> Add functions to remove particular context sets (from Inspect buffer?) and clear the whole context set (from transient menu).

To remove particular context sets you can

- use the context inspection buffer (`C` in the menu)
- run `gptel-add` in a region/buffer that is part of the context, it will be removed instead.

> when I have 2 chats open, the contexts will be shared across both even if they are totally unrelated.

Context is global by design.  It's not clear how you can indicate different context lists per chat buffer to the user in a way that's not very confusing.  Context is also independent of gptel buffers because you can use gptel-send anywhere -- for example, you can include context when doing some refactoring in a project.  If the context were made buffer-local, you would have to repeatedly add regions/buffers/files to the buffer-local context in each project buffer you want to use gptel in.

> I have to restart emacs to clear it.

As mentioned above, you can clear it from the context inspection buffer or by running `gptel-add` again.  You don't need to restart Emacs.

> Context keybindings don't work when evil is enabled (ofc this can be manally fixed).

Transient's keymap should override evil-mode here, not sure what's happening.

**Comment by osheari1** [comment]
> To remove particular context sets you can
>
>    use the context inspection buffer (C in the menu)
>    run gptel-add in a region/buffer that is part of the context, it will be removed instead.
Ok got it thanks. I tested this out at bit and it seems to work in some situations but not others.

It works when you are removing the context by calling `gptel-context-add` on the context region in the buffer itself, but it doesn't work when removing from the context Inspector.

Examples:
**Adding a specific region in the currently selected buffer and removing with function directly from buffer**
Highlight region in buffer
![image](https://github.com/user-attachments/assets/f1598e6e-116d-4e77-bca9-8a021c6b6b93)

in transient menu, run `-r`
![image](https://github.com/user-attachments/assets/e16a741e-f394-4a63-b4d6-3722aa390263)

run `gptel-context-add` on selected region (NOT via the context menu)
![image](https://github.com/user-attachments/assets/30a56fc3-99ef-4e25-99d3-fd432de99788)


**Adding a context file from transient menu and removing from inspector**
In transient menu, select file `-f`
![image](https://github.com/user-attachments/assets/b470e253-5931-4d5f-94c2-7739d00c4931)

Attempt to remove file from context menu
![image](https://github.com/user-attachments/assets/e491147a-3754-4eae-8c2b-aa3909bcbea0)
![image](https://github.com/user-attachments/assets/a0b4f505-b22a-4712-a7a9-b38fc001c1e3)

Results after removing
![image](https://github.com/user-attachments/assets/a2f5483e-dca4-418d-8ebf-f4f1b360a467)

(From inspecting the payload)
![image](https://github.com/user-attachments/assets/b559d6a3-4b3e-4024-b9ff-cf3d49df3cd6)




> Context is global by design. It's not clear how you can indicate different context lists per chat buffer to the user in a way that's not very confusing.

Yeah this makes sense. Not an issue when you can update the context anyway

> Transient's keymap should override evil-mode here, not sure what's happening.
I'll look into this and submit a PR if I can find anything. Do you know where in the code is this configured?

**Comment by karthink** [comment]
In the context inspection buffer, you can delete chunks from the context with `d`, and move around with `n` and `p` -- these are the same keybindings as in Dired, buffer-menu, ibuffer etc.  The header line explains this:

![image](https://github.com/user-attachments/assets/03868f19-0432-42ff-ada1-58a44dbed05d)

I misunderstood what you meant about `evil-mode`, I thought the keys in the transient menu (like `-b` and `-f`) don't work.

The context inspection buffer does not support evil-mode keybindings, yes.  You can switch to Emacs mode in this buffer or add the keybindings to your config.

**Comment by ultronozm** [comment]
@osheari1 since you ask about having "per-chat context", it might be worth taking a look at how context is handled in https://github.com/ultronozm/ai-org-chat.el (which uses gptel as a backend, so should hopefully be simple to try out)

**Comment by osheari1** [comment]
Ok cool. This is working thanks :+1:
