### ISSUE TITLE
Error (use-package): gptel/:config: Symbol’s function definition is void: gptel-make-ollama

### ISSUE THREAD

**Issue by k4r4b3y** [karthink/gptel#468]
**Briefly describe what you are trying to do**
I clone the gptel repo to ~/.local/gits/emacs/ directory.  In my emacs, I have the following use-package declaration for loading up the gptel upon emacs' startup:
```
(use-package gptel
  :if (file-exists-p "~/.local/gits/emacs/gptel")
  :load-path "~/.local/gits/emacs/gptel"
  :config
  (setq gptel-model 'mistral-small:latest)
  (setq gptel-backend (gptel-make-ollama "Ollama"
					 :host "localhost:11434"
					 :stream t
					 :models '(mistral-small:latest))))
```
However, when emacs starts, I get the error:
```
Error (use-package): gptel/:config: Symbol’s function definition is void: gptel-make-ollama
```
I can see the 'M-x gptel' and its other command space there in the minibuffer menu.  But the gptel-make-ollama is absent.  When I check the cloned repo's files on my disk, I can locate the gptel-make-ollama function declaration, it seems to be marked for autolading, but it seems like I am unable to trigger its autoload?

**Additional context**
Emacs version: 29.4 (installed from debian bookworm-backports)
Operating system: Debian 12 (bookworm)

**Comment by karthink** [comment]
> I clone the gptel repo to ~/.local/gits/emacs/ directory.

This isn't enough, you have to install the package with `M-x package-install-file`.  (Give it the gptel directory)

Please see the manual install instructions in the README.

**Comment by k4r4b3y** [comment]
> This isn't enough, you have to install the package with M-x package-install-file.

Why is this special with gptel?  Other emacs packages that I use, like denote, allow using it from use-package load-path declarations.

**Comment by k4r4b3y** [comment]
>  You should install denote this way too, with M-x package-install-file.
[Here](https://protesilaos.com/emacs/denote#h:d397712c-c8c0-4cfa-ad1a-ef28cf78d1f0), in Manual Installtion header, Prot recommends simply cloning his denote repo, and adding the following line to the init.el file:
```
;; Make Elisp files in that directory available to the user.
(add-to-list 'load-path "~/.emacs.d/manual-packages/denote")
```
Isn't this the "same" as I doing with use-package and :load-path declarations?  Prot doesn't seem to be recommending the use of `M-x package-install-file`, yet his denote repo also has multiple .el files.

**Comment by karthink** [comment]
> [Here](https://protesilaos.com/emacs/denote#h:d397712c-c8c0-4cfa-ad1a-ef28cf78d1f0), in Manual Installtion header, Prot recommends simply cloning his denote repo, and adding the following line to the init.el file:
> 
> ```
> ;; Make Elisp files in that directory available to the user.
> (add-to-list 'load-path "~/.emacs.d/manual-packages/denote")
> ```
> 
> Isn't this the "same" as I doing with use-package and :load-path declarations? Prot doesn't seem to be recommending the use of `M-x package-install-file`, yet his denote repo also has multiple .el files.

It's not the same.  None of the autoloads in the denote package (in any file) are available, not even the ones in `denote.el`, and autoloading is not being used at all.  If you have a use-package block for denote like

```elisp
(use-package denote
  :config
  ...)
```

then only the commands in `denote.el` itself are available.  Unless you also run `(require 'denote-sort)` or `(use-package denote-sort)`, you can't actually access `denote-sort-files` or `denote-sort-dired`, which are autoloaded in `denote-sort.el`.  Ditto with all the other files in the denote repo besides `denote.el`.

The Denote manual should either specify that you need to explicitly `(require 'denote-sort)` to access `denote-sort-*`, or ask you to install the package properly so all available autoloads can be generated and loaded.

See `(info "(elisp) Autoload")` for how autoloading works.
