### ISSUE TITLE
buffers visiting context files modified externally prompt user for auto-revert confirmation

### ISSUE THREAD

**Issue by benthamite** [karthink/gptel#479]
### Please update gptel first -- errors are often fixed by the time they're reported.

- [X] I have updated gptel to the latest commit and tested that the issue still exists

### Bug Description

If any of the files that are part of the gptel context are modified externally and `global-auto-revert` is enabled, the user will be prompted to decide whether the buffer visiting that file should re-read it (`"<file> changed on disk. Reread from disk?"`). This behavior is quite disruptive if one is regularly modifying a file externally, e.g. in response to LLM suggestions.

I see that [this comment](https://github.com/karthink/gptel/pull/256#issuecomment-2094322963) mentions `auto-revert-handler` in the context of a discussion of the context functionality, so maybe this is related?

### Steps to Reproduce

1. Enable `global-auto-revert`.
2. Add a file to the context.
3. With an external editor, open, change and save the file.
4. Voilà.

**Comment by karthink** [comment]
Thank you for the report @benthamite.  I cannot reproduce this using your provided steps, both with and without the file open in Emacs.

I'm also not sure there's any reason adding a file to gptel's context should matter -- gptel does not touch the file until you open the context inspection buffer or send the request, neither of which are part of your reproduction steps.  I also tried it with the context inspection buffer open, and by sending the file in a gptel request after modifying it externally.  Emacs does not prompt me.

**Comment by benthamite** [comment]
Thanks for the quick reply. To be clear: what appears to be triggering the issue is merely adding the file to the gptel context via `gptel-context-add` with point on that file in Dired, not interacting with the inspection buffer.

If you can’t reproduce the issue after this clarification, there might be something peculiar to my setup triggering the issue.

**Comment by karthink** [comment]
> To be clear: what appears to be triggering the issue is merely adding the file to the gptel context via gptel-context-add with point on that file in Dired

Can you break it down further for me?  What is the ordering of editing the file externally and running `gptel-context-add`?

**Comment by benthamite** [comment]
I just tried a minimal config and the issue did not arise. Let me take a closer look and I’ll report back.

**Comment by karthink** [comment]
I can make a guess as to what's happening:

1. You have `auto-revert-mode` turned on in dired (since the mode is global)
2. You edit a file externally.  Now the dired buffer is "out of date".
3. Before the dired buffer can auto-revert, you run `gptel-context-add`.  (auto-reverting runs on a timer)
4. Dired recognizes that the file name being asked for by `gptel-context-add` is out of date, and asks for confirmation to revert.

Note that gptel does not read the file at the time you run `gptel-context-add`, it just makes a note of the file path.  So this warning is primarily about the file's metadata being out of date, issued by dired.

That's my best guess.

**Comment by benthamite** [comment]
That is a clever guess, but it turns out to be incorrect. What was happening is that the call to [a function](https://github.com/benthamite/dotfiles/blob/master/emacs/extras/gptel-extras.el#L93) I use to calculate the cost of the request was visiting all the context files (in order for them to be included in the cost calculation) and this was triggering the auto-revert issue. It did not occur to think about this when filing the bug report, though perhaps I should have.

Sorry for the false report.
