### ISSUE TITLE
OpenRouter error: (HTTP/2 400) Input required: specify "prompt" or "messages"

### ISSUE THREAD

**Issue by xoich** [karthink/gptel#480]
### Please update gptel first -- errors are often fixed by the time they're reported.

- [X] I have updated gptel to the latest commit and tested that the issue still exists

### Bug Description

whatever you do with OpenRouter it returns the error: (HTTP/2 400) Input required: specify "prompt" or "messages"

### Backend

Other (please specify in Additional Context)

### Steps to Reproduce

It happens when you use gptel in any way

### Additional Context

config:

(setq gptel-model   'google/gemini-exp-1121:free
	gptel-backend
	(gptel-make-openai "OpenRouter"               ;Any name you want
          :host "openrouter.ai"
          :endpoint "/api/v1/chat/completions"
          :stream t
          :key (lambda () 
		 (with-temp-buffer
		   (insert-file-contents "~/.openrouter")
		   (buffer-string)))
          :models '(google/gemini-exp-1121:free
		    meta-llama/llama-3.2-3b-instruct:free)))

### Log Information

```json
{
  "model": "meta-llama/llama-3.2-3b-instruct:free",
  "messages": [
    {
      "role": "system",
      "content": "You are a large language model living in Emacs and a helpful assistant. Respond concisely."
    },
    {
      "role": "user",
      "content": "hi"
    }
  ],
  "stream": true,
  "temperature": 1.0
}
{
  "gptel": "response body",
  "timestamp": "2024-11-23 11:00:56"
}
{
  "error": {
    "message": "Input required: specify \"prompt\" or \"messages\"",
    "code": 400
  }
}
```

**Comment by karthink** [comment]
@xoich Glad you figured it out.  I've made it so gptel will strip trailing newlines from API keys before sending them, hopefully avoiding this problem in the future.
