### ISSUE TITLE
Jump to file from context buffer not working.

### ISSUE THREAD

**Issue by metachip** [karthink/gptel#482]
### Please update gptel first -- errors are often fixed by the time they're reported.

- [X] I have updated gptel to the latest commit and tested that the issue still exists

### Bug Description

Jump to file from context buffer not working. This appears to work for buffers and regions, but not files. 

### Backend

None

### Steps to Reproduce

When I add a file to context, and then try to jump to the file from the context window, an error occurs. 

The reported error is

funcall-interactively: Wrong type argument: overlayp, "~/Downloads/Roadmap-V1.png"

### Additional Context

Emacs 28.2

### Backtrace

```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument overlayp nil)
  gptel-context-visit()
  funcall-interactively(gptel-context-visit)
  command-execute(gptel-context-visit)
```

**Comment by metachip** [comment]
Another minor problem likely to be in the same part of the source code: The gptel-context buffer is not updated when context is deleted. That is, when context is deleted using =d= and =C-c C-c= the context buffer is not updated. The deleted context is still shown. The context buffer only appears to be updated when =gptel-add= or =gptel-add-file= is used. Doing a manual update =g= in the context also updates the context buffer.

**Comment by karthink** [comment]
Then I don't understand this:

> That is, when context is deleted using =d= and =C-c C-c= the context buffer is not updated

After `C-c C-c` the context buffer goes away.  So what do you mean by "it's not updated"?

**Comment by metachip** [comment]
Not if it's open in two windows or one (re)selects it without adding anything else to it. It still exists, with stale data. Not a major problem, but confusing.

**Comment by karthink** [comment]
Got it, thanks for reporting this too.  I'll fix both bugs when I can.

**Comment by metachip** [comment]
Both bugs appear to be fixed. Thank you!

There appears to remain some stateful problems with the context buffer though.

Reproduce: open the content buffer in a separate window. Add context to it and that buffer will not update. This looks very similar to the problem you just fixed, where the buffer was not updated when items were deleted from it. It's also not updated when context is added to it.

However, when you reopen/revisit context via the gptel menu C command context is correctly updated. That is, updates occur on view events not when the context is changed.

Given the modus operandi for the system at the moment, where the presumption seems to be that the context buffer is only shown upon gptel view events, and hidden again automatically based on actions taken via the gptel events, one normally wouldn't see this problem.

However, if context buffers become things one manages in multiplicity and explicitly in future ([as I would suggest](https://github.com/karthink/gptel/issues/475#issuecomment-2495853089)), their update should be synchronized to events that actually add or remove context, and not upon events related to viewing of context buffers.

That is, the context buffer should always reflect the correct context state given the most recent modifications made to the context, regardless of whether the context buffer(s) is(are) visible or not.

**Comment by karthink** [comment]
> Reproduce: open the content buffer in a separate window. Add context to it and that buffer will not update. This looks very similar to the problem you just fixed, where the buffer was not updated when items were deleted from it. It's also not updated when context is added to it.

This is how other listings like buffer-menu, ibuffer and dired work -- you have to refresh the display with `g`.  This can be addressed but I think this can wait until the design is worked on more -- the fix to automate this won't work with having multiple context lists (as you suggest in #475.)

**Comment by metachip** [comment]
> This is how other listings like buffer-menu, ibuffer and dired work -- you have to refresh the display with `g`.

Fair enough, hitting `g` is easy enough.

**Comment by metachip** [comment]
I consider this bug (jump from context) close with thanks.
