### ISSUE TITLE
GPT4All: Unrecognized request argument supplied: max_completion_tokens

### ISSUE THREAD

**Issue by novacellus** [karthink/gptel#485]
### Please update gptel first -- errors are often fixed by the time they're reported.

- [X] I have updated gptel to the latest commit and tested that the issue still exists

### Bug Description

Calling `gptel-rewrite-menu` with GPT4All backend yields:
```
GPT4All error: (HTTP/1.1 400 Bad Request) Unrecognized request argument supplied: max_completion_tokens
LLM response error: ((HTTP/1.1 400 Bad Request) invalid_request_error) Unrecognized request argument supplied: max_completion_tokens. Rewrite/refactor in buffer paper.org canceled.
```

### Backend

Other (please specify in Additional Context)

### Steps to Reproduce

1. Mark a textline.
2. Call `gptel-rewrite-menu`.
3. Choose `r`.

### Additional Context

I run Emacs 29.4 on Kubuntu 24.10 with GPT4All v3.4.2.

My config worked just fine before upgrading to the last version:
```
(use-package! gptel
:config
(setq
    gptel-max-tokens 500
    gptel-model 'mistral-7b-openorca.Q4_0.gguf
    gptel-backend
    (gptel-make-gpt4all "GPT4All"
        :protocol "http"
        :host "localhost:4891"
        :models '(mistral-7b-openorca.Q4_0.gguf Llama-3.2-3B-Instruct-Q4_0.gguf)
        ) ))
```
From what I gather this may have to do with the [commit bcbbe67](https://github.com/karthink/gptel/commit/bcbbe67e08d423884c2554c95b91d5f0f9b833e3#diff-b0ccd6168b36cfd4e20d1f92f47666071dc7d81b0299b7251b8efeb59dd1eb53R145) where the `max_tokens` was changed to `max_completion_tokens`.

**Comment by karthink** [comment]
Thanks for report @novacellus.  Should be fixed for now.  A better solution might be needed in the future as the OpenAI API drifts further away from GPT4All and other OpenAI-compatible ones.

**Comment by novacellus** [comment]
This fix seems to resolve the issue, thank you!
