### ISSUE TITLE
Quick Context Suspension and Deletion

### ISSUE THREAD

**Issue by metachip** [karthink/gptel#486]
Two (simple?) enhancement requests or perhaps questions about features I've not yet discovered:

1) **Context Deletion**: In light of the recent discussions about the management of [multi-modal](https://github.com/karthink/gptel/issues/459) and [per-buffer](https://github.com/karthink/gptel/issues/475) context, an interim and relatively easy solution that would improve my workflow might be be to provide a simple command, or an action from the transient menu, that allows me to entirely delete the prevailing context. This would avoid the need to to open the context buffer manually, select each item within it, and then delete them.
   
2) **Context Active**: Is there a way to **ignore** a (non-empty) context buffer conveniently. If I'm undertaking a series of queries that require context, and then I need to "jump left" to make a few queries that don't, before returning back to my main series of queries that require the context again, can I do this without having to delete and then reconstruct the context buffer? That is, analogous to how `gptel-track-media` works now, but for the context buffer.

[2024-11-27 Wed 11:17]

**Comment by karthink** [comment]
**Context deletion**: The context is stored in `gptel-context--alist`, so it's easy to delete it.  We just have to be sure to remove the overlays we've placed in other buffers.

```elisp
(defun gptel-context-remove-all ()
  (interactive)
  (cl-loop for (source . ovs) in gptel-context--alist
           if (bufferp source) do
           (mapc #'gptel-context-remove ovs)
           else do (gptel-context-remove source)
           finally do (setq gptel-context--alist nil)))
```

**Context ignore**: This is built-in.  It's the `-i` `include context` option in the transient menu.  You can set it to "no".  There's a switch to set this just for the current buffer.

![image](https://github.com/user-attachments/assets/7676af57-31a6-4221-8856-1f5c2f93b885)

If that's too slow you can use a custom function -- it's just one variable.

```elisp
(defun gptel-context-toggle ()
  (interactive)
  (if gptel-use-context
      (progn (setq gptel-use-context nil)
             (message "gptel is now ignoring context"))
    (setq gptel-use-context 'system)
    (message "gptel is now tracking context.")))
```

You might want to modify this to set it buffer-locally (use `setq-local` instead of `setq`), so that some buffers track context and some don't.

**Comment by karthink** [comment]
To add the first command to the transient menu, you can do:

```elisp
(transient-append-suffix 'gptel-menu '(0 1 5)
  '("-D" "Remove all" gptel-context-remove-all))
```

![image](https://github.com/user-attachments/assets/2eed1e8a-372d-437f-954d-1289fc430b05)

See the documentation of `transient-append-suffix` to understand the arguments.

**Comment by metachip** [comment]
Thanks, @karthink. I have added a modified version of this to my use-package clause as follows:
```elisp
    (use-package gptel
      ;; <other configuration stuff here>
      :config
      (defun gptel-context-delete-all ()
        (interactive)
        (cl-loop for (source . ovs) in gptel-context--alist
          if (bufferp source) do
          (mapc #'gptel-context-remove ovs)
          else do (gptel-context-remove source)
          finally do (setq gptel-context--alist nil)))
      (defun gptel-context--exists-p ()
        (not (null gptel-context--alist)))
      (with-eval-after-load 'gptel-transient
        (transient-append-suffix 'gptel-menu '(0 1 5)
          `(" D" "Delete" gptel-context-delete-all :if gptel-context--exists-p))))
```
It does what you designed but it presents it as a D option which only appears in the transient menu when there is context to delete. I share this back with you to ask if this is a good stylistic way of doing it.

**Comment by karthink** [comment]
Yup that looks good to me.

However, I actually added it to the menu a few hours ago (a844612), since there was one more request for this feature in #487.  It works like your implementation does, only shows up if there's any context to clear.

**Comment by karthink** [comment]
Closing since both features (deleting and ignoring context) are now available via `gptel-menu`.  Feel free to reopen if there are related issues or bugs in the implementation.
