### ISSUE TITLE
[Ollama] Refactor doesn't include the context.

### ISSUE THREAD

**Issue by Stebalien** [karthink/gptel#493]
### Please update gptel first -- errors are often fixed by the time they're reported.

- [X] I have updated gptel to the latest commit and tested that the issue still exists

### Bug Description

When I select a region and ask GPTEL to refactor it with the ollama backend, it doesn't include the context. The request sent is:

```
{
  "model": "qwen2.5:latest",
  "messages": [
    {
      "role": "system",
      "content": "You are a go programmer.  Follow my instructions and refactor go code I provide.\n- Generate ONLY go code as output, without any explanation or markdown code fences.\n- Generate code in full, do not abbreviate or omit code.\n- Do not ask for further clarification, and make any assumptions you need to follow instructions."
    },
    {
      "role": "user",
      "content": "What is the required change?"
    },
    {
      "role": "assistant",
      "content": "Refactor: Extract all constant strings into named constants."
    }
  ],
  "stream": true,
  "options": {
    "temperature": 1.0
  }
}
```

If I instead use the openai backend, the second message includes the correct context (the selected region).

### Backend

Ollama

### Steps to Reproduce

1. Configure gptel to use the ollama backend and configure ollama.
2. Ask it to refactor a region of code.
3. Note that it doesn't actually send said region of code to ollama.

### Additional Context

Emacs version: latest master.
OS: Linux
gptel version: master

**Comment by karthink** [comment]
Thanks for catching that.  Should be fixed.

**Comment by karthink** [comment]
Also: Depending on when you last updated gptel, you might find the rewrite interface quite different, hopefully for the better.  Please let me know if the new interface is intuitive.

**Comment by Stebalien** [comment]
I've pulled the latest master and I'm really liking it.

And thanks for the quick fix!
