### ISSUE TITLE
Aborting active query

### ISSUE THREAD

**Issue by spenczar** [karthink/gptel#50]
Sometimes GPT goes running off in the wrong direction. I'd like to be able to abort it to rephrase my prompt, without waiting for it to finish chugging out junk. I'm imagining a `gpt-abort` or `gpt-cancel` which cancels any queries in the current buffer, but I'm up for whatever.

**Comment by karthink** [comment]
Added `gptel-abort` in 219e163d.  Only works when using curl (`gptel-use-curl` is non-nil, which is the default if Curl is detected in the path.)

Please test.
