### ISSUE TITLE
After provider selection, gptel opens up a split below it. 

### ISSUE THREAD

**Issue by ziova** [karthink/gptel#501]
### Please update gptel first -- errors are often fixed by the time they're reported.

- [X] I have updated gptel to the latest commit and tested that the issue still exists

### Bug Description

Not sure if this is something on my end but after i select a model. there is a split created below (this only happens after model selection). This split usually takes up another buffer that is in in the background. Is there anyway to fix this. 

### Backend

None

### Steps to Reproduce

Run gptel-menu, press -m for model selection. after selecting a model by pressing RET, there seems to be a new split open. 

### Additional Context

Emacs version: Emacs 29.6

**Comment by ziova** [comment]
Turns out the issue was not related to gptel, instead it was just a problem with Doom's handling of transient. I fixed the issue by pinning the magit package to an old commit:
`(package! transient :pin "00fabc76eb3dc75f742d8d2720c44e25e5772e8f")`

**Comment by Cbeck527** [comment]
🔍 Related doom emacs issue: https://github.com/doomemacs/doomemacs/issues/8194
