### ISSUE TITLE
Formatting multi-line prompts in gptel-mode?

### ISSUE THREAD

**Issue by jbarbero1** [karthink/gptel#507]
Hello,

I'm using gptel-mode to save and restore gptel chats. However, if a prompt spans multiple lines, the transcript becomes confusing. E.g.:

:PROPERTIES:
:GPTEL_MODEL: claude-3-5-sonnet-20241022
:GPTEL_BACKEND: Claude
:GPTEL_SYSTEM: You are a large language model and a helpful assistant. Respond without using bullet points.
:GPTEL_BOUNDS: ((277 . 532) (734 . 1804))
:END:

*** How many stars are in the Milky Way?

The Milky Way contains between 100-400 billion stars. The exact number is difficult to determine because many stars are hidden behind dust and gas clouds, and many are too dim to detect easily. The most commonly cited estimate is around 200 billion stars.

*** How many galaxies are in the observable universe?

How wide is the observable universe?

What are the best current estimates on the age of the universe? Are there discrepancies in this estimate?

The observable universe contains approximately 2 trillion galaxies (2,000,000,000,000), though this number has been revised several times as our detection methods improve. Some estimates go as low as 200 billion, while others suggest up to 2 trillion or more.

The observable universe is approximately 93 billion light-years in diameter. This might seem confusing since the universe is only about 13.8 billion years old, but this larger size is due to cosmic expansion - the space between galaxies has been stretching while light has been traveling.

Regarding the age of the universe, the current best estimate is 13.8 billion years, but there are some interesting discrepancies in this measurement known as the "Hubble tension." Different methods of measurement give slightly different results - measurements based on the cosmic microwave background suggest 13.8 billion years, while measurements based on the current expansion rate suggest a younger universe of around 12.5-13 billion years. This discrepancy is one of the most intriguing puzzles in modern cosmology.

*** 

I assume gptel keeps track of where each prompt is via GPTEL_BOUNDS. However, is there a better way to format multi-line prompts so it's clear from the transcript where the prompt ends and the LLM's reply begins?

Thank you!

**Comment by karthink** [comment]
Yes, use `gptel-prompt-prefix-alist` and `gptel-response-prefix-alist`.

``` emacs-lisp
(setf (alist-get 'org-mode gptel-prompt-prefix-alist) "@user:\n")
(setf (alist-get 'org-mode gptel-response-prefix-alist) "@llm:\n")
```

**Comment by jbarbero1** [comment]
Thank you, these are extremely helpful! I appreciate your guidance very much, as well as this awesome package you've created.
