### ISSUE TITLE
Unexpected buffer appears with transient menu

### ISSUE THREAD

**Issue by j-palms** [karthink/gptel#509]
### Please update gptel first -- errors are often fixed by the time they're reported.

- [X] I have updated gptel to the latest commit and tested that the issue still exists

### Bug Description

When using `gptel-menu` followed by `Add instruction` or `gptel-rewrite` followed by `Rewrite instruction`, an unexpected small (mini?)buffer opens alongside the transient menu after confirming the new instruction. This additional buffer contains content from a buffer that was previously in the background. This buffer persists also after closing the transient menu so that it has to be closed manually.
(This also happens for some other menu options. The above are only examples.)
### Backend

None

### Steps to Reproduce

1. Call `gptel-menu`
2. From the transient menu, select the `Add instruction` option.
3. Observe that in addition to the transient menu, a new, unrelated small buffer opens at the bottom containing content from the previously opened background buffer.
4. Close the transient menu and notice that the additional buffer remains open.
5. Repeat similar steps with `gptel-rewrite` and selecting `Rewrite instruction` to observe the same behavior.

### Additional Context

emacs version: 29.4
doom emacs version: latest
gptel version: latest
transient version: latest

**Comment by jkshum** [comment]
Experiencing the same issue, not sure it is Doom Emacs related.

**Comment by karthink** [comment]
See https://github.com/karthink/gptel/issues/501 -- appears to be a Doom Emacs issue.

@jkshum Are you not using Doom Emacs?

**Comment by jkshum** [comment]
Yes @karthink  I am using Doom EMacs.
Older gptel versions could work properly with Doom EMacs in my experience.

**Comment by j-palms** [comment]
> See #501 -- appears to be a Doom Emacs issue.
> 
Ah alright, I didn't check the closed issues...
