### ISSUE TITLE
authinfo, gpg, password store

### ISSUE THREAD

**Issue by jgarte** [karthink/gptel#51]
After following the [usage](https://github.com/karthink/gptel#usage) section I added this config:

```lisp
           (setq auth-sources '("~/.authinfo"))
           (setq auth-source-pass-filename "~/.password-store")
```

But `gptel` still prompts me for an api key.

What do you think I am missing?

**Comment by karthink** [comment]
Could you try executing (auth-source-pass-enable) before running gptel?

**Comment by aplaice** [comment]
In case somebody is lazy, like me, and also whose password-store file naming convention doesn't fit with that conventions assumed by `auth-source`, you can directly retrieve the key with:

```
(alist-get 'secret (auth-source-pass-parse-entry "KEY_FILE_WITHIN_PASSWORD_STORE_WITHOUT_EXTENSION")))
```

i.e. you would need to customize `gptel-api-key` to:

```
(lambda () (alist-get 'secret (auth-source-pass-parse-entry "KEY_FILE_WITHIN_PASSWORD_STORE_WITHOUT_EXTENSION")))
```

(You might also need `(require 'auth-source-pass)` somewhere in your init.)

(This works for me.)

<hr/>

(But if your key is in `.password-store/openai.com`, and you run:

```
(auth-source-pass-enable)
```

then everything should also work.)

<hr/>

BTW @karthink thanks for the very convenient package! :)

**Comment by karthink** [comment]
> BTW @karthink thanks for the very convenient package! :)

Glad it's useful.

**Comment by karthink** [comment]
I'm assuming this issue is resolved now. Please re-open if not.
