### ISSUE TITLE
Different default for gptel-curl-file-size-threshold on windows

### ISSUE THREAD

**Issue by AustinMooreT** [karthink/gptel#517]
On windows arguments passed to the subprocess are limited to [32,767](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa?redirectedfrom=MSDN) characters.

It took me a bit to figure out what was going wrong when chat buffers would get a little long. I'm wondering if it would be possible to detect the users platform and if it's windows set the gptel-curl-file-size-threshold a little lower? If not maybe adding something FAQ in the readme to help other folks who come across this.

**Comment by karthink** [comment]
Sure, we can do this.  I don't have access to Windows right now, could you let me know the exact size we should set the threshold to?

**Comment by AustinMooreT** [comment]
I haven't looked at the gptel source code too thoroughly yet, so I'm not sure what all gptel-curl-file-size-threshold takes into account, but if it's the whole message size in characters including the Unicode null terminator I think we should just use the windows max of 32,767, but I set mine to 30000 just to have some wiggle room around that limit and it seems to work well.

**Comment by AustinMooreT** [comment]
Sorry to spam you Christmas Eve, but I've made a pull request that I think does what we want. I'm not an elisp expert, so please scrutinize it closely. I just added an if check and expanded the docstring a little to the gptel-curl-file-size-threshold defcustom.
Happy Holidays!

**Comment by karthink** [comment]
You're a few minutes late, I just added it!

**Comment by karthink** [comment]
Actually, I like the additional docstring you added about the size limitation.  Could you rebase on master so I can merge this PR with the new docstring?

**Comment by AustinMooreT** [comment]
I don't know how to rebase, so it might take me a second to do that. But a good learning opportunity.

**Comment by karthink** [comment]
The easiest way to do it would be to change the default value from `(if (eq system-type...))` to what I used, then run `git pull --rebase master`.

**Comment by AustinMooreT** [comment]
I think I did the rebase somewhat correctly? I ended up having to force push I'm thinking it was cause my original commit still existed on my remote after the rebase, so I couldn't push but didn't want to pull it either.
