### ISSUE TITLE
Efficiently extracting name/title of the current chat 

### ISSUE THREAD

**Issue by jackmac92** [karthink/gptel#520]
**IF your feature request is related to a problem**
When using gptel in Emacs for LLM interactions, there's no automatic conversation naming feature like those found in web-based chat interfaces. This makes it harder to organize and reference past conversations compared to web clients that automatically suggest relevant names for each chat.

**Describe the solution you'd like**
An "efficient" (fast/minimal credit usage) way to create a short/filename summary of the chat.  

**Describe alternatives you've considered**
- Direct chat method: Ask gptel to suggest a name within the chat itself, then remove that naming interaction to keep the chat history clean
- Background processing: Create an Elisp function that would send the chat contents to gptel with a "suggest a name" prompt, without modifying the visible buffer
- Minibuffer interaction: Develop a way to query gptel about the current chat's content via the minibuffer, avoiding any buffer modifications

**Additional context**
typing this realized I should be able to figure out how open-webui manages this feature, but don't wanna do that spelunking quite yet unless you're considering the feature

**Comment by karthink** [comment]
You can write one-off utilities like this very easily with `gptel-request`, there's no need to add it to gptel:

```elisp
(defun gptel-rename-chat ()
  (interactive)
  (unless gptel-mode
    (user-error "This command is intended to be used in gptel chat buffers."))
  (let ((gptel-model 'gpt-4o-mini))

    (gptel-request (list nil "What is the chat content?"
                         (concat "```" (if (eq major-mode 'org-mode) "org" "markdown") "\n"
                                 (buffer-substring-no-properties (point-min) (point-max))
                                 "\n```")) ;user
      :system
      (format
       "I will provide a transcript of a chat with an LLM.  \
Suggest a short and informative name for a file to store this chat in.  \
Use the following guidelines:
- be very concise, one very short sentence at most
- no spaces, use underscores if required
- return ONLY the title, no explanation or summary
- append the extension .%s"
       (if (eq major-mode 'org-mode) "org" "md"))
      :callback
      (lambda (resp info)
        (if (stringp resp)
            (let ((buf (plist-get info :buffer)))
              (when (and (buffer-live-p buf)
                         (y-or-n-p (format "Rename buffer %s to %s? " (buffer-name) resp)))
                (with-current-buffer buf (rename-visited-file resp))))
          (message "Error(%s): did not receive a response from the LLM."
                   (plist-get info :status)))))))
```

**Comment by jackmac92** [comment]
ahh that works great! 

I did check the wiki before posting, mentioning because I think including some "batteries" would be helpful. But in any case thanks for a very helpful response!!

also Happy Holidays/Merry Chistmas!

**Comment by karthink** [comment]
Happy hollidays @jackmac92!

**Comment by karthink** [comment]
FWIW, I [added this example to the wiki](https://github.com/karthink/gptel/wiki/Defining-custom-gptel-commands#example-4-get-the-llm-to-name-your-chat-buffer-520).

**Comment by petergaultney** [comment]
for anybody else who runs into issues with the above snippet for `gptel-rename-chat`, I was on gptel-0.8.0 and it did not work. I had to upgrade.

**Comment by blahgeek** [comment]
FYI: personally I am using a different approach: in the system prompt, ask the LLM to summarize the title at the end of the response, so that no extra LLM request is required.

```elisp
    (setq gptel-directives
     '((default . "You are a large language model and a professional programmer.

A special requirement: at the end of the first response, always summarize the conversation into a very short title and output it surrounded by <summarized_title>.
For example, if the user asks about the usage of asyncio in python, add <summarized_title>python-asyncio-usage</summarized_title> at the end.
Only output the summarized title once. If it already present in the conversation history, don't output it again.

")))

    (defun my/gptel-rename-buffer-from-title (beg end)
      "Parse <summarized_title>...</summarized_title> from the LLM response and rename buffer."
      (save-excursion
        (goto-char beg)
        (when (re-search-forward "<summarized_title>\\([^<]+\\)</summarized_title>" end t)
          (let ((title (match-string 1)))
            (rename-buffer (format "*gptel*<%s>" (string-trim title)) t)))))

    (add-hook 'gptel-post-response-functions #'my/gptel-rename-buffer-from-title)

```
