### ISSUE TITLE
User should get freedom to use any IP address, and compatible endpoints

### ISSUE THREAD

**Issue by gnusupport** [karthink/gptel#524]
I am on LAN, and we do not necessarily use localhost, there shall be option, easy to set, for user to use any IP address or any host, and type of the prompt, or OpenAI compatible prompt, for example.

Otherwise I cannot use gptel for locally running LLM.

If it is ollama or llamafile or llama.cpp, it does not matter for gptel, those are not endpoints but software running it.

**Comment by karthink** [comment]
@gnusupport I don't understand, please provide more context about what you're trying to do.

1. Which backend/API are you trying to use?
2. What is the relevant gptel configuration you have?

**Comment by gnusupport** [comment]
Endpoint is OpenAI compatible, so far I know. I am using:

- llamafile
- llama.cpp, now mostly llama.cpp as it has nice web interface

Both of them run with the same endpoint. 

In my particular case it is:
http://192.168.188.140:8080/v1/chat/completions

So the user should be able to set any IP address, as software could run on any computer, not so? IP address or host, plus the end point, plus the port.

I think that is something very important for us who run it locally. 

I am about to delete ChatGPT fully from my space and environment, my needs are satisfied with fully free software and data sets, like Qwen, Phi-3.5 (imagine from Microsoft), Mistral, and similar.

**Comment by karthink** [comment]
Please see the llama.cpp/llamafile setup section of the README.   It specifies how to set the host, endpoint and port to whatever you want.

**Comment by gnusupport** [comment]
In the README.org in the repository I see nothing. I see heading, though it is empty. There is no README in the package.

**Comment by karthink** [comment]
1. The entire README.org is empty?
2. Are you trying to see it in a web browser on this website, or have you opened README.org in Emacs?

**Comment by gnusupport** [comment]
I have opened it on Github

**Comment by karthink** [comment]
> I see heading, though it is empty. 

You can click on the heading to open it.

**Comment by gnusupport** [comment]
It doesn't open, it seems empty. I am now cloning.

**Comment by karthink** [comment]
Then you can find the instructions in the README.org file after opening it in Emacs.

**Comment by gnusupport** [comment]
Thanks, I  got it now.
