### ISSUE TITLE
Concurrent responses from different LLMs sometimes get mixed up

### ISSUE THREAD

**Issue by jbarbero1** [karthink/gptel#525]
### Please update gptel first -- errors are often fixed by the time they're reported.

- [X] I have updated gptel to the latest commit and tested that the issue still exists

### Bug Description

Hi, I mentioned this bug yesterday but since it recurred, I wanted to open a bug again. Sometimes gptel requests in different buffers cause the input to become interleaved or duplicated. For example:

Buffer A:
Model A response line 1
Model B response line 1
Model A response line 2
Model A response line 3

Buffer B:
Model B response line 1
Model A response line 3
Model B response line 2

etc.

I've set (setq gptel-log-level 'debug) and am running concurrent requests. This doesn't always happen, but once it occurs again I will paste my gptel-log buffer. Thank you!

### Backend

None

### Steps to Reproduce

1. Open gptel-mode with two models in two different buffers
2. Send requests concurrently
3. Observe that responses from the two LLMs sometimes get interleaved with each other

### Additional Context

Emacs 29.4
macOS

**Comment by jbarbero1** [comment]
[gptel-mixup-claude.org.txt](https://github.com/user-attachments/files/18264548/gptel-mixup-claude.org.txt)
[gptel-mixup-gemini.org.txt](https://github.com/user-attachments/files/18264549/gptel-mixup-gemini.org.txt)
[gptel-mixup-log.txt](https://github.com/user-attachments/files/18264572/gptel-mixup-log.txt)

init.el:

`
(use-package gptel
  :ensure t
  :config
  (require 'gptel-anthropic)
  ;; (require 'gptel-context)
  (require 'gptel-curl)  
  (require 'gptel-gemini)
  (require 'gptel-kagi)
  (require 'gptel-ollama)
  (require 'gptel-openai)
  (require 'gptel-org)
  (require 'gptel-privategpt)
  (require 'gptel-rewrite)
  (require 'gptel-transient)

  (setf (alist-get 'org-mode gptel-prompt-prefix-alist) "* User\n\n")
  (setf (alist-get 'org-mode gptel-response-prefix-alist) "* Assistant\n\n")

  ;; ChatGPT
  (setq gptel-api-key "OPENAI_KEY")

  ;; Claude
  (gptel-make-anthropic "Claude"          ;Any name you want
    :stream t                             ;Streaming responses
    :key "CLAUDE_KEY")

  ;; Gemini
  (gptel-make-gemini "Gemini" :key "GEMINI_KEY" :stream t)
  (setq gptel-default-mode 'org-mode))
`

**Comment by jbarbero1** [comment]
Above is a repro with both chat buffers and the debug log.

The first set of responses from each LLM are distinct.

The second set of responses are interleaved.

One thing that was different between the two is that in the first set of requests one model started streaming a response before I could send the other request. In the second set, I sent the request to the second model while the first was still in the Waiting state. Not sure if that's the reason but this happens to me pretty consistently.

**Comment by karthink** [comment]
Wow!  This is a very interesting bug.  The process handlers are completely separated so I'm very curious about how this is happening.  This is going to bother me until I figure it out.

Thanks for the logs, I'll look into it.

**Comment by karthink** [comment]
Okay, I have one suggestion already: could you try to reproduce these mixups in two markdown buffers instead of Org?

**Comment by jbarbero1** [comment]
I haven't been able to reproduce it in markdown buffers. No guarantees but I did the same for ~10 prompts and no repro.

The results subjectively feel like they are streamed differently, in smaller chunks, compared to org-mode. Not sure if I'm just imagining.

**Comment by karthink** [comment]
> I haven't been able to reproduce it in markdown buffers. No guarantees but I did the same for ~10 prompts and no repro.

Thanks.  I tried too, and couldn't reproduce it in Markdown, so I think I'm on the right track here.

> The results subjectively feel like they are streamed differently, in smaller chunks, compared to org-mode. Not sure if I'm just imagining.

You're not imagining this, although the difference isn't much, maybe 20% larger chunks on average.  gptel does Markdown to Org conversion live, while the text is streaming in.  This requires holding on to some chunks for longer to have the context required to make the required transformations.

**Comment by karthink** [comment]
I pushed a fix, please test in Org buffers like in your original tests.

**Comment by jbarbero1** [comment]
I updated with package-refresh-contents and package-upgrade of gptel, and I was only able to get version 20241226.1901.

It still happened in Org buffers.

[gptel-mixup-gemini.org.txt](https://github.com/user-attachments/files/18264961/gptel-mixup-gemini.org.txt)
[gptel-mixup-claude.org.txt](https://github.com/user-attachments/files/18264962/gptel-mixup-claude.org.txt)
[gptel-mixup-latest-log.txt](https://github.com/user-attachments/files/18264963/gptel-mixup-latest-log.txt)

Now I upgraded to 20241228.415, will try again.

**Comment by jbarbero1** [comment]
With 20241228.415, I get: 

error in process filter: Selecting deleted buffer

And the output is truncated.

**Comment by karthink** [comment]
1. `M-x toggle-debug-on-error`
2. Produce the error
3. Paste the backtrace here.

**Comment by jbarbero1** [comment]
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  #f(compiled-function (str) #<bytecode -0xbfbaf95956caad5>)(" have been relaxed, and initiatives have been laun...")
  gptel-curl--stream-insert-response(" have been relaxed, and initiatives have been laun..." (:token "c295f930b09f13b96b54bdf7e99a788d" :backend #s(gptel-gemini :name "Gemini" :host "generativelanguage.googleapis.com" :header nil :protocol "https" :stream t :endpoint "/v1beta/models" :key "GEMINI_KEY" :models (gemini-1.5-pro-latest gemini-2.0-flash-exp gemini-1.5-flash gemini-1.5-flash-8b gemini-exp-1206 gemini-pro) :url #f(compiled-function () #<bytecode 0x2c3833962454e4>) :request-params nil :curl-args nil) :parser #f(compiled-function (backend info) #<bytecode 0x15ebd09147dcd8e3>) :callback gptel-curl--stream-insert-response :transformer #f(compiled-function (str) #<bytecode -0xbfbaf95956caad5>) :data (:contents [(:role "user" :parts [(:text ":PROPERTIES:\n:GPTEL_MODEL: gemini-exp-1206\n:GPTEL_...")]) (:role "model" :parts (:text "Okay, here is a 1000-word essay on the geopolitica...")) (:role "user" :parts [(:text "Great. Now please do the same for abortion rights ...")]) (:role "model" :parts (:text "OkayKey challenges and aspects of the Russia-Ukrai...")) (:role "user" :parts [(:text "Wonderful. Now let's do the same for income inequa...")]) (:role "model" :parts (:text "Okay, here's a 1000-word essay on income inequalit...")) (:role "user" :parts [(:text "Wonderful. Now let's do the same for the root caus...")]) (:role "model" :parts (:text "Okay, here is a 1000-word essay on the root causes...")) (:role "user" :parts [(:text "Fantastic job. Let's do the same for the pros and ...")]) (:role "model" :parts (:text "Okay, here's a 1000-word essay on the pros and con...")) (:role "user" :parts [(:text "Okay, great stuff. Now let's cover the root causes...")]) (:role "model" :parts (:text "\n- Individual donations\n- Corporate contributions\n...")) (:role "user" :parts [(:text "Fantastic. Now let's do the same for the root caus...")]) (:role "model" :parts (:text "Okay, here's a 1000-word essay on the root causes ...")) (:role "user" :parts [(:text "Great job. Now let's do the same for the ethical c...")]) (:role "model" :parts (:text " requirements\n- Resource constraints\n- RadiationOk...")) (:role "user" :parts [(:text "Wonderful. Now let's do the same for the rise of f...")]) (:role "model" :parts (:text "Okay, here's a 1000-word essay on the rise of far-...")) (:role "user" :parts [(:text "Great. Now let's discuss women's rights in Saudi A...")])] :safetySettings [(:category "HARM_CATEGORY_HARASSMENT" :threshold "BLOCK_NONE") (:category "HARM_CATEGORY_SEXUALLY_EXPLICIT" :threshold "BLOCK_NONE") (:category "HARM_CATEGORY_DANGEROUS_CONTENT" :threshold "BLOCK_NONE") (:category "HARM_CATEGORY_HATE_SPEECH" :threshold "BLOCK_NONE")] :system_instruction (:parts (:text "You are a large language model living in Emacs and...")) :generationConfig (:temperature 1.0)) :buffer #<buffer gptel-mixup-gemini.org> :position #<marker at 54745 in gptel-mixup-gemini.org> :stream t :http-status "200" :status "HTTP/2 200" :tracking-marker #<marker (moves after insertion) at 57472 in gptel-mixup-gemini.org>))
  gptel-curl--stream-filter(#<process gptel-curl> "     }\n      ]\n    }\n  ],\n  \"usageMetadata\": {\n   ...")

**Comment by karthink** [comment]
How did you update gptel?

**Comment by karthink** [comment]
Okay, I think I fixed that error.  Please try now.

**Comment by jbarbero1** [comment]
I still get the error message "Selected deleted buffer" but no actual mistakes with the output.

**Comment by karthink** [comment]
Are you on the latest commit?  Should be d285955

**Comment by jbarbero1** [comment]
This was on 20241228.5310

**Comment by jbarbero1** [comment]
And my bad, I still get "Selected deleted buffer" and there's truncated output as well.

**Comment by karthink** [comment]
- The latest commit is 20241228.719
-  Can you evaluate `gptel-org.el` manually after updating and try?

**Comment by jbarbero1** [comment]
On commit 20241229.458 I still get "Selected deleted buffer" and truncated output. 

Next I evaluated gptel-org.el manually and this time I got this error:

﻿gptel-curl-get-response: Wrong number of arguments: ((t) (start-marker) "Return a Markdown to Org converter.

This function parses a stream of Markdown text to Org
continuously when it is called with successive chunks of the
text stream.

START-MARKER is used to identify the corresponding process when
cleaning up after." (let* ((in-src-block nil) (temp-buf (generate-new-buffer " *gptel-temp*" t)) (start-pt (make-marker)) (ticks-total 0)) (let (cleanup-fn) (setq cleanup-fn #'(lambda (beg _) (if (and (equal beg (marker-position start-marker)) (eq (current-buffer) (marker-buffer start-marker))) (progn (if (buffer-live-p (get-buffer temp-buf)) (progn (set-marker start-pt nil) (kill-buffer temp-buf))) (remove-hook 'gptel-post-response-functions cleanup-fn))))) (add-hook 'gptel-post-response-functions cleanup-fn) #'(lambda (str) (let ((noop-p) (ticks 0)) (save-current-buffer (set-buffer (get-buffer temp-buf)) (save-excursion (goto-char (point-max)) (insert str)) (if (marker-position start-pt) (progn (goto-char start-pt))) (if in-src-block (progn (setq ticks ticks-total))) (save-excursion (while (re-search-forward "`\\|\\*\\{1,2\\}\\|_\\|^#+" nil t) (let* (...) (cond ... ... ... ... ...)))) (if noop-p (buffer-substring (point) start-pt) (prog1 (buffer-substring (point) (point-max)) (set-marker start-pt (point-max)))))))))), 0

Next, I restarted emacs. The problem hasn't recurred, but I don't know for sure from that whether it's really fixed, because it wasn't a problem that happened on every request. Still, looking good so far!

**Comment by karthink** [comment]
> Next I evaluated gptel-org.el manually and this time I got this error:
> 
> ﻿gptel-curl-get-response: Wrong number of arguments: ((t) (start-marker) "Return a Markdown to Org converter.

When you update gptel, the files need to be re-byte-compiled, otherwise it can end up in a mixed/inconsistent state like the above.  If you use a package manager it should do that automatically.

In any case I found the cause of the mix-up so I'm about 70% sure the problem is fixed -- unless there's a second, independent bug with the same effect.

Let's leave this issue open until you're confident that it's fixed.

**Comment by jbarbero1** [comment]
Yeah, I had used package-update and it's from elpa. I just manually eval'd the file as per your request. I haven't been able to repro and you think you found it, so closing for now. If I see it again, I'll re-open. Thank you!

**Comment by jbarbero1** [comment]
Just wanted to add I've been using gptel with the fix for the last few days heavily as part of my regular workflow, and the bug hasn't happened again! Thank you and happy New Year :)
