### ISSUE TITLE
gptel-extensions.el

### ISSUE THREAD

**Issue by kamushadenes** [karthink/gptel#65]
Hey there!

Just to drop this here in case anyone is interested.

I wanted to ask questions about my documents and decided to create this small helper to facilitate things.

https://github.com/kamushadenes/gptel-extensions.el

 I'll add new stuff as I come across ideas.

Thanks for this amazing project!

**Comment by karthink** [comment]
This is great, thanks for putting this together!

Some notes:

- Refactoring is built into gptel through the transient menu:
![2023-05-31-190759_430x188_scrot](https://user-images.githubusercontent.com/8607532/230770162-1a5a496c-ee57-4a67-9c95-d45f238544ae.png)

- `gptel` does not take an `:initial` keyword argument (`gptel-ext-send-whole-buffer`), just a positional one.

- To send the whole buffer, you can just move to the end of the buffer and call `gptel-send`, but I can see why you might want a separate function for it.

As for sending whole documents, don't you run into the token limit easily?

**Comment by kamushadenes** [comment]
Thanks! I'll take that into consideration.

For the documents I'm handling currently (blog posts), it's working great. Handling more complex stuff like embeddings is too much for my Elisp-fu, but I might eventually interface with my AI project [Chloe](https://github.com/kamushadenes/chloe)

**Comment by karthink** [comment]
Added to the README under "Extensions using GPTel"
