### ISSUE TITLE
Support BingChat ?

### ISSUE THREAD

**Issue by liar666** [karthink/gptel#66]
Would be nice to support BingChat, so that one do not need a (paid) OpenAI subscription, like:
https://github.com/xhcoding/emacs-aichat

**Comment by Ypot** [comment]
And it would be chatgpt 4.
Is it difficult?

**Comment by ahyatt** [comment]
I've contributed the `llm` package to GNU ELPA which allows using different LLMs, and should also free packages like this of the burden of doing the LLM integrations themselves.  You can see the code at https://github.com/ahyatt/llm.  BingChat isn't supported, but if anyone would like to contribute an integration, that would be nice (but you will need FSF copyright assignment before doing so).

**Comment by karthink** [comment]
> I've contributed the `llm` package to GNU ELPA which allows using different LLMs, and should also free packages like this of the burden of doing the LLM integrations themselves.

Hi Andrew, does llm enable streaming responses from APIs?  This was missing from many ChatGPT packages back when I wrote this package, and it was a fair bit of work to write a filter function that did this correctly.  I can consider depending on llm in gptel if it handles streaming.

**Comment by ahyatt** [comment]
Yess, it does handle streaming.

**Comment by karthink** [comment]
I don't plan to support bing chat in gptel's current incarnation.  However at some point gptel will move over to using llm, and if llm gets support for it gptel will too.
