### ISSUE TITLE
ai-blog.el

### ISSUE THREAD

**Issue by kamushadenes** [karthink/gptel#68]
Hey there!

Just to drop this here in case anyone is interested.

I blog with Emacs and easy-hugo, and wanted to integrated some AI-assisted helper functions to help me speed up my blogging, using gptel.

https://github.com/kamushadenes/ai-blog.el

I'll add new stuff as I come across ideas.

Thanks for this amazing project!

**Comment by karthink** [comment]
Looks good, thanks for letting us know!

**Comment by karthink** [comment]
Added to the Readme under "Extensions using GPTel".
