### ISSUE TITLE
ChatGPT error: (HTTP/2 429) You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by AbeEtan** [karthink/gptel#70]
Hello everyone,

I am getting the following error 

ChatGPT error: (HTTP/2 429) You exceeded your current quota, please check your plan and billing details.

I can use ChatGPT through the webrowser just fine.

Note: I haven't been able to run anything locally yet so I didn't even use any quota.

Please advise

**Comment by karthink** [comment]
@AbeEtan I don't think there's a free quota any more, have you added your billing details to your account at openai.com?

**Comment by Kabouik** [comment]
I haven't added any billing data to my account, and would prefer not to if I can avoid it, but like @AbeEtan, I can use ChatGPT 3.5 just fine in the web app by OpenAI, and get this same error with `gptel`.

**Comment by Kabouik** [comment]
I can confirm that setting up an account does solve this issue. Too bad, I'd love to use `gptel` more, but that makes it have a cost while the web app is still free (and inconvenient).

**Comment by PalaceChan** [comment]
yes i had to do that too after my free trial. only the (garbage) website api is free. but pay per use is extremely cheap (especially with gpt 3.5) and this package is too good not to be leveraging it for the fractions of a cent it ends up costing

**Comment by karthink** [comment]
> yes i had to do that too after my free trial. only the (garbage) website api is free. but pay per use is extremely cheap (especially with gpt 3.5) and this package is too good not to be leveraging it for the fractions of a cent it ends up costing

I have been using the ChatGPT 3.5 API for a few months now and am yet to break 2 cents on the bill.  However I share the concern about trusting OpenAI with your credit card details and about supplying them with even more data.  When using local or open-source LLMs becomes easier I'll look into adding support for them to gptel.  Right now they're (a) not as good, and (b) quite inconvenient to set up and use.
