### ISSUE TITLE
Turn `gptel--infix-model` reader into a loop selection with configurable choices.

### ISSUE THREAD

**Issue by tshu-w** [karthink/gptel#72]
I often switch `gptel-model`, but currently the reader of `gptel--infix-mode` uses `completing-read`, which requires selecting the model and pressing enter every time. I think it can be changed to cyclic selection and the candidates can be configurable. I can submit a PR, but I would like to know your thoughts.
```emacs-lisp
  (transient-define-infix gptel--infix-model ()
    "AI Model for Chat."
    :description "GPT Model: "
    :class 'transient-lisp-variable
    :variable 'gptel-model
    :key "m"
    :choices '("gpt-3.5-turbo-0301" "gpt-3.5-turbo" "gpt-4")
    :reader (lambda (prompt &rest _)
              (let ((gptel--models '("gpt-3.5-turbo-0301" "gpt-3.5-turbo" "gpt-4")))
                (nth (% (1+ (cl-position gptel-model gptel--models :test #'equal))
                        (length gptel--models)) gptel--models))))
```

**Comment by karthink** [comment]
1. Cyclic selection is built into transient (I think) as one of the infix classes, you don't need to supply a custom reader.

2. While there are only three models right now, I'm planning to add support for more in the future (such as many local LLMs and DALL-E), so cyclic selection will become cumbersome then.

My suggestion for now is to use the reader you supplied as a custom function and bind it to a key:

``` emacs-lisp
(defun gptel-model-cycle ()
  (interactive)
  (let ((gptel--models '("gpt-3.5-turbo-0301" "gpt-3.5-turbo" "gpt-4")))
    (setq-local gptel-model
                (nth (% (1+ (cl-position gptel-model gptel--models :test #'equal))
                        (length gptel--models))
                     gptel--models))))
```

I understand the problem though -- let me think about how the UI can be better for a bit.

**Comment by tshu-w** [comment]
BTW, I wonder if there is any way to select a directive and quit without press q.
