### ISSUE TITLE
How to colorize `gptel` response persistent

### ISSUE THREAD

**Issue by tshu-w** [karthink/gptel#73]
I'm using `gptel` to refine my writing. Sometimes I modify and resend responses to OpenAI to get new replies. I want to add a face to the response text so that I can realize clear text properties when resending the modified response. Otherwise, `gptel` will divide it into multiple prompts. I tried the following code but it didn't work. Any suggestions would be greatly appreciated.

```emacs-lisp
  (add-to-list 'gptel-response-filter-functions
               (defun gptel--colorize-response (content buffer)
                 (put-text-property 0 (length content) 'face 'font-lock-warning-face content)
                 content))
```

**Comment by karthink** [comment]
If I understand correctly, you want to classify a response message from ChatGPT as a user prompt.

For the purpose of (repeatedly) rewriting text, you could just use the rewrite feature built into gptel.  Select the text to be rewritten, then `gptel-menu` -> `r` -> `R`.  This should work no matter the source of the text selected (i.e. ChatGPT or you).  Is there some reason you don't want to do it this way?

**Comment by tshu-w** [comment]
> If I understand correctly, you want to classify a response message from ChatGPT as a user prompt.

Yes, this is what I need, or `gptel` consider all content as 'user' with an option, regardless of its property.

I am not using the default rewrite because I have many different directives that implement "rewriting", such as translation, paraphrasing, abbreviation, etc.

**Comment by PalaceChan** [comment]
(maybe misunderstanding but if you universal prefix arg before the rewrite can't you edit the prompt to select on of these many rewrite directives?)

**Comment by karthink** [comment]
Yes, the UI for selecting rewrite directives needs to be better. I'll try
to improve it soon.

**Comment by karthink** [comment]
> but it's not possible to select "gptel-directives" and must be manually entered, which makes it difficult to switch directives frequently.

I took a look at this, and realized the history of rewrite prompts is already saved.  You can access all previously used prompts with `M-n` and `M-p` in the minibuffer prompt. If you use `savehist-mode`, it is persisted across Emacs sessions.

**Comment by tshu-w** [comment]
Putting aside the original intention, I still want to know if there is a way to set up the face of the reply, so as to better distinguish between the original content and the reply.

**Comment by karthink** [comment]
You could try something like this:

```elisp
(defun gptel--color-response ()
  (let ((prop))
    (save-excursion
      (setq prop (text-property-search-forward 'gptel 'response t))
      (put-text-property (prop-match-beginning prop)
                         (prop-match-end prop)
                         'font-lock-face
                         'warning))))

(add-hook 'gptel-post-response-hook #'gptel--color-response t)
```
