### ISSUE TITLE
`RET` in the options menu conflicts with `org`'s DWIM

### ISSUE THREAD

**Issue by JonatanSahar** [karthink/gptel#75]
I'm getting 

> Unbound suffix: ‘<return>’ (Use ‘C-g’ to abort, ‘?’ for help) [+org/dwim-at-point]

and I'm not sure how to override this binding, since I don't understand how is the major mode set for the transient menu - why would it still be in org mode?

Thanks!

**Comment by karthink** [comment]
This has popped up before, see #40. This could be due to some quirk of `evil-mode` integration with `org`, or perhaps some Doom Emacs customization. I'm not sure how to fix this -- the workaround is to use `C-m` instead of `RET`. Does that work?

**Comment by JonatanSahar** [comment]
yes, it works, thanks!
