### ISSUE TITLE
can't access GPT-4

### ISSUE THREAD

**Issue by JonatanSahar** [karthink/gptel#79]
while I have a pro subsrcription and access gpt-4 the the web UI, I get the following through gptel :
> ChatGPT response error: ((HTTP/1.1 404 Not Found) invalid_request_error) The model: `gpt-4` does not exist

This is from gptel--debug:

> HTTP/1.1 404 Not Found
> Date: Sun, 18 Jun 2023 14:06:29 GMT
> Content-Type: application/json; charset=utf-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> vary: Origin
> x-request-id: bf975c5597ef48db9dfe1df66f9c8e23
> strict-transport-security: max-age=15724800; includeSubDomains
> CF-Cache-Status: DYNAMIC
> Server: cloudflare
> CF-RAY: 7d9417dadba809cd-HFA
> alt-svc: h3=":443"; ma=86400
> 
> {
>     "error": {
>         "message": "The model: `gpt-4` does not exist",
>         "type": "invalid_request_error",
>         "param": null,
>         "code": "model_not_found"
>     }
> }

**Comment by karthink** [comment]
GPT-4 API access is independent of web access and the pro subscription, as I understand. Please see #44, #47 and #59 for previous discussions about this.
