### ISSUE TITLE
Re-use of prompts

### ISSUE THREAD

**Issue by Ypot** [karthink/gptel#83]
Is it possible to save the prompts we send, directive included, in the kill ring? In that way, we could use them in other places.

Thanks for your exciting package!

**Comment by karthink** [comment]
It looks like this will take a bit of code to do.  I'll see about adding a hook or some other mechanism for this.

**Comment by PalaceChan** [comment]
maybe naive but am curious how is this useful @Ypot very simple to copy the current header to the kill ring but what's a use case for copying the whole content?

**Comment by Ypot** [comment]
> maybe naive but am curious how is this useful @Ypot very simple to copy the current header to the kill ring but what's a use case for copying the whole content?

For example to see how act on the same prompt other LLMs.

I thought it would be very easy...

**Comment by PalaceChan** [comment]
ah interesting, isn't the full payload with prompt a dict that's API specific though? do other LLMs generally accept similar enough payload? what would you imagine the kill ring content look like e.g.

**Comment by karthink** [comment]
> Is it possible to save the prompts we send, directive included, in the kill ring? In that way, we could use them in other places.

This is now possible.  Here is a function that does it:

```elisp
(defun gptel-copy-prompts-as-kill ()
  (interactive)
  (when-let*
      ((bounds (gptel--get-bounds))
       (prompts
        (cl-loop for (beg . end) in bounds
                 with prev-beg
                 collect (buffer-substring-no-properties (or prev-beg (point-min)) beg)
                 into prompts
                 do (setq prev-beg end)
                 finally return
                 (nconc (list gptel--system-message)
                        prompts (list (buffer-substring-no-properties end (point-max)))))))
    (kill-new (apply #'concat prompts))))
```
