### ISSUE TITLE
Customizing gptel-mode-hook example

### ISSUE THREAD

**Issue by LittleHouse75** [karthink/gptel#86]
Might someone give an example for customizing ‘gptel-mode-hook’?

I’m trying to always enter a minor mode (olivetti-mode) with gptel, and I can’t quite get the syntax right.

Thanks!!!

**Comment by karthink** [comment]
```elisp
(add-hook 'gptel-mode-hook 'olivetti-mode)
```

Does this work?

**Comment by LittleHouse75** [comment]
Couldn’t get that to work when I used it as a value for ‘gptel-mode-hook’, but worked perfectly when I added it to my init.el. Thank you!
