### ISSUE TITLE
FYI - khoj - the real OpenSource AI

### ISSUE THREAD

**Issue by OrionRandD** [karthink/gptel#87]
Have you seen this?

https://khoj.dev/about
https://github.com/khoj-ai/khoj#khoj-in-emacs-browser

Perhaps, when you have time, you can implement a gptel-like app for khoj...

**Comment by karthink** [comment]
Like most local LLM efforts, it's not quite there yet. From the about page:

> We currently use OpenAI's GPT family of Large Language Models for the chat layer. We plan to support offline models for chat soon.

And [from the README](https://github.com/khoj-ai/khoj#details),

> These notes, the last few messages and associated metadata is passed to ChatGPT along with your query for a response.

I haven't even been able to get openLlama to run on my system.  That said, I'm keeping my eyes open for progress, and plan to add support for local LLMs to gptel when it's more convenient to use them.

**Comment by OrionRandD** [comment]
"I'm keeping my eyes open for progress..." ==> thx...

**Comment by karthink** [comment]
I'm closing this now, will reopen to update when I start working on local LLM support.

**Comment by karthink** [comment]
Support for local LLMs has been added to gptel.

**Comment by nickanderson** [comment]
> Support for local LLMs has been added to gptel.

Yeah, it's really nice via ollama.

Have you looked at adding support for khoj?
