### ISSUE TITLE
error in process sentinel on Windows

### ISSUE THREAD

**Issue by daedsidog** [karthink/gptel#90]
GNU Emacs 28.2 (build 2, x86_64-w64-mingw32) of 2022-09-13

Installed from MELPA, ran `M-x gptel`, gave it my API key, the window opened, I wrote some nonsense, sent, then got the error.

```Generating autoloads for gptel-curl.el...done
Generating autoloads for gptel-pkg.el...done
Generating autoloads for gptel-transient.el...done
Generating autoloads for gptel.el...done
  INFO     Scraping files for gptel-autoloads.el...done
Wrote c:/Users/Admin/AppData/Roaming/.emacs.d/elpa/gptel-20230713.2231/gptel-autoloads.el [2 times]
Loading async...done
Package ‘gptel’ installed.
Send your query with C-c RET!
Querying ChatGPT...
error in process sentinel: gptel-curl--stream-cleanup: Search failed: "534b866860e35a4f9f2bceccece4d06a"
error in process sentinel: Search failed: "534b866860e35a4f9f2bceccece4d06a"
```

**Comment by karthink** [comment]
I'm seeing reports about such problems with curl+windows. While I figure
out how to test and debug this (no Windows access), you can set
gptel-use-curl to nil. You'll lose the streaming text capability but the
package should still work.

**Comment by daedsidog** [comment]
Setting `gpt-use-curl` to `nil` works as a workaround. Thanks.

**Comment by karthink** [comment]
I'm trying to test this. Could you run `(setq gptel--debug t)` and paste the text that pops up?

**Comment by daedsidog** [comment]
```
C:\Users\Admin>curl --version
curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN
Release-Date: 2023-03-20
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets
```

Evaluating `(setq gptel--debug t)` and then sending some message to ChatGPT results in a new `gptel-error` buffer opening with the following:
```
curl: option --compressed: the installed libcurl version doesn't support this
curl: try 'curl --help' for more information
```
