### ISSUE TITLE
migrate to TabNine 

### ISSUE THREAD

**Issue by shuxiao9058** [karthink/gptel#91]
Hi, @karthink , thanks for your awesome work.

I want to pick some code from this project to support the TabNine Chat , do you mind?

This is the TabNine repo for Emacs: https://github.com/shuxiao9058/tabnine

**Comment by karthink** [comment]
@shuxiao9058 I see that the tabnine package is MIT-licensed.  This repo is GPL3, so you can't reuse more than a few lines of code.

However I just picked GPL3 as a default, and wouldn't mind switching to MIT if you plan to reuse a large chunk. Please let me know.

Out of curiosity, what code are you planning to pick?

**Comment by shuxiao9058** [comment]
I want to use the gptel curl and gptel buffer render the chat result, and it seems that a lot codes will be picked.

**Comment by shuxiao9058** [comment]
Hi, @karthink 

The latest code of TabNine for emacs is updated, you can have a view.

**Comment by karthink** [comment]
Cool. Do you want to license tabnine as GPL3, or should I switch to the MIT license? (I would prefer for gptel to remain GPL3 licensed, but it's not a strong preference.)

**Comment by shuxiao9058** [comment]
I don't mind the license, but I will try switch the project's license from MIT to GPLv3.
