### ISSUE TITLE
How to make `*ChatGPT*` buffer auto scroll when the buffer is growing?

### ISSUE THREAD

**Issue by eval-exec** [karthink/gptel#92]
![image](https://github.com/karthink/gptel/assets/46400566/197475d9-cb54-463f-a9b0-842dfded7b4b)

For above example: when I ask ChatGPT a question, and the question is near the mode-line, then the buffer is growing, I have to scroll up to see the answer.

How can I make this buffer auto scroll up when the buffer is growing? I tried `auto-revert-tail-mode`, but it give me "This buffer is not a file".

**Comment by karthink** [comment]
This feature will break asynchronous behavior -- gptel will not move point or mess with the window in any way.

I added `gptel-pre-response-hook` (latest commit) where you can manipulate the buffer/window as required. For instance you can now do

```elisp
(add-hook 'gptel-pre-response-hook #'recenter)
```

to recenter the window before the response is inserted.  If you want more fine-grained control, you can write a custom hook function.  For example, you could move the query to the top of the window:

```elisp
(defun gptel--recenter ()
  "Move point to top of window"
  (set-window-start nil (point)))

(add-hook 'gptel-pre-response-hook #'gptel--recenter)
```

You could also add to `gptel-post-response-hook` instead, which will update the window after the response has been inserted.

**Comment by karthink** [comment]
Update: I added auto-scrolling, see the [README](https://github.com/karthink/gptel/#i-want-the-window-to-scroll-automatically-as-the-response-is-inserted). Note that this moves the cursor too, not just the window view.
