### ISSUE TITLE
[Feature request] Persist transient flags

### ISSUE THREAD

**Issue by garrett-hopper** [karthink/gptel#94]
I would like to be able to call `C-u <gptel-send>` to bring up the transient map, update some flags in it, and then from then on only need to call `gptel-send` to reuse those flags. (E.g. sending output to minibuffer, reading input from minibuffer (pre-populated with selection), sending to new or existing session)

**Comment by tshu-w** [comment]
Here is an temp solution, you can run `C-x C-s` to save infixes after modified. And run the following `gptel-transient-send` to use saved flags:
```emacs-lisp
(defun gptel-transient-send (args)
  "Call `gptel--suffix-send' with saved ARGS."
  (interactive (list (transient-args 'gptel-menu)))
  (gptel--suffix-send args))

(call-interactively 'gptel-transient-send)
```

**Comment by tshu-w** [comment]
I end up using `gptel-transient-send` to replace `gptel-send`
```emacs-lisp
(defun gptel-transient-send (&optional arg)
      "Call `gptel--suffix-send' with latest history."
      (interactive "P")
      (if (and arg (require 'gptel-transient nil t))
          (call-interactively #'gptel-menu)
        (let* ((obj (plist-get (symbol-plist 'gptel-menu) 'transient--prefix))
               (hst (alist-get (transient--history-key obj)
                               transient-history))
               (args (nth 0 hst)))
          (gptel--suffix-send args))))
```

**Comment by karthink** [comment]
> Here is a user-side solution, you can run `C-x C-s` to save infixes after modification. And call `gptel-transient-send` to reuse saved flags:

Wow, thanks for pointing this out! Making Transient flags persistent is a problem best handled by Transient itself. Trying to do it in gptel would be very messy.

**Comment by karthink** [comment]
I am considering the issue resolved and @tshu-w's method as the solution here. It might be worth adding this to the wiki at some point. @garrett-hopper if you have any specific concerns feel free to re-open.

**Comment by karthink** [comment]
I've added a [section to the wiki](https://github.com/karthink/gptel/wiki#save-transient-flags) with a simple solution, reproduced here:

> You can replace your usage of `gptel-send` with the following command if you want these options to be applied without having to bring up the menu:

```elisp
(put 'gptel--suffix-send 'interactive-only nil)

(defun gptel-send-with-options (&optional arg)
  "Send query.  With prefix ARG open gptel's menu instead."
  (interactive "P")
  (if arg
      (call-interactively 'gptel-menu)
    (gptel--suffix-send (transient-args 'gptel-menu))))
```
