### ISSUE TITLE
Should we quit `gptel-system-prompt` after select?

### ISSUE THREAD

**Issue by tshu-w** [karthink/gptel#95]
I prefer to quit `gptel-system-prompt` after select a directive

 I'd like to know what you think.

**Comment by karthink** [comment]
My idea when making this persist was that you can't preview the directive before you choose it, so the user might want to press (in this example) `p`, `d`, `c`, `w` etc and read the "current directive" header before finalizing their choice:
![2023-07-30-123230_762x215_scrot](https://github.com/karthink/gptel/assets/8607532/0c1f53c0-d57c-4ef8-b372-a34288b64237)

That said, the current directive is shown here in the main `gptel-menu` as well:
![2023-07-30-123426_767x276_scrot](https://github.com/karthink/gptel/assets/8607532/6a4101de-1aa6-4eae-8a70-56a0f2643439)

So what you suggest makes sense too. It would take two keys now -- `hp`, `hd`, `hc`, `hw` etc -- to preview directives. Let me try your PR for a couple of days and see if it works better this way.

**Comment by tshu-w** [comment]
<img width="1290" alt="Screenshot 2023-07-31 at 10 48 39" src="https://github.com/karthink/gptel/assets/13161779/be59c723-b535-42c0-bfd6-e1f5184392dd">
And the directive will show in the echo area after selection too.  For me, I'll be pretty sure of each selection and there are rarely multiple switches, so I want to avoid redundant exits press.

**Comment by karthink** [comment]
It works well, thank you for the PR.
