### ISSUE TITLE
Save chat directive

### ISSUE THREAD

**Issue by Ypot** [karthink/gptel#99]
Is it possible to save the directive too?

Something like:
:PROPERTIES:
:GPTEL_MODEL: gpt-3.5-turbo
:GPTEL_TOPIC: Emacs
:GPTEL_BOUNDS: ((366 . 2275) (2320 . 3195) (3230 . 4624))
:GPTEL_DIRECTIVE: You are Richard Stallman
:END:

**Comment by karthink** [comment]
Yes, all state is saved. Try changing the directive and saving the file.

**Comment by karthink** [comment]
I'm assuming this issue is resolved. Please reopen if it doesn't work as expected.

**Comment by Ypot** [comment]
Hi. 
Yes, it works. Thanks. Although I had some rare issues: when I saved the directive changed, if this repeats itself I will let you know.

Best regards
